Repository Automattic/newspack-theme, pull requests merged in 2019-09, with the labels that each got.

#327 Correct font weights, uses, in style 2, to better match the designs
  inc/style-packs.php
  inc/typography.php
  sass/styles/style-2/style-2-editor.scss
  sass/styles/style-2/style-2.scss
Labels: [Status] Approved

#333 Cover Block: Fix section header contrast issue with homepage block
  inc/color-patterns.php
  sass/style-editor-base.scss
  sass/styles/style-2/style-2.scss
  sass/styles/style-3/style-3.scss
  sass/styles/style-4/style-4-editor.scss
  sass/styles/style-4/style-4.scss
Labels: Smaller PR, [Status] Approved

#328 Update column spacing when the border style is used
  sass/blocks/_blocks.scss
  sass/style-editor-base.scss
Labels: Smaller PR, [Status] Approved

#340 Adds image size for the non-single views (archive, search, blog index).
  functions.php
  inc/template-tags.php
Labels: Smaller PR, [Status] Approved

#341 Cover Block: Improve styles for cover blocks when floated left or right
  sass/blocks/_blocks.scss
  sass/style-editor-base.scss
Labels: [Status] Approved

#342 Cover block: Update widths to display correctly on the static front page
  sass/blocks/_blocks.scss
  sass/style-editor-overrides.scss
Labels: Smaller PR, [Status] Approved

#353 Footer: Fix 'site info' spacing
  footer.php
  sass/site/footer/_site-footer.scss
Labels: Smaller PR, [Status] Approved

#354 Make sure blocks nested in wide and full blocks don't get too wide
  sass/blocks/_blocks.scss
Labels: [Status] Approved

#356 Locale pt br
  languages/pt_BR.mo
  languages/pt_BR.po
Labels: [Status] Approved

#359 Fix issue where captioned images were pulled out of the content area.
  sass/media/_captions.scss
Labels: Smaller PR, [Status] Approved

#334 Style 3: Update column border styles
  sass/styles/style-3/style-3-editor.scss
  sass/styles/style-3/style-3.scss
  sass/variables-site/_structure.scss
Labels: [Status] Approved

#343 Centred Logo: Allow for larger logos when centred
  functions.php
  inc/logo-resizer.php
  js/logo/customize-preview.js
  sass/navigation/_menu-tertiary-navigation.scss
  sass/site/header/_site-header.scss
Labels: [Status] Approved

#355 Add PWA feature support
  functions.php
Labels: [Status] Approved

#376 Style 1: Rework Pullquote styles so they work in Cover Blocks
  inc/color-patterns.php
  inc/typography.php
  sass/styles/style-1/style-1-editor.scss
  sass/styles/style-1/style-1.scss
Labels: [Status] Approved

#377 Style 3: Remove 'overlap' style when the block is in a group or cover block
  sass/styles/style-3/style-3-editor.scss
  sass/styles/style-3/style-3.scss
Labels: Smaller PR, [Status] Approved

#378 Fix alignment in comment count in footer
  sass/site/primary/_comments.scss
Labels: Smaller PR, [Status] Approved

#380 Fix issue with custom colours in entry footer.
  inc/color-patterns.php
Labels: Smaller PR, [Status] Approved

#381 Fix button padding when nested in a floated cover block
  sass/blocks/_blocks.scss
  sass/style-editor-base.scss
Labels: Smaller PR, [Status] Approved

#384 Fix issue where cover block collapses when focused on in editor.
  sass/style-editor-base.scss
Labels: Smaller PR, [Status] Approved

#385 Update font sizes to be relative to the base size.
  functions.php
  sass/blocks/_blocks.scss
Labels: Smaller PR, [Status] Approved

#386 Style 3: Make sure post meta (author and published date) aren't large…
  sass/styles/style-3/style-3-editor.scss
  sass/styles/style-3/style-3.scss
Labels: Smaller PR, [Status] Approved

#388 Style 2: Remove overlap styles from header on smaller screens.
  inc/color-patterns.php
  sass/styles/style-2/style-2.scss
Labels: [Status] Approved

#383 Fix donation block custom colours
  inc/color-patterns.php
Labels: [Status] Approved

#382 Make accent header class more consistent with article block section headers
  sass/blocks/_blocks.scss
  sass/styles/style-2/style-2.scss
  sass/styles/style-3/style-3-editor.scss
  sass/styles/style-3/style-3.scss
  sass/styles/style-4/style-4.scss
  sass/typography/_headings.scss
Labels: [Status] Approved

#387 Style 2: Make sure the menu toggle uses the all-caps
  inc/typography.php
Labels: Smaller PR, [Status] Approved

#379 Add widget area above and below post content
  functions.php
  sass/site/secondary/_widgets.scss
  single-feature.php
  single-wide.php
  single.php
  template-parts/content/content-single.php
Labels: [Status] Approved

#398 Only define newspack_is_amp if it's not already defined
  functions.php
Labels: [Status] Approved

#395 Fixes excessive spacing on top of articles
  sass/site/primary/_posts-and-pages.scss
Labels: Smaller PR, [Status] Approved

#401 Fixes issue with disappeared homepage title
  front-page.php
Labels: Smaller PR, [Status] Approved

#400 Set Up A Build Pipeline
  .gitignore
  .prettierrc
  babel.config.js
  classes/class-newspack-style-packs-core.php
  functions.php
  inc/customizer.php
  inc/logo-resizer.php
  js/originals/skip-link-focus-fix.js
  js/src/amp-fallback.js
  js/src/customize-controls.js
  js/src/customize-preview.js
  js/src/logo-customize-controls.js
  js/src/logo-customize-preview.js
  js/src/style-packs-customizer.js
  package-lock.json
  package.json
  webpack.config.js
Labels: [Status] Approved

#390 Single Post: First pass at adding featured image position option, to display behind title
  functions.php
  inc/template-functions.php
  js/src/extend-featured-image-editor.js
  sass/site/primary/_posts-and-pages.scss
  single-feature.php
  single-wide.php
  single.php
Labels: [Status] Approved

#397 Make sure you can't "tab into" a closed mobile menu
  sass/navigation/_menu-mobile-navigation.scss
Labels: Smaller PR, [Status] Approved

#399 Moves the keyboard focus to the 'close' button when mobile menu is opened
  js/amp-fallback.js
Labels: Smaller PR, [Status] Approved

#402 Fix focus contrast issues with search, text inputs
  inc/color-patterns.php
  sass/forms/_fields.scss
Labels: [Status] Approved

#405 Improve appearance of mobile menu
  inc/color-patterns.php
  sass/navigation/_menu-mobile-navigation.scss
Labels: [Status] Approved

#410 Fixes donate block custom colours on homepage
  inc/color-patterns.php
Labels: Smaller PR, [Status] Approved

#411 Cover Block: Reduce the amount of padding on the cover block further
  sass/blocks/_blocks.scss
  sass/style-editor-base.scss
Labels: Smaller PR, [Status] Approved

#412 Remove top and bottom no margin from nested blocks
  sass/blocks/_blocks.scss
Labels: Smaller PR, [Status] Approved

#413 Update styles to work better with hidden avatars
  sass/site/primary/_comments.scss
  sass/site/primary/_posts-and-pages.scss
Labels: Smaller PR, [Status] Approved

#415 Fix vertical spacing in site footer on smaller screens
  footer.php
  sass/site/footer/_site-footer.scss
Labels: Smaller PR, [Status] Approved

#409 Fix button focus colour
  sass/forms/_buttons.scss
Labels: Smaller PR, [Status] Approved

#421 Cover Block: Override `height: 100%` when nested in columns block
  sass/blocks/_blocks.scss
Labels: Smaller PR, [Status] Approved

#407 Improve appearance of featured image when set as background
  inc/template-functions.php
  sass/site/primary/_posts-and-pages.scss
  sass/styles/style-2/style-2.scss
  sass/styles/style-4/style-4.scss
  sass/styles/style-default/style-default.scss
  single-feature.php
  single-wide.php
  single.php
Labels: [Status] Approved

#396 Editor: Make sure wide template editor preview is correct
  functions.php
  sass/style-editor-overrides.scss
Labels: Smaller PR, [Status] Approved

#417 Tighten up the spacing on the primary menu when using the short header
  sass/navigation/_menu-main-navigation.scss
Labels: Smaller PR, [Status] Approved

#418 Reduce vertical spacing on solid-background headers
  sass/site/header/_site-header.scss
Labels: Smaller PR, [Status] Approved

#419 Remove bottom spacing from blocks nested inside of column or group blocks
  sass/blocks/_blocks.scss
Labels: Smaller PR, [Status] Approved

#428 Make sure git only ignores files in the root styles directory
  .gitignore
Labels: Smaller PR, [Status] Needs review

#394 Rework caption styles
  sass/blocks/_blocks.scss
  sass/media/_captions.scss
  sass/style-editor-base.scss
  sass/style-editor-overrides.scss
Labels: [Status] Approved

#422 Add bottom border to mobile header
  inc/color-patterns.php
  sass/site/header/_site-header.scss
  sass/styles/style-2/style-2.scss
Labels: [Status] Approved

#423 Only show featured image option on posts
  js/src/extend-featured-image-editor.js
Labels: Smaller PR, [Status] Approved

#426 Fix issue where floated image inside of a column pops out of the side
  sass/style-editor-base.scss
Labels: Smaller PR, [Status] Approved

#424 Make sure the author bio is not displayed on single posts and pages.
  template-parts/post/author-bio.php
Labels: Smaller PR, [Status] Approved

#425 Single Article: Add style to place featured image and article title side by side
  functions.php
  inc/color-patterns.php
  inc/template-functions.php
  js/src/extend-featured-image-editor.js
  sass/site/header/_site-header.scss
  sass/site/primary/_posts-and-pages.scss
  sass/styles/style-1/style-1.scss
  sass/styles/style-2/style-2.scss
  sass/styles/style-3/style-3.scss
  sass/styles/style-4/style-4.scss
  sass/styles/style-default/style-default.scss
  single-feature.php
  single-wide.php
  single.php
  template-parts/post/large-featured-image.php
Labels: [Status] Approved

#55 Fix issue with style pack preview overriding custom colours and fonts
  classes/class-newspack-style-packs-core.php
  inc/style-packs.php
  js/src/style-packs-customizer.js
Labels: [Status] Approved
