Repository Automattic/newspack-theme, pull requests merged in 2019-10, with the labels that each got.

#427 Make sure editor correctly reflects widths, and block widths/alignments.
  functions.php
  sass/style-editor-base.scss
  sass/style-editor-overrides.scss
Labels: [Status] Approved

#429 Take another pass at improving the dropdown menu styles
  inc/color-patterns.php
  sass/navigation/_menu-main-navigation.scss
  sass/styles/style-3/style-3.scss
  sass/styles/style-4/style-4.scss
Labels: [Status] Approved

#447 Widgets: Fix issue with "top post" image width
  sass/site/secondary/_widgets.scss
Labels: Smaller PR, [Status] Approved

#448 Fix up styles for related posts block
  inc/typography.php
  sass/blocks/_blocks.scss
  sass/style-editor-base.scss
  sass/styles/style-3/style-3-editor.scss
  sass/styles/style-3/style-3.scss
Labels: [Status] Needs review

#430 Improve appearance of style 3 + captions for the article blocks.
  sass/styles/style-3/style-3-editor.scss
  sass/styles/style-3/style-3.scss
Labels: [Status] Approved

#450 Tweaks to the comment templates for Renaming Comments
  comments.php
  template-parts/post/discussion-meta.php
Labels: [Status] Approved

#458 Add 'Highlight/focus on' menu to theme
  functions.php
  header.php
  inc/color-patterns.php
  inc/typography.php
  sass/navigation/_menu-highlight-navigation.scss
  sass/navigation/_navigation.scss
  sass/site/header/_site-header.scss
  sass/styles/style-2/style-2.scss
  sass/styles/style-3/style-3.scss
  sass/styles/style-4/style-4.scss
Labels: [Status] Approved

#440 Adjust mobile menu breakpoint
  sass/mixins/_utilities.scss
  sass/navigation/_menu-mobile-navigation.scss
  sass/site/header/_site-header.scss
  sass/variables-site/_structure.scss
Labels: Smaller PR, [Status] Approved

#446 Hide Jetpack-specific comments header
  sass/site/primary/_comments.scss
Labels: Smaller PR, [Status] Approved

#451 Make sure the special featured image classes are only applied to single posts
  inc/template-functions.php
Labels: Smaller PR, [Status] Approved

#459 Remove extra spacing from bottom of homepage
  sass/blocks/_blocks.scss
  sass/site/primary/_posts-and-pages.scss
Labels: Smaller PR, [Status] Approved

#460 Recent Posts widget: Fix up vertical spacing, colours
  sass/site/secondary/_widgets.scss
Labels: Smaller PR, [Status] Approved

#463 Style 3: Fix issue with category customizer inheritance
  inc/color-patterns.php
Labels: Smaller PR, [Status] Approved

#462 Add option to hide entire Author Bio
  inc/customizer.php
  inc/template-functions.php
  js/src/customize-preview.js
  sass/site/primary/_posts-and-pages.scss
Labels: [Status] Approved

#468 Remove 'entry-summary' classes from block styles
  sass/blocks/_blocks.scss
Labels: Smaller PR, [Status] Approved

#473 Style 5: Make sure the figcaption uses the body font
  inc/typography.php
  sass/styles/style-5/style-5-editor.scss
  sass/styles/style-5/style-5.scss
Labels: [Status] Approved

#466 Cover block: Tighten up spacing on cover blocks
  sass/blocks/_blocks.scss
  sass/style-editor-base.scss
Labels: [Status] Approved

#469 Paragraph Block: Simplify styles
  inc/color-patterns.php
  inc/typography.php
  sass/blocks/_blocks.scss
  sass/styles/style-1/style-1.scss
  sass/styles/style-2/style-2.scss
  sass/styles/style-3/style-3.scss
  sass/styles/style-4/style-4.scss
  sass/styles/style-5/style-5.scss
Labels: [Status] Approved

#474 Make sure 'highlight menu' inherits header font.
  inc/typography.php
Labels: Smaller PR, [Status] Approved

#479 Update styles for style 3 to work with the 'image behind the article' block style
  sass/styles/style-3/style-3-editor.scss
  sass/styles/style-3/style-3.scss
Labels: Smaller PR, [Status] Approved

#476 Columns Block: Fix selector for last child
  sass/blocks/_blocks.scss
Labels: Smaller PR, [Status] Approved

#481 Make styles to hide 'highlight menu' more specific
  sass/navigation/_menu-highlight-navigation.scss
Labels: Smaller PR, [Status] Approved

#480 Add object fit AMP fix to behind, beside image styles
  inc/template-tags.php
Labels: [Status] Approved

#485 Update the Primary Color to use Newspack new blue: `#36f`
  functions.php
  inc/color-filters.php
  sass/plugins/woocommerce.scss
  sass/variables-site/_colors.scss
Labels: [Status] Approved

#487 Fix minor issue in style 5 header when highlight menu is assigned.
  sass/styles/style-5/style-5.scss
Labels: [Status] Approved

#489 Add captions to featured images
  inc/template-tags.php
  sass/site/primary/_posts-and-pages.scss
  sass/styles/style-3/style-3.scss
  template-parts/post/large-featured-image.php
Labels: [Status] Approved

#494 Fix issue with spacing at the bottom of columns with borders.
  sass/blocks/_blocks.scss
Labels: [Status] Approved

#486 Style 5: Update the navigation to make sure it's using a dark background colour
  inc/color-patterns.php
  sass/styles/style-5/style-5.scss
Labels: [Status] Approved

#496 Make sure WooCommerce notice doesn't inherit primary colour.
  inc/woocommerce.php
Labels: Smaller PR, [Pri] High, [Status] Approved

#502 Style 2: Make sure site info links don't disappear on hover
  sass/styles/style-2/style-2.scss
Labels: Smaller PR, [Pri] High, [Status] Approved

#503 Make buttons display inline-block.
  sass/forms/_buttons.scss
Labels: Smaller PR, [Pri] High, [Status] Approved

#493 Rework Columns Block by moving changes to Newspack Blocks
  sass/blocks/_blocks.scss
Labels: [Status] Approved

#500 Adjust avatar size on small screens to make the post header seem less crowded
  sass/site/primary/_posts-and-pages.scss
Labels: Smaller PR, [Status] Approved

#501 Add option to hide author email from bios
  inc/customizer.php
  inc/template-functions.php
  js/src/customize-controls.js
  js/src/customize-preview.js
  sass/site/primary/_posts-and-pages.scss
  template-parts/post/author-bio.php
Labels: [Status] Approved

#508 Fix avatar duplication
  inc/template-tags.php
  template-parts/post/author-bio.php
Labels: [Status] Approved

#512 Don't remove checkout sidebars
  inc/woocommerce.php
Labels: [Status] Approved

#513 Fix up some of the styles in the new footer widget area
  sass/site/footer/_site-footer.scss
Labels: [Status] Approved

#498 Fix styles for article block categories
  inc/color-patterns.php
  inc/typography.php
  sass/style-editor-base.scss
  sass/styles/style-1/style-1.scss
  sass/styles/style-2/style-2-editor.scss
  sass/styles/style-2/style-2.scss
  sass/styles/style-3/style-3.scss
  sass/styles/style-4/style-4.scss
  sass/styles/style-5/style-5.scss
  sass/styles/style-default/style-default.scss
Labels: [Status] Approved

#510 Correct initial check for author bio
  js/src/customize-controls.js
Labels: Smaller PR, [Status] Approved

#467 Fix issue with custom colour inheritance in editor.
  inc/color-patterns.php
Labels: Smaller PR, [Status] Approved

#518 "Above Copyright" footer widget spacing fix
  sass/site/footer/_site-footer.scss
Labels: Smaller PR, [Status] Approved

#520 Style 3: Fix article border styles
  sass/styles/style-3/style-3-editor.scss
  sass/styles/style-3/style-3.scss
Labels: Smaller PR, [Status] Approved

#521 Update check for image size to add body class
  inc/template-functions.php
Labels: Smaller PR, [Status] Approved

#522 Style 3: Fix Article Block image overlap
  sass/styles/style-3/style-3.scss
Labels: Smaller PR, [Status] Approved

#524 Update Article block category styles
  inc/color-patterns.php
  inc/typography.php
  sass/styles/style-2/style-2.scss
  sass/styles/style-3/style-3.scss
Labels: [Status] Approved

#526 Style 3: Fix 'image behind' styles with block
  sass/styles/style-3/style-3-editor.scss
  sass/styles/style-3/style-3.scss
Labels: [Status] Approved

#528 Add 'display=swap' to style pack Google Font query strings
  inc/style-packs.php
Labels: Smaller PR, [Status] Approved

#523 PWA: Add 'offline.php' template
  header.php
  offline.php
  sass/layout/_layout.scss
Labels: [Status] Approved

#538 Fix issue with missing image causing display problems.
  sass/site/primary/_archives.scss
Labels: Smaller PR, [Status] Needs review

#539 Only display primary category on singles if set
  inc/template-tags.php
Labels: [Status] Approved
