Repository Automattic/newspack-theme, pull requests merged in 2019-08, with the labels that each got.

#139 Clean up image block styles
  sass/blocks/_blocks.scss
  sass/style-editor-base.scss
Labels: Smaller PR, [Status] Needs review

#142 Move some of the more opinionated default styles out of the 'base' stylesheet
  sass/style.scss
  sass/styles/style-1/style-1.scss
  sass/styles/style-default/style-default.scss
  sass/typography/_headings.scss
Labels: Smaller PR, [Status] Approved

#145 Switch #ccc colour to use the existing (and matching) colour variabl …
  sass/plugins/woocommerce.scss
  sass/site/footer/_site-footer.scss
  sass/style-editor-base.scss
Labels: Smaller PR, [Status] Approved

#143 Prevent enqueuing scripts on AMP responses
  composer.json
  composer.lock
  functions.php
Labels: [Status] Approved

#146 Update table block styles
  sass/blocks/_blocks.scss
  sass/elements/_tables.scss
  sass/style-editor-base.scss
Labels: Smaller PR, [Status] Approved

#119 Adds option for 'simplified' header
  header.php
  inc/customizer.php
  inc/template-functions.php
  sass/navigation/_menu-tertiary-navigation.scss
  sass/site/header/_site-header.scss
Labels: Larger PR, [Status] Approved

#152 Move more opinionated 'tertiary menu' styles to the default style.scss.
  sass/navigation/_menu-tertiary-navigation.scss
  sass/style.scss
  sass/styles/style-default/style-default.scss
Labels: Smaller PR, [Status] Approved

#151 Update approach wide and full styles
  sass/blocks/_blocks.scss
Labels: [Status] Approved

#149 Add custom typography to editor
  functions.php
  inc/typography.php
Labels: Larger PR, [Status] Approved

#154 More more opinionated category styles
  inc/color-patterns.php
  inc/template-tags.php
  sass/site/primary/_archives.scss
  sass/site/primary/_posts-and-pages.scss
  sass/styles/style-default/style-default.scss
Labels: [Status] Approved

#155 Switch tables to use the body font
  sass/elements/_tables.scss
  sass/style-editor-base.scss
Labels: Smaller PR, [Status] Approved

#153 WooCommerce Checkout styles
  inc/woocommerce.php
  sass/plugins/woocommerce.scss
  woocommerce/checkout/form-checkout.php
Labels: [Status] Approved

#156 Add hooks for additional ad locations
  footer.php
  header.php
  sidebar.php
Labels: [Status] Approved

#157 Removes remaining original menu cruft 🔥
  functions.php
  inc/template-functions.php
  js/touch-keyboard-navigation.js
Labels: Larger PR, [Status] Approved

#160 Switch max-width to width for sidebar and content areas
  sass/layout/_layout.scss
Labels: Smaller PR, [Status] Needs review

#159 Make sure default style is properly dequeued
  classes/class-newspack-style-packs-core.php
Labels: Smaller PR, [Status] Approved

#161 Remove 'smart' text colours with solid background colours
  sass/blocks/_blocks.scss
  sass/style-editor-base.scss
Labels: Smaller PR, [Status] Approved

#158 Adds amp mobile menu functionality
  classes/class-newspack-svg-icons.php
  footer.php
  functions.php
  header.php
  inc/template-tags.php
  sass/navigation/_menu-main-navigation.scss
  sass/navigation/_menu-mobile-navigation.scss
  sass/navigation/_menu-secondary-navigation.scss
  sass/navigation/_menu-social-navigation.scss
  sass/navigation/_menu-tertiary-navigation.scss
  sass/navigation/_navigation.scss
  sass/site/header/_site-header.scss
  sass/styles/style-default/style-default.scss
  sass/typography/_headings.scss
  template-parts/footer/footer-branding.php
  template-parts/header/mobile-sidebar.php
Labels: Larger PR, [Status] Needs review

#173 Style C: Add option for 'Style 2', and update header and body fonts
  inc/style-packs.php
  package.json
  sass/styles/style-2/style-2-editor.scss
  sass/styles/style-2/style-2.scss
  sass/styles/style-2/variables-style/_fonts.scss
  sass/styles/style-2/variables-style/_variables-style.scss
Labels: Smaller PR, [Status] Approved

#165 Fixes alignment issue with full-width blocks on static front page
  sass/blocks/_blocks.scss
Labels: Smaller PR, [Status] Approved

#163 Fix positioning issue for search icon + AMP
  header.php
  sass/site/header/_site-header.scss
Labels: [Status] Approved

#164 Move opinionated footer styles to the default style variation
  sass/site/footer/_site-footer.scss
  sass/styles/style-default/style-default.scss
Labels: Smaller PR, [Status] Approved

#167 Move opinionated accent header styles from general editor styles
  sass/style-editor-base.scss
  sass/style-editor.scss
  sass/styles/style-1/style-1-editor.scss
  sass/styles/style-default/style-default-editor.scss
Labels: Smaller PR, [Status] Approved

#172 Style B: Update author name colour
  sass/styles/style-1/style-1-editor.scss
  sass/styles/style-1/style-1.scss
Labels: Smaller PR, [Status] Approved

#177 Make the spacing between the primary and tertiary navigations more consistent
  sass/navigation/_menu-main-navigation.scss
  sass/navigation/_menu-tertiary-navigation.scss
  sass/site/header/_site-header.scss
Labels: Smaller PR, [Status] Approved

#166 Style pack B: update 'accent' headers
  classes/class-newspack-style-packs-core.php
  inc/color-patterns.php
  inc/style-packs.php
  sass/styles/style-1/style-1-editor.scss
  sass/styles/style-1/style-1.scss
  sass/styles/style-1/variables-style/_fonts.scss
Labels: [Status] Approved

#169 Style B: Add square image styles for the avatars
  sass/styles/style-1/style-1-editor.scss
  sass/styles/style-1/style-1.scss
Labels: Smaller PR, [Status] Approved

#170 Style B: Update footer styles
  sass/styles/style-1/style-1.scss
Labels: Smaller PR, [Status] Approved

#171 Style B: Add dropcap styles
  inc/typography.php
  sass/styles/style-1/style-1-editor.scss
  sass/styles/style-1/style-1.scss
Labels: Smaller PR, [Status] Approved

#180 Add stylesheets, build process and fonts for 'Style D'
  inc/style-packs.php
  package.json
  sass/styles/style-3/style-3-editor.scss
  sass/styles/style-3/style-3.scss
  sass/styles/style-3/variables-style/_fonts.scss
  sass/styles/style-3/variables-style/_variables-style.scss
Labels: Smaller PR, [Status] Approved

#181 Add stylesheets, build process and fonts for 'Style E'.
  inc/style-packs.php
  package.json
  sass/styles/style-4/style-4-editor.scss
  sass/styles/style-4/style-4.scss
  sass/styles/style-4/variables-style/_fonts.scss
  sass/styles/style-4/variables-style/_variables-style.scss
Labels: Smaller PR, [Status] Approved

#168 Style B: Add Pullquote block styles to front-end.
  inc/color-patterns.php
  sass/blocks/_blocks.scss
  sass/elements/_elements.scss
  sass/styles/style-1/style-1.scss
Labels: [Status] Approved

#182 Style C: Update accent headers
  inc/color-patterns.php
  sass/styles/style-2/style-2-editor.scss
  sass/styles/style-2/style-2.scss
Labels: [Status] Approved

#183 Replace ':not' pseudo-selectors for the header with classes
  inc/template-functions.php
  sass/navigation/_menu-main-navigation.scss
  sass/site/header/_site-header.scss
  sass/styles/style-default/style-default.scss
Labels: Smaller PR, [Status] Approved

#184 Style B: Style author name, date side by side
  sass/styles/style-1/style-1.scss
Labels: Smaller PR, [Status] Approved

#185 Style C: Add pullquote styles
  sass/styles/style-2/style-2-editor.scss
  sass/styles/style-2/style-2.scss
Labels: [Status] Approved

#187 Style C: Update header font styles
  sass/styles/style-2/style-2.scss
Labels: Smaller PR, [Status] Approved

#190 Style C: Swap Monserrat 400 for 500, so it's a bit stronger
  inc/style-packs.php
Labels: Smaller PR, [Status] Approved

#189 Style C: Add dividing border above the author profile
  sass/styles/style-2/style-2.scss
Labels: Smaller PR, [Status] Approved

#193 Move header options to own Customizer section
  inc/customizer.php
Labels: Smaller PR, [Status] Approved

#195 Style C: Add styles for entry footer tags.
  inc/color-patterns.php
  sass/styles/style-2/style-2.scss
Labels: Smaller PR, [Status] Approved

#188 Style C: Updates author link style, entry meta border on single posts.
  sass/styles/style-2/style-2-editor.scss
  sass/styles/style-2/style-2.scss
Labels: Smaller PR, [Status] Approved

#196 Style D: Add accent header styles
  inc/color-patterns.php
  sass/styles/style-3/style-3-editor.scss
  sass/styles/style-3/style-3.scss
Labels: [Status] Approved

#198 Style D: Adds dropcap styles
  inc/typography.php
  sass/styles/style-3/style-3-editor.scss
  sass/styles/style-3/style-3.scss
Labels: Smaller PR, [Status] Approved

#199 Style D: Add styles for post tags.
  inc/color-patterns.php
  sass/styles/style-3/style-3.scss
Labels: Smaller PR, [Status] Approved

#200 Style D: Add pullquote styles.
  sass/styles/style-3/style-3-editor.scss
  sass/styles/style-3/style-3.scss
Labels: [Status] Approved

#202 Style D: Add image caption styles
  inc/color-patterns.php
  sass/styles/style-3/style-3-editor.scss
  sass/styles/style-3/style-3.scss
Labels: Smaller PR, [Status] Approved

#197 Style D: Add entry meta -- byline and published date -- styles.
  inc/color-patterns.php
  sass/styles/style-3/style-3-editor.scss
  sass/styles/style-3/style-3.scss
Labels: [Status] Approved

#201 Style D: Add cutout styles for homepage article blocks
  sass/styles/style-3/style-3-editor.scss
  sass/styles/style-3/style-3.scss
Labels: Smaller PR, [Status] Approved

#204 Style E: Rough in accent header styles
  functions.php
  inc/color-patterns.php
  sass/styles/style-4/style-4-editor.scss
  sass/styles/style-4/style-4.scss
Labels: [Status] Approved

#207 Style E: Add styles to center post title in editor
  functions.php
  sass/style-editor-overrides.scss
Labels: Smaller PR, [Status] Approved

#208 Style E: Adds styles for author bio
  sass/styles/style-4/style-4.scss
  template-parts/post/author-bio.php
Labels: [Status] Approved

#205 Style E: Add dropcap styles
  inc/color-patterns.php
  inc/typography.php
  sass/styles/style-4/style-4-editor.scss
  sass/styles/style-4/style-4.scss
Labels: Smaller PR, [Status] Approved

#206 Style E: Build out single post headers
  sass/style-editor-base.scss
  sass/styles/style-4/style-4.scss
Labels: Smaller PR, [Status] Approved

#217 Style E: Add styles for story tags
  inc/color-patterns.php
  sass/styles/style-4/style-4.scss
Labels: Smaller PR, [Status] Approved

#223 Style E: Add styles for archive pages
  inc/typography.php
  sass/styles/style-4/style-4.scss
Labels: Smaller PR, [Status] Approved

#224 Style E: Add image caption styles
  sass/styles/style-4/style-4-editor.scss
  sass/styles/style-4/style-4.scss
Labels: Smaller PR, [Status] Approved

#219 Style E: Build out pullquote styles
  inc/typography.php
  sass/styles/style-4/style-4-editor.scss
  sass/styles/style-4/style-4.scss
Labels: [Status] Approved

#191 Style C: Add styles for dropcap
  inc/color-patterns.php
  inc/typography.php
  sass/style-editor-base.scss
  sass/styles/style-2/style-2-editor.scss
  sass/styles/style-2/style-2.scss
  sass/styles/style-4/style-4-editor.scss
Labels: [Status] Approved

#211 Style E: Add styles for footer.
  inc/color-patterns.php
  sass/styles/style-4/style-4.scss
Labels: Smaller PR, [Status] Approved

#226 Style A, D & E: Correct archive 'page title' custom colour behaviour
  inc/color-patterns.php
Labels: Smaller PR, [Status] Approved

#176 Style C: Add the styles to make the header overlap.
  inc/color-patterns.php
  sass/layout/_layout.scss
  sass/site/header/_site-header.scss
  sass/site/primary/_posts-and-pages.scss
  sass/styles/style-2/style-2.scss
Labels: Larger PR, [Status] Approved

#227 Style B: Update archive header colour
  sass/styles/style-1/style-1.scss
Labels: Smaller PR, [Status] Approved

#228 Style C: Build out styles for archive page headers
  inc/typography.php
  sass/styles/style-2/style-2.scss
  sass/variables-site/_fonts.scss
Labels: Smaller PR, [Status] Approved

#229 Style C: Fix up top spacing on single posts, pages and archives
  sass/styles/style-2/style-2.scss
Labels: Smaller PR, [Status] Approved

#232 Style B: Add pullquote styles to editor
  inc/color-patterns.php
  inc/typography.php
  sass/styles/style-1/style-1-editor.scss
  sass/styles/style-1/style-1.scss
Labels: [Status] Approved

#233 Style B: Make sure pullquote block inherits custom fonts
  inc/typography.php
Labels: Smaller PR, [Status] Approved

#234 Reduce size of single post headers on smaller screens.
  sass/site/primary/_posts-and-pages.scss
  sass/style-editor-overrides.scss
Labels: Smaller PR, [Status] Approved

#235 Mobile menu: Make sure mobile menu inherits the custom colours
  inc/color-patterns.php
  sass/navigation/_menu-mobile-navigation.scss
Labels: Smaller PR, [Status] Approved

#192 Phpstan
  classes/class-newspack-style-packs-core.php
  comments.php
  composer.json
  composer.lock
  inc/customizer.php
  inc/icon-functions.php
  inc/template-functions.php
  phpcs.xml.dist
  phpstan.neon.dist
  tests/bootstrap.php
  tests/functions-stubs.php
Labels: [Status] Approved

#240 Author Bio: Remove placeholder 'Staff Writer' string from author bio
  template-parts/post/author-bio.php
Labels: Smaller PR, [Status] Approved

#238 Style D: Add footer styles.
  sass/styles/style-3/style-3.scss
  sass/variables-site/_colors.scss
Labels: Smaller PR, [Status] Approved

#242 Custom Colours: Make sure essential items have sufficient contrast
  inc/color-patterns.php
Labels: [Status] Approved

#244 Style E: Update solid background header styles.
  inc/color-patterns.php
  sass/styles/style-4/style-4.scss
Labels: Smaller PR, [Status] Approved

#245 Style C: Adjust content padding on the front page.
  sass/styles/style-2/style-2.scss
Labels: Smaller PR, [Status] Approved

#250 Centre Logo: Fix alignment
  header.php
  sass/navigation/_menu-main-navigation.scss
  sass/navigation/_menu-tertiary-navigation.scss
  sass/site/header/_site-header.scss
Labels: [Status] Approved

#251 Centred Logo: Fixes centred dropdowns.
  sass/navigation/_menu-main-navigation.scss
Labels: Smaller PR, [Status] Approved

#237 Menu: Simplify menu styles
  inc/color-patterns.php
  sass/navigation/_menu-main-navigation.scss
  sass/navigation/_menu-mobile-navigation.scss
  sass/navigation/_menu-secondary-navigation.scss
  sass/navigation/_menu-tertiary-navigation.scss
  sass/styles/style-2/style-2.scss
  sass/typography/_headings.scss
Labels: [Status] Approved

#252 Solid Header: Improving vertical spacing, appearance
  inc/color-patterns.php
  sass/navigation/_menu-secondary-navigation.scss
  sass/site/header/_site-header.scss
Labels: Smaller PR, [Status] Approved

#241 Short Header + Left logo: Fix menu alignments
  inc/template-functions.php
  js/customize-preview.js
  sass/navigation/_menu-mobile-navigation.scss
  sass/site/header/_site-header.scss
Labels: [Status] Approved

#253 Style E: Fix entry title font weight in editor.
  sass/styles/style-4/style-4-editor.scss
Labels: Smaller PR, [Status] Approved

#255 Adds class to let you 'highlight' a tertiary menu item
  inc/color-patterns.php
  sass/navigation/_menu-main-navigation.scss
  sass/navigation/_menu-tertiary-navigation.scss
Labels: Smaller PR, [Status] Approved

#256 Fix issue with mis-aligned logo in footer
  sass/site/header/_site-header.scss
Labels: Smaller PR, [Status] Approved

#257 Minor: Tone down default header borders
  sass/site/header/_site-header.scss
Labels: Smaller PR, [Status] Approved

#258 Minor: Adds bottom border when there is no background on the simplified header
  sass/site/header/_site-header.scss
Labels: Smaller PR, [Status] Approved

#259 Style C: Make only single post heading narrow, not whole content area.
  sass/styles/style-2/style-2.scss
Labels: Smaller PR, [Status] Approved

#260 Style C: Make only archive headers narrow, not the whole content area
  sass/styles/style-2/style-2.scss
Labels: Smaller PR, [Status] Approved

#246 Code simplification: helper function to check the current style pack.
  functions.php
  inc/color-patterns.php
  inc/typography.php
  template-parts/post/author-bio.php
Labels: [Status] Approved

#262 Pages: Restructure markup to match the single posts.
  page.php
  sass/layout/_layout.scss
  sass/site/primary/_posts-and-pages.scss
  template-parts/content/content-page.php
Labels: [Status] Approved

#247 Add styling for Newspack Ads
  header.php
  sass/plugins/newspack-ads.scss
  sass/style-base.scss
Labels: [Status] Approved

#263 Restructure the search results page a bit.
  sass/site/primary/_archives.scss
  search.php
Labels: Smaller PR, [Status] Approved

#266 Swap locations of the primary and tertiary navigation in the short header
  header.php
  sass/site/header/_site-header.scss
Labels: [Status] Approved

#265 Menus: Fixes multi-level dropdowns for the primary menu.
  sass/navigation/_menu-main-navigation.scss
Labels: [Status] Approved

#269 Style C: Fix first homepage block
  sass/styles/style-2/style-2.scss
Labels: Smaller PR, [Status] Approved

#270 Update secondary colour
  inc/color-patterns.php
  sass/blocks/_blocks.scss
  sass/elements/_elements.scss
  sass/forms/_buttons.scss
  sass/forms/_fields.scss
  sass/navigation/_links.scss
  sass/site/primary/_posts-and-pages.scss
  sass/site/secondary/_widgets.scss
  sass/styles/style-1/style-1.scss
  sass/styles/style-2/style-2.scss
  sass/variables-site/_colors.scss
Labels: [Status] Approved

#274 Fixes overflow issue with desktop menu when AMP is enabled.
  sass/navigation/_menu-main-navigation.scss
Labels: [Status] Approved, [Type] Bug

#277 Remove select colour from customizations.
  inc/color-patterns.php
  sass/elements/_elements.scss
Labels: Smaller PR, [Status] Approved

#271 Style B: Fix category font family
  sass/variables-site/_fonts.scss
Labels: Smaller PR, [Status] Approved

#279 Add POT file to theme
  languages/newspack-theme.pot
Labels: [Status] Approved

#281 Add first pass at Spanish translations
  languages/es_ES.mo
  languages/es_ES.po
Labels: [Status] Approved

#286 Do not enqueue comment-reply script in AMP context
  functions.php
Labels: AMP, [Status] Approved

#282 Cover Block: Make sure links inherit the white text colour.
  sass/blocks/_blocks.scss
  sass/style-editor-base.scss
Labels: Smaller PR, [Status] Approved

#289 Hide footer branding space if the site doesn't have branding
  footer.php
  sass/styles/style-1/style-1.scss
  sass/styles/style-default/style-default.scss
  template-parts/footer/footer-branding.php
Labels: Smaller PR, [Status] Approved

#290 Increase size of gaps between widgets.
  sass/site/footer/_site-footer.scss
Labels: Smaller PR, [Status] Approved

#293 Add hover styles to the top-level of menu.
  inc/color-patterns.php
  sass/navigation/_menu-main-navigation.scss
  sass/navigation/_menu-secondary-navigation.scss
  sass/navigation/_menu-social-navigation.scss
  sass/navigation/_menu-tertiary-navigation.scss
  sass/site/header/_site-header.scss
  sass/styles/style-default/style-default.scss
Labels: [Status] Approved

#295 Separators: Adding styles the separator blocks.
  sass/blocks/_blocks.scss
  sass/style-editor-base.scss
  sass/styles/style-2/style-2-editor.scss
  sass/styles/style-2/style-2.scss
  sass/styles/style-3/style-3-editor.scss
  sass/styles/style-3/style-3.scss
Labels: [Status] Approved

#296 Reduce minimum height of cover blocks when nested in columns blocks
  sass/blocks/_blocks.scss
  sass/style-editor-base.scss
Labels: Smaller PR, [Status] Approved

#298 Fix contrast issue with the Style 3 accent headers
  inc/color-patterns.php
Labels: Smaller PR, [Status] Approved

#300 Add release script
  .gitignore
  package.json
Labels: [Status] Approved

#283 Adds option for footer logo
  functions.php
  inc/customizer.php
  sass/site/footer/_site-footer.scss
  template-parts/footer/footer-branding.php
Labels: [Status] Approved

#297 Make sure the homepage block doesn't inherit the custom link colour
  inc/color-patterns.php
Labels: Smaller PR, [Status] Approved

#303 Add 'all-caps' option to the Typography settings, so it's optional.
  functions.php
  inc/customizer.php
  inc/typography.php
  sass/site/primary/_posts-and-pages.scss
  sass/styles/style-default/style-default-editor.scss
  sass/styles/style-default/style-default.scss
  sass/typography/_headings.scss
Labels: [Status] Approved

#304 Update theme screenshot
  screenshot.png
Labels: Smaller PR, [Status] Approved

#302 Cover Blocks: Remove/override default cover block font styles
  inc/color-patterns.php
  sass/blocks/_blocks.scss
  sass/style-editor-base.scss
Labels: Smaller PR, [Status] Approved

#314 Column Block: Remove theme's nowrap style for the columns block
  sass/blocks/_blocks.scss
Labels: Smaller PR, [Status] Approved

#315 Add additional colours to the theme palette.
  functions.php
  sass/blocks/_blocks.scss
Labels: [Status] Approved

#316 Cover Block: Remove width restriction on content width when nested inside of columns
  sass/blocks/_blocks.scss
  sass/style-editor-base.scss
Labels: Smaller PR, [Status] Approved

#317 Set a specific size for the featured image on single posts
  functions.php
  inc/template-tags.php
Labels: Smaller PR, [Status] Approved

#318 Improve styles for post thumbnail on single posts
  sass/site/primary/_posts-and-pages.scss
Labels: Smaller PR, [Status] Approved
