Repository Automattic/newspack-theme, pull requests merged in 2019-06, with the labels that each got.

#36 Add core functionality for the style packs
  classes/class-newspack-style-packs-core.php
  functions.php
  js/style-packs-customizer.js
Labels: [Status] Approved

#37 Fix full and wide aligned blocks on the static front page
  sass/blocks/_blocks.scss
  style-rtl.css
  style.css
Labels: [Status] Approved

#38 Add a sidebar to single posts
  functions.php
  inc/template-functions.php
  sass/blocks/_blocks.scss
  sass/layout/_layout.scss
  sass/site/primary/_posts-and-pages.scss
  sidebar.php
  single.php
  style-rtl.css
  style.css
  template-parts/content/content-excerpt.php
  template-parts/content/content-page.php
  template-parts/content/content-single.php
  template-parts/content/content.php
  template-parts/footer/footer-widgets.php
Labels: [Status] Approved

#41 Add bare-bones for first style pack option
  functions.php
  inc/style-packs.php
  package.json
  sass/styles/style-1/style-1.scss
  sass/styles/style-1/variables-style/_colors.scss
  sass/styles/style-1/variables-style/_fonts.scss
  sass/styles/style-1/variables-style/_variables-style.scss
  style-base.scss
  styles/style-1.css
Labels: [Status] Needs review

#44 Alternate: Fix widths in editor styles
  functions.php
  package.json
  style-editor-static-front-page.css
  style-editor-static-front-page.scss
  style-editor.css
  style-editor.scss
Labels: [Status] Approved

#39 Custom Fonts
  functions.php
  inc/customizer.php
  inc/typography.php
Labels: [Status] Needs review

#43 Generally scale down elements in the header
  functions.php
  sass/navigation/_menu-main-navigation.scss
  sass/navigation/_menu-social-navigation.scss
  sass/navigation/_menu-tertiary-navigation.scss
  sass/site/header/_site-header.scss
  sass/typography/_headings.scss
  style-rtl.css
  style.css
Labels: [Status] Approved

#51 Fix PHP Warning
  functions.php
Labels: [Status] Approved, [Type] Bug

#50 Add RTL styles for style packs
  package.json
  styles/style-1-rtl.css
Labels: [Status] Approved

#54 Allow Clearing Font Provider URL Fields
  inc/customizer.php
Labels: [Status] Approved

#62 Fix hide site title preview in Customizer
  sass/site/header/_site-header.scss
  style-rtl.css
  style.css
  styles/style-1-rtl.css
  styles/style-1.css
Labels: [Status] Needs review

#60 Remove Newspack-block specific styles from theme's default styles
  sass/blocks/_blocks.scss
  sass/typography/_headings.scss
  sass/typography/_typography.scss
  style-rtl.css
  style.css
  styles/style-1-rtl.css
  styles/style-1.css
Labels: [Status] Needs review
