Repository Automattic/newspack-theme, pull requests merged in 2019-05, with the labels that each got.

#19 Replace hue-based colour picker with hex-based colour picker
  functions.php
  inc/color-filters.php
  inc/color-patterns.php
  inc/customizer.php
  inc/template-functions.php
  js/customize-controls.js
  js/customize-preview.js
Labels: [Status] Approved

#21 Reorder existing header elements
  header.php
  sass/navigation/_menu-main-navigation.scss
  sass/navigation/_menu-top-navigation.scss
  sass/navigation/_navigation.scss
  sass/site/header/_site-header.scss
  style-rtl.css
  style.css
  template-parts/header/site-branding.php
Labels: [Status] Approved

#25 Add body class for the static front page
  inc/template-functions.php
  sass/site/primary/_posts-and-pages.scss
  style-rtl.css
  style.css
Labels: [Status] Approved

#26 Preliminary work to update the theme's width
  sass/blocks/_blocks.scss
  sass/layout/_layout.scss
  sass/navigation/_next-previous.scss
  sass/site/footer/_site-footer.scss
  sass/site/header/_site-header.scss
  sass/site/primary/_archives.scss
  sass/site/primary/_posts-and-pages.scss
  sass/variables-site/_structure.scss
  style-rtl.css
  style.css
  woocommerce-rtl.css
  woocommerce.css
Labels: [Status] Approved

#27 Remove author name, published date from entry footer
  inc/template-tags.php
Labels: [Status] Approved

#16 Fixing security issues with Node packages
  package-lock.json
  package.json
Labels: [Status] Approved

#23 Re-add an automatically generated variation of the primary colour
  functions.php
  inc/color-patterns.php
  inc/customizer.php
  inc/template-functions.php
  inc/woocommerce.php
  js/customize-controls.js
  js/customize-preview.js
  sass/blocks/_blocks.scss
  style-editor.css
  style-editor.scss
  style-rtl.css
  style.css
Labels: [Status] Approved, [Type] Core functionality

#28 Add 'secondary' menu space to the header
  functions.php
  header.php
  inc/template-functions.php
  js/touch-keyboard-navigation.js
  sass/navigation/_menu-main-navigation.scss
  sass/navigation/_menu-social-navigation.scss
  sass/navigation/_menu-top-navigation.scss
  sass/site/header/_site-header.scss
  style-rtl.css
  style.css
Labels: [Status] Needs review

#29 Add second custom color option
  functions.php
  inc/color-filters.php
  inc/color-patterns.php
  inc/customizer.php
  js/customize-controls.js
  js/customize-preview.js
  sass/blocks/_blocks.scss
  sass/elements/_elements.scss
  sass/forms/_fields.scss
  sass/media/_galleries.scss
  sass/mixins/_mixins-master.scss
  sass/navigation/_menu-main-navigation.scss
  sass/navigation/_next-previous.scss
  sass/site/footer/_site-footer.scss
  sass/site/primary/_comments.scss
  sass/site/primary/_posts-and-pages.scss
  sass/site/secondary/_widgets.scss
  sass/variables-site/_colors.scss
  style-editor.css
  style-editor.scss
  style-rtl.css
  style.css
Labels: [Status] Needs review

#31 Add tertiary menu space to the theme header
  functions.php
  header.php
  sass/navigation/_menu-tertiary-navigation.scss
  sass/navigation/_navigation.scss
  sass/site/header/_site-header.scss
  style-rtl.css
  style.css
Labels: [Status] Approved

#32 Remove styles associated with the already-removed featured image header
  print.css
  print.scss
  sass/site/_site.scss
  sass/site/header/_site-featured-image.scss
  sass/site/header/_site-header.scss
  style-rtl.css
  style.css
Labels: [Status] Approved

#33 Update the theme font faces and sizes
  sass/blocks/_blocks.scss
  sass/site/primary/_posts-and-pages.scss
  sass/variables-site/_fonts.scss
  style-editor.css
  style-rtl.css
  style.css
Labels: [Status] Approved

#34 Update how the primary content width is handled
  sass/blocks/_blocks.scss
  sass/layout/_layout.scss
  sass/navigation/_next-previous.scss
  sass/site/primary/_comments.scss
  sass/site/primary/_posts-and-pages.scss
  style-rtl.css
  style.css
Labels: [Status] Needs changes or feedback
