Repository Automattic/newspack-theme, pull requests merged in 2019-11, with the labels that each got.

#529 Offline template: Remove Newspack ads
  offline.php
Labels: Smaller PR, [Status] Approved

#533 Remove underline styles from links when inside of headings
  sass/site/primary/_posts-and-pages.scss
  sass/style-editor-base.scss
Labels: Smaller PR, [Status] Approved

#534 Remove 'clear both' from headings
  sass/elements/_elements.scss
Labels: Smaller PR, [Status] Approved

#535 Make sure author archive pages aren't spread out
  sass/site/primary/_archives.scss
Labels: Smaller PR, [Status] Approved

#541 Style 2: Update dropcap style
  inc/color-patterns.php
  sass/styles/style-2/style-2-editor.scss
  sass/styles/style-2/style-2.scss
Labels: [Status] Approved

#542 Remove left padding from first menu item in some cases
  sass/navigation/_menu-main-navigation.scss
  sass/navigation/_menu-secondary-navigation.scss
Labels: Smaller PR, [Status] Approved

#552 Style 3: Fix visited category link style in search
  inc/color-patterns.php
Labels: Smaller PR, [Status] Approved

#540 Add check for menus before outputting mobile menu toggle
  header.php
  inc/template-tags.php
Labels: [Status] Approved

#543 Make the content area narrower, more consistent in Style 2
  sass/styles/style-2/style-2.scss
Labels: [Status] Approved

#545 Style 2: Remove missed background colour from block category links.
  inc/color-patterns.php
  sass/styles/style-2/style-2-editor.scss
Labels: Smaller PR, [Status] Approved

#549 Add space between page title and featured image
  sass/site/primary/_posts-and-pages.scss
Labels: Smaller PR, [Status] Approved

#550 Fix 'wide' and 'full' width blocks on pages
  sass/blocks/_blocks.scss
Labels: Smaller PR, [Status] Approved

#551 Tighten up horizontal spacing in primary menu
  sass/navigation/_menu-main-navigation.scss
Labels: Smaller PR, [Status] Approved

#558 Add Small image option
  inc/template-functions.php
  js/src/extend-featured-image-editor.js
  single-feature.php
  single-wide.php
  single.php
Labels: [Status] Approved

#557 Add wp-components as dependency of extend-featured-image-editor.js
  functions.php
Labels: [Status] Approved

#555 Add a custom style to the Pop-up depending on Style Pack
  sass/styles/style-1/style-1.scss
  sass/styles/style-2/style-2.scss
  sass/styles/style-3/style-3.scss
  sass/styles/style-4/style-4.scss
  sass/styles/style-5/style-5.scss
Labels: [Status] Approved

#554 Make top and bottom spacing more consistent in columns, group blocks
  sass/blocks/_blocks.scss
Labels: Smaller PR, [Status] Approved

#559 Add support for Co-Authors Plus plugin
  archive.php
  inc/template-tags.php
  template-parts/post/author-bio.php
Labels: [Status] Approved

#563 Make the spacing between nested blocks more consistent with the ones that aren't
  sass/blocks/_blocks.scss
Labels: [Status] Approved

#564 Simplify main menu classes
  inc/color-patterns.php
  inc/template-tags.php
  inc/typography.php
  sass/navigation/_menu-main-navigation.scss
  sass/navigation/_menu-mobile-navigation.scss
  sass/print.scss
  sass/site/header/_site-header.scss
  sass/styles/style-2/style-2.scss
  sass/styles/style-3/style-3.scss
  sass/styles/style-4/style-4.scss
  sass/styles/style-5/style-5.scss
  sass/typography/_headings.scss
Labels: [Status] Approved

#565 Replace 'secondary-menu' class with the shorter 'nav2' class
  inc/color-patterns.php
  inc/template-tags.php
  inc/typography.php
  sass/navigation/_menu-secondary-navigation.scss
Labels: [Status] Approved

#566 Swap 'tertiary-menu' class with a shorter 'nav3' class
  inc/color-patterns.php
  inc/template-tags.php
  inc/typography.php
  sass/navigation/_menu-mobile-navigation.scss
  sass/navigation/_menu-tertiary-navigation.scss
  sass/styles/style-5/style-5.scss
  sass/styles/style-default/style-default.scss
  sass/typography/_headings.scss
Labels: [Status] Approved

#569 Fix issue with guest author image fallback
  archive.php
  inc/template-tags.php
  template-parts/post/author-bio.php
Labels: [Status] Approved

#570 Style 1: Fix Pullquote Block preview in editor
  inc/color-patterns.php
  inc/typography.php
  sass/styles/style-1/style-1-editor.scss
Labels: [Status] Approved

#573 Column block: Simplify selectors
  sass/blocks/_blocks.scss
  sass/styles/style-3/style-3.scss
  sass/styles/style-5/style-5.scss
Labels: [Status] Approved

#574 Article Block: Update default article block styles to use a simpler selector
  inc/color-patterns.php
  inc/typography.php
  sass/blocks/_blocks.scss
  sass/styles/style-1/style-1.scss
  sass/styles/style-2/style-2.scss
  sass/styles/style-3/style-3.scss
  sass/styles/style-4/style-4.scss
  sass/styles/style-5/style-5.scss
  sass/styles/style-default/style-default.scss
Labels: [Status] Approved

#579 Columns Block: Fix issue when nested in Group block
  sass/blocks/_blocks.scss
Labels: Smaller PR, [Status] Approved

#580 Article Block: Add full styles to make sure the block isn't cut off
  sass/blocks/_blocks.scss
Labels: [Status] Approved

#577 Styles 4, 5: Fix accent header border alignment in editor
  sass/styles/style-4/style-4-editor.scss
  sass/styles/style-5/style-5-editor.scss
Labels: Smaller PR, [Status] Needs changes or feedback

#585 Column block: Make sure it fills all available space
  sass/blocks/_blocks.scss
Labels: Smaller PR, [Status] Approved

#584 Replace header solid background and header default backgrounds with simpler classes
  inc/color-patterns.php
  inc/template-functions.php
  sass/navigation/_menu-tertiary-navigation.scss
  sass/site/header/_site-header.scss
  sass/site/primary/_posts-and-pages.scss
  sass/styles/style-2/style-2.scss
  sass/styles/style-3/style-3.scss
  sass/styles/style-4/style-4.scss
  sass/styles/style-5/style-5.scss
  sass/styles/style-default/style-default.scss
Labels: [Status] Approved

#586 Style 2: Make sure highlight menu contrasts against default solid header colour
  sass/styles/style-2/style-2.scss
Labels: Smaller PR, [Status] Approved

#595 Update screenshot so logo uses the correct primary colour
  screenshot.png
Labels: [Status] Approved

#593 Style 4: Fix custom typography issues
  inc/typography.php
Labels: Smaller PR, [Status] Approved

#588 Jetpack Subscription: Make sure messages are visible against dark backgrounds
  sass/site/secondary/_widgets.scss
Labels: [Status] Approved

#590 Style 4: Hide author avatar when featured image is behind title
  sass/styles/style-4/style-4.scss
Labels: Smaller PR, [Status] Approved

#589 Simplifies CSS selectors for the center align header options
  inc/template-functions.php
  sass/navigation/_menu-highlight-navigation.scss
  sass/navigation/_menu-main-navigation.scss
  sass/site/header/_site-header.scss
Labels: [Status] Approved

#592 Use get_the_excerpt to get image caption/excerpt
  inc/template-tags.php
Labels: Smaller PR, [Status] Approved

#596 Author Widget: Clean up styles
  sass/site/secondary/_widgets.scss
Labels: Smaller PR, [Status] Approved

#587 Update 'simplified' and 'default height' classes
  inc/color-patterns.php
  inc/template-functions.php
  sass/navigation/_menu-main-navigation.scss
  sass/navigation/_menu-mobile-navigation.scss
  sass/navigation/_menu-tertiary-navigation.scss
  sass/site/header/_site-header.scss
  sass/site/primary/_posts-and-pages.scss
  sass/styles/style-2/style-2.scss
  sass/styles/style-3/style-3.scss
  sass/styles/style-4/style-4.scss
  sass/styles/style-default/style-default.scss
Labels: [Status] Approved, [Status] Needs Discussion
