Repository Automattic/newspack-theme, pull requests merged in 2019-07, with the labels that each got.

#18 Feature/amp native
  functions.php
Labels: [Status] Needs changes or feedback, [Type] Core functionality

#64 Standardizing font sizing and styles
  sass/blocks/_blocks.scss
  sass/navigation/_menu-tertiary-navigation.scss
  sass/navigation/_menu-top-navigation.scss
  sass/site/header/_site-header.scss
  sass/site/primary/_comments.scss
  sass/site/primary/_posts-and-pages.scss
  sass/site/secondary/_widgets.scss
  sass/typography/_headings.scss
  sass/typography/_typography.scss
  sass/variables-site/_fonts.scss
  style-editor-base.scss
  style-editor.css
  style-rtl.css
  style.css
  styles/style-1-editor.css
  styles/style-1-rtl.css
  styles/style-1.css
Labels: [Status] Approved

#65 Add 'Feature' template for articles
  sass/site/primary/_posts-and-pages.scss
  single-feature.php
  style-rtl.css
  style.css
  styles/style-1-rtl.css
  styles/style-1.css
Labels: [Status] Approved

#66 Add sidebar, fix alignment on blog posts page
  index.php
  template-parts/content/content.php
Labels: [Status] Approved

#67 Update default accent colour to be Newspack blue
  inc/color-filters.php
  sass/plugins/woocommerce.scss
  sass/variables-site/_colors.scss
  style-editor.css
  style-rtl.css
  style.css
  styles/style-1-editor.css
  styles/style-1-rtl.css
  styles/style-1.css
  woocommerce-rtl.css
  woocommerce.css
Labels: [Status] Approved

#74 Remove compiled CSS files
  .gitignore
  functions.php
  inc/woocommerce.php
  package.json
  print.css
  sass/print.scss
  sass/style-base.scss
  sass/style-editor-base.scss
  sass/style-editor-customizer.scss
  sass/style-editor-static-front-page.scss
  sass/style-editor.scss
  sass/style.scss
  sass/styles/style-1/style-1-editor.scss
  sass/styles/style-1/style-1.scss
  style-base.scss
  style-editor-customizer.scss
  style-editor-static-front-page.css
  style-editor.css
  style-rtl.css
  style.css
  styles/style-1-editor.css
  styles/style-1-rtl.css
  styles/style-1.css
  woocommerce-rtl.css
  woocommerce.css
Labels: [Status] Approved

#71 Add sidebar to page template
  page.php
  sass/layout/_layout.scss
  sass/site/primary/_posts-and-pages.scss
Labels: [Status] Approved, [Status] Needs changes or feedback

#76 Reorder single post and update styles
  inc/jetpack.php
  inc/template-functions.php
  inc/template-tags.php
  sass/blocks/_blocks.scss
  sass/navigation/_next-previous.scss
  sass/site/primary/_comments.scss
  sass/site/primary/_posts-and-pages.scss
  sass/typography/_headings.scss
  single.php
  template-parts/header/entry-header.php
Labels: [Status] Approved

#68 Add styles for single article author bio.
  sass/site/primary/_posts-and-pages.scss
  sass/typography/_headings.scss
  template-parts/post/author-bio.php
Labels: [Status] Approved

#97 Update header styles
  header.php
  sass/layout/_layout.scss
  sass/navigation/_menu-main-navigation.scss
  sass/navigation/_menu-secondary-navigation.scss
  sass/navigation/_menu-social-navigation.scss
  sass/navigation/_menu-tertiary-navigation.scss
  sass/navigation/_menu-top-navigation.scss
  sass/navigation/_navigation.scss
  sass/site/header/_site-header.scss
  sass/typography/_headings.scss
  template-parts/header/site-branding.php
Labels: [Status] Approved

#100 Add separate front-page.php template to theme
  front-page.php
  functions.php
Labels: [Status] Approved

#101 Removes priority menu functionality
  functions.php
  js/priority-menu.js
  sass/navigation/_menu-main-navigation.scss
Labels: [Status] Approved

#103 Update sidebar widget styles
  functions.php
  sass/layout/_layout.scss
  sass/site/primary/_posts-and-pages.scss
  sass/site/secondary/_widgets.scss
Labels: [Status] Approved

#107 Adds fallback location for featured image when less than 1200 wide.
  inc/template-functions.php
  sass/site/primary/_posts-and-pages.scss
  single-feature.php
  single.php
Labels: [Status] Approved

#109 Add options to customize the header (solid background and centred logo)
  header.php
  inc/color-patterns.php
  inc/customizer.php
  inc/template-functions.php
  sass/navigation/_menu-main-navigation.scss
  sass/navigation/_menu-social-navigation.scss
  sass/navigation/_menu-tertiary-navigation.scss
  sass/site/header/_site-header.scss
Labels: [Status] Approved

#110 Updates search form styles
  classes/class-newspack-svg-icons.php
  functions.php
  sass/forms/_forms.scss
  sass/forms/_search.scss
  sass/site/primary/_archives.scss
  sass/site/secondary/_widgets.scss
  searchform.php
Labels: [Status] Approved

#122 #106 fixes the npm run build initial errors
  package.json
Labels: [Status] Approved

#124 Style Newspack homepage block headers in theme
  inc/color-patterns.php
  sass/style-editor-base.scss
  sass/typography/_headings.scss
Labels: [Status] Approved

#115 Make sure sidebar fills up all the available space on mobile
  sass/layout/_layout.scss
Labels: [Status] Approved

#118 Removes more unneeded priority menu code
  inc/template-functions.php
Labels: [Status] Approved

#117 Add option to hide tagline
  inc/customizer.php
  inc/template-functions.php
  js/customize-preview.js
  sass/site/header/_site-header.scss
Labels: [Status] Needs changes or feedback

#108 Build out theme footer styles
  footer.php
  functions.php
  header.php
  sass/site/footer/_site-footer.scss
  sass/site/header/_site-header.scss
  sass/site/secondary/_widgets.scss
  template-parts/footer/footer-branding.php
  template-parts/footer/footer-widgets.php
Labels: [Status] Approved

#116 Adds search toggle and search box to header
  classes/class-newspack-svg-icons.php
  functions.php
  header.php
  js/amp-fallback.js
  sass/layout/_layout.scss
  sass/site/header/_site-header.scss
  template-parts/header/header-search.php
Labels: [Status] Approved

#123 Clean up search result styles
  inc/color-patterns.php
  sass/layout/_layout.scss
  sass/navigation/_next-previous.scss
  sass/site/primary/_archives.scss
  sass/site/primary/_posts-and-pages.scss
  sass/typography/_headings.scss
  search.php
  template-parts/content/content-excerpt.php
Labels: [Status] Approved

#126 Fixes sidebar spacing
  sass/layout/_layout.scss
Labels: [Status] Approved

#127 Fix up entry-footer/tag styles on single posts
  sass/site/primary/_posts-and-pages.scss
  sass/typography/_headings.scss
Labels: [Status] Approved

#128 Correct 'accent header' sizing
  sass/site/primary/_posts-and-pages.scss
  sass/site/secondary/_widgets.scss
Labels: [Status] Approved

#130 Adds pullquote block styles
  sass/blocks/_blocks.scss
Labels: [Status] Approved

#141 Removes footer navigation CSS
  sass/navigation/_menu-footer-navigation.scss
  sass/navigation/_navigation.scss
Labels: Smaller PR, [Status] Approved

#140 Remove previous/next navigation and associated styles
  inc/color-patterns.php
  inc/typography.php
  sass/navigation/_next-previous.scss
  sass/print.scss
  sass/typography/_headings.scss
  single-feature.php
  single.php
Labels: Smaller PR, [Status] Approved

#132 Update dropcap styles
  sass/blocks/_blocks.scss
  sass/style-editor-base.scss
Labels: Smaller PR, [Status] Approved

#134 Fix up a couple visual issues with Infinite Scroll
  inc/jetpack.php
  sass/navigation/_infinite-scroll.scss
Labels: Smaller PR, [Status] Approved

#136 Fix search sidebar styles
  sass/layout/_layout.scss
Labels: Smaller PR, [Status] Approved

#138 Fix up blog posts page styles
  inc/jetpack.php
  inc/template-tags.php
  index.php
  sass/blocks/_blocks.scss
  sass/site/primary/_archives.scss
  sass/typography/_headings.scss
Labels: Smaller PR, [Status] Approved

#135 Update Infinite Scroll to use load on scroll when available
  inc/jetpack.php
Labels: Smaller PR, [Status] Approved

#105 Upgrade to v2.0.0 of the VIP Coding Standards
  composer.json
  composer.lock
Labels: [Status] Needs changes or feedback

#137 Fix up the spacing between the header and content
  sass/layout/_layout.scss
  sass/site/primary/_archives.scss
  sass/site/primary/_posts-and-pages.scss
Labels: [Status] Approved

#133 Updates post title style in editor to match the front-end
  functions.php
  package.json
  sass/style-editor-base.scss
  sass/style-editor-overrides.scss
Labels: [Status] Approved

#144 Remove `!important` from the print styles
  sass/print.scss
Labels: Smaller PR, [Status] Approved
