Repository Automattic/newspack-theme, pull requests merged in 2020-05, with the labels that each got.

#910 Bump woocommerce thank you page version
  newspack-theme/woocommerce/checkout/thankyou.php
Labels: Smaller PR, [Status] Approved

#909 Allow html in title when filtering in WooCommerce code
  newspack-theme/inc/woocommerce.php
Labels: Smaller PR, [Status] Approved

#911 Button Block: Make sure editor colours are correct
  newspack-theme/inc/color-patterns.php
  newspack-theme/sass/blocks/_blocks.scss
  newspack-theme/sass/style-editor-base.scss
Labels: [Status] Approved

#919 Homepage Posts: Move content option fixes to block
  newspack-theme/sass/blocks/_blocks.scss
Labels: Smaller PR, [Status] Approved

#918 Release May 6, 2020
  newspack-theme/inc/color-patterns.php
  newspack-theme/inc/woocommerce.php
  newspack-theme/sass/blocks/_blocks.scss
  newspack-theme/sass/style-editor-base.scss
  newspack-theme/woocommerce/checkout/thankyou.php
Labels: [Status] Approved

#924 Improved styling for shop and products
  newspack-theme/sass/plugins/woocommerce.scss
Labels: [Status] Approved

#901 Header: Add simplied header option for subpages
  newspack-katharine/inc/child-color-patterns.php
  newspack-nelson/sass/style.scss
  newspack-sacha/sass/style.scss
  newspack-theme/header.php
  newspack-theme/inc/color-patterns.php
  newspack-theme/inc/customizer.php
  newspack-theme/inc/template-functions.php
  newspack-theme/js/src/amp-fallback.js
  newspack-theme/js/src/customize-controls.js
  newspack-theme/sass/navigation/_menu-mobile-navigation.scss
  newspack-theme/sass/site/header/_site-header.scss
  newspack-theme/sass/site/primary/_posts-and-pages.scss
  newspack-theme/template-parts/header/site-branding.php
  newspack-theme/template-parts/header/subpage-sidebar.php
Labels: Needs documentation, [Status] Approved

#925 Footer: Add option to customize copyright text
  newspack-theme/footer.php
  newspack-theme/inc/customizer.php
Labels: [Status] Approved

#914 Default Template: Make sure full width blocks preview centered in editor
  newspack-theme/sass/style-editor-overrides.scss
Labels: Smaller PR, [Status] Approved

#915 Cover Block: Make sure the gradient overlay isn't cut off on wide and full blocks
  newspack-theme/sass/blocks/_blocks.scss
Labels: Smaller PR, [Status] Approved

#928 Header: correct alignment issue with simplified header and centered logo
  newspack-theme/sass/site/header/_site-header.scss
Labels: [Status] Approved

#916 Group Block: Make sure preview width is correct
  newspack-theme/sass/style-editor-base.scss
  newspack-theme/sass/style-editor-overrides.scss
Labels: [Status] Approved

#927 Release May 11, 2020
  newspack-katharine/inc/child-color-patterns.php
  newspack-nelson/sass/style.scss
  newspack-sacha/sass/style.scss
  newspack-theme/footer.php
  newspack-theme/header.php
  newspack-theme/inc/color-patterns.php
  newspack-theme/inc/customizer.php
  newspack-theme/inc/template-functions.php
  newspack-theme/js/src/amp-fallback.js
  newspack-theme/js/src/customize-controls.js
  newspack-theme/sass/blocks/_blocks.scss
  newspack-theme/sass/navigation/_menu-mobile-navigation.scss
  newspack-theme/sass/plugins/woocommerce.scss
  newspack-theme/sass/site/header/_site-header.scss
  newspack-theme/sass/site/primary/_posts-and-pages.scss
  newspack-theme/sass/style-editor-base.scss
  newspack-theme/sass/style-editor-overrides.scss
  newspack-theme/template-parts/header/site-branding.php
  newspack-theme/template-parts/header/subpage-sidebar.php
Labels: [Status] Needs Review

#917 Group Block: adjust border styles
  newspack-joseph/sass/style-editor.scss
  newspack-joseph/sass/style.scss
  newspack-katharine/sass/style-editor.scss
  newspack-katharine/sass/style.scss
  newspack-nelson/sass/style-editor.scss
  newspack-nelson/sass/style.scss
Labels: [Status] Approved

#920 Article Carousel block: improve contrast, category appearance
  newspack-katharine/sass/style.scss
  newspack-nelson/sass/style-editor.scss
  newspack-sacha/sass/style.scss
  newspack-scott/sass/style-editor.scss
  newspack-scott/sass/style.scss
  newspack-theme/sass/blocks/_blocks.scss
  newspack-theme/sass/styles/style-default/style-default.scss
Labels: [Status] Approved

#929 Featured Images: Make sure special featured image styles show credits
  newspack-theme/template-parts/post/large-featured-image.php
Labels: Smaller PR, [Status] Approved

#930 Header: Correct centered logo sizing
  newspack-theme/sass/site/header/_site-header.scss
Labels: [Status] Approved

#933 Header: Fix JS error in simplified subpage header non-AMP fallback
  newspack-theme/js/src/amp-fallback.js
Labels: Smaller PR, [Status] Approved

#935 Header: correct logo size display issues with AMP
  newspack-theme/inc/logo-resizer.php
  newspack-theme/sass/site/header/_site-header.scss
Labels: [Status] Approved

#937 Header: improve subpage header code to remove AMP errors
  newspack-theme/inc/template-tags.php
Labels: [Status] Approved

#936 Add GH action to manage labels
  .github/workflows/main.yml
Labels: [Status] Approved

#932 Header: Keep centred logo from getting cut off in IE11
  newspack-theme/sass/site/header/_site-header.scss
Labels: Smaller PR, [Status] Approved

#940 Block Editor: Add a line height to the post title
  newspack-theme/sass/style-editor-base.scss
Labels: Smaller PR, [Status] Approved

#952 Newspack Sacha: Correct post title alignment preview in editor
  newspack-sacha/functions.php
  newspack-sacha/sass/child-style-editor-overrides.scss
  scripts/compile-scss.js
Labels: [Status] Approved

#938 Header: Add `object-fit` for logos when AMP isn't active
  newspack-theme/sass/site/header/_site-header.scss
Labels: Smaller PR, [Status] Approved

#939 Archives: add extra HTML to the_archive_title for easier styling
  newspack-theme/functions.php
Labels: [Status] Approved

#954 Add author email to archive page; improve apperance
  newspack-sacha/sass/style.scss
  newspack-sacha/template-parts/post/author-bio.php
  newspack-theme/archive.php
  newspack-theme/classes/class-newspack-svg-icons.php
  newspack-theme/inc/customizer.php
  newspack-theme/inc/template-functions.php
  newspack-theme/inc/typography.php
  newspack-theme/sass/site/primary/_posts-and-pages.scss
  newspack-theme/sass/typography/_headings.scss
  newspack-theme/template-parts/post/author-bio.php
Labels: [Status] Approved
