Repository Automattic/newspack-theme, pull requests merged in 2020-04, with the labels that each got.

#853 Fix release files: CSS changed by release process
  newspack-joseph/sass/style.scss
Labels: Next release, [Status] Approved

#860 Release 3/31/2020
  newspack-joseph/inc/child-color-patterns.php
  newspack-joseph/sass/style.scss
  newspack-katharine/inc/child-color-patterns.php
  newspack-katharine/sass/style-editor.scss
  newspack-katharine/sass/style.scss
  newspack-nelson/inc/child-color-patterns.php
  newspack-nelson/sass/style.scss
  newspack-sacha/inc/child-color-patterns.php
  newspack-sacha/sass/style.scss
  newspack-scott/inc/child-color-patterns.php
  newspack-scott/sass/style.scss
  newspack-theme/classes/class-newspack-svg-icons.php
  newspack-theme/comments.php
  newspack-theme/functions.php
  newspack-theme/header.php
  newspack-theme/inc/color-patterns.php
  newspack-theme/inc/customizer.php
  newspack-theme/inc/typography.php
  newspack-theme/js/src/amp-fallback.js
  newspack-theme/js/src/customize-controls.js
  newspack-theme/sass/blocks/_blocks.scss
  newspack-theme/sass/navigation/_menu-mobile-navigation.scss
  newspack-theme/sass/navigation/_next-previous.scss
  newspack-theme/sass/site/header/_site-header.scss
  newspack-theme/sass/site/primary/_comments.scss
  newspack-theme/sass/site/primary/_posts-and-pages.scss
  newspack-theme/sass/site/secondary/_widgets.scss
  newspack-theme/sass/style-editor-base.scss
  newspack-theme/sass/typography/_headings.scss
  newspack-theme/template-parts/header/desktop-sidebar.php
  newspack-theme/template-parts/header/mobile-sidebar.php
  package-lock.json
  package.json
  release.config.js
Labels: [Status] Approved

#855 Add support for Yoast Breadcrumbs
  newspack-joseph/sass/style.scss
  newspack-katharine/inc/child-color-patterns.php
  newspack-katharine/sass/style.scss
  newspack-nelson/inc/child-color-patterns.php
  newspack-nelson/sass/style.scss
  newspack-sacha/sass/style.scss
  newspack-scott/inc/child-color-patterns.php
  newspack-scott/sass/style.scss
  newspack-theme/header.php
  newspack-theme/inc/template-functions.php
  newspack-theme/inc/typography.php
  newspack-theme/js/src/amp-fallback.js
  newspack-theme/sass/plugins/yoast-breadcrumb.scss
  newspack-theme/sass/style-base.scss
Labels: Needs documentation, [Status] Approved

#862 Author Bio: Add ability to turn off truncate and allow HTML
  newspack-sacha/sass/style.scss
  newspack-sacha/template-parts/post/author-bio.php
  newspack-theme/archive.php
  newspack-theme/inc/customizer.php
  newspack-theme/js/src/customize-controls.js
  newspack-theme/sass/site/primary/_archives.scss
  newspack-theme/sass/site/primary/_posts-and-pages.scss
  newspack-theme/template-parts/post/author-bio.php
Labels: [Status] Approved

#868 Checkout Page: Make some fields more compact
  newspack-theme/inc/woocommerce.php
  newspack-theme/sass/plugins/woocommerce.scss
Labels: [Status] Needs Review

#872 Paragraph block: Correct dropcap preview in editor
  newspack-joseph/inc/child-typography.php
  newspack-joseph/sass/style-editor.scss
  newspack-katharine/inc/child-typography.php
  newspack-katharine/sass/style-editor.scss
  newspack-nelson/inc/child-color-patterns.php
  newspack-nelson/inc/child-typography.php
  newspack-nelson/sass/style-editor.scss
  newspack-sacha/inc/child-color-patterns.php
  newspack-sacha/inc/child-typography.php
  newspack-sacha/sass/style-editor.scss
  newspack-scott/inc/child-typography.php
  newspack-scott/sass/style-editor.scss
  newspack-theme/sass/style-editor-base.scss
Labels: [Status] Approved

#875 Improve icon used to indicate comments by the post author
  newspack-theme/classes/class-newspack-svg-icons.php
  newspack-theme/classes/class-newspack-walker-comment.php
  newspack-theme/inc/icon-functions.php
Labels: [Status] Approved

#876 Pullquote Block: Correct width in editor
  newspack-theme/sass/style-editor-base.scss
Labels: [Status] Approved

#878 Latest Posts Block: Correct custom fonts
  newspack-theme/inc/typography.php
  newspack-theme/sass/blocks/_blocks.scss
  newspack-theme/sass/style-editor-base.scss
Labels: [Status] Approved

#879 Add Featured Images to RSS output
  newspack-theme/functions.php
Labels: [Status] Approved

#873 One Column template: Make max width a px value, not %
  newspack-theme/sass/layout/_layout.scss
Labels: [Status] Approved

#867 Checkout: Option to hide order details table
  newspack-theme/functions.php
  newspack-theme/inc/customizer.php
  newspack-theme/js/src/amp-fallback.js
  newspack-theme/sass/plugins/woocommerce.scss
  newspack-theme/woocommerce/checkout/form-checkout.php
Labels: [Status] Approved

#865 Release 4/7/2020
  newspack-joseph/inc/child-typography.php
  newspack-joseph/sass/style-editor.scss
  newspack-joseph/sass/style.scss
  newspack-katharine/inc/child-color-patterns.php
  newspack-katharine/inc/child-typography.php
  newspack-katharine/sass/style-editor.scss
  newspack-katharine/sass/style.scss
  newspack-nelson/inc/child-color-patterns.php
  newspack-nelson/inc/child-typography.php
  newspack-nelson/sass/style-editor.scss
  newspack-nelson/sass/style.scss
  newspack-sacha/inc/child-color-patterns.php
  newspack-sacha/inc/child-typography.php
  newspack-sacha/sass/style-editor.scss
  newspack-sacha/sass/style.scss
  newspack-sacha/template-parts/post/author-bio.php
  newspack-scott/inc/child-color-patterns.php
  newspack-scott/inc/child-typography.php
  newspack-scott/sass/style-editor.scss
  newspack-scott/sass/style.scss
  newspack-theme/archive.php
  newspack-theme/classes/class-newspack-svg-icons.php
  newspack-theme/classes/class-newspack-walker-comment.php
  newspack-theme/functions.php
  newspack-theme/header.php
  newspack-theme/inc/customizer.php
  newspack-theme/inc/icon-functions.php
  newspack-theme/inc/template-functions.php
  newspack-theme/inc/typography.php
  newspack-theme/inc/woocommerce.php
  newspack-theme/js/src/amp-fallback.js
  newspack-theme/js/src/customize-controls.js
  newspack-theme/sass/blocks/_blocks.scss
  newspack-theme/sass/layout/_layout.scss
  newspack-theme/sass/plugins/woocommerce.scss
  newspack-theme/sass/plugins/yoast-breadcrumb.scss
  newspack-theme/sass/site/primary/_archives.scss
  newspack-theme/sass/site/primary/_posts-and-pages.scss
  newspack-theme/sass/style-base.scss
  newspack-theme/sass/style-editor-base.scss
  newspack-theme/template-parts/post/author-bio.php
  newspack-theme/woocommerce/checkout/form-checkout.php
Labels: [Status] Approved

#765 Linting: use lint-staged for JS pre-commit linting
  composer.json
  package.json
Labels: [Status] Approved

#891 Fix change release zips' labels to zip
  release.config.js
Labels: [Status] Approved

#888 Fix make subtitle appear in Gutenberg >v7.8.1
  newspack-theme/js/src/post-subtitle/utils.js
  newspack-theme/sass/style-editor-base.scss
Labels: [Status] Approved

#890 Feat: Add options to WooCommerce thank you page
  newspack-theme/inc/customizer.php
  newspack-theme/inc/woocommerce.php
  newspack-theme/sass/plugins/woocommerce.scss
  newspack-theme/woocommerce/checkout/thankyou.php
  newspack-theme/woocommerce/order/order-details-customer.php
Labels: [Status] Approved, [Status] Needs Changes or Feeback

#895 Add hook above comments render
  newspack-theme/comments.php
Labels: [Status] Approved

#896 Release 4/23/2020
  composer.json
  newspack-theme/comments.php
  newspack-theme/inc/customizer.php
  newspack-theme/inc/woocommerce.php
  newspack-theme/js/src/post-subtitle/utils.js
  newspack-theme/sass/plugins/woocommerce.scss
  newspack-theme/sass/style-editor-base.scss
  newspack-theme/woocommerce/checkout/thankyou.php
  newspack-theme/woocommerce/order/order-details-customer.php
  package.json
  release.config.js
Labels: [Status] Approved

#882 Featured Image: improve appearance of caption with beside featured image setting
  newspack-theme/sass/site/primary/_posts-and-pages.scss
  newspack-theme/template-parts/post/large-featured-image.php
Labels: [Status] Approved

#897 Update classes for custom typography
  newspack-theme/inc/typography.php
Labels: Gutenberg 7.9, [Status] Approved

#898 Add color classes to the editor styles
  newspack-theme/inc/color-patterns.php
  newspack-theme/sass/style-editor-base.scss
Labels: Gutenberg 7.9, [Status] Approved

#899 Update button styles to work with new markup
  newspack-joseph/inc/child-typography.php
  newspack-theme/inc/color-patterns.php
  newspack-theme/inc/typography.php
  newspack-theme/sass/blocks/_blocks.scss
  newspack-theme/sass/style-editor-base.scss
Labels: Gutenberg 7.9, [Status] Approved

#903 fix: make sure first floated element has top margin
  newspack-theme/sass/blocks/_blocks.scss
Labels: Smaller PR, [Status] Approved

#902 Featured image beside: add top and bottom padding to title
  newspack-theme/sass/site/primary/_posts-and-pages.scss
Labels: Smaller PR, [Status] Approved

#887 Make sure amp styles work with logo centering
  newspack-theme/sass/site/header/_site-header.scss
Labels: [Status] Approved

#884 Centred Logo: Primary menu is slightly off
  newspack-theme/sass/navigation/_menu-main-navigation.scss
Labels: Smaller PR, [Status] Approved

#907 Button Block: Add temporary fix for doubled-button outline
  newspack-theme/sass/blocks/_blocks.scss
Labels: Gutenberg 7.9, Smaller PR, [Status] Approved

#904 Content Options: Make sure styles are enqueued, correct
  newspack-joseph/functions.php
  newspack-katharine/functions.php
  newspack-nelson/functions.php
  newspack-sacha/functions.php
  newspack-scott/functions.php
  newspack-theme/inc/jetpack.php
  newspack-theme/sass/blocks/_blocks.scss
Labels: [Status] Approved

#908 Release 04/29/2020
  newspack-joseph/functions.php
  newspack-joseph/inc/child-typography.php
  newspack-katharine/functions.php
  newspack-nelson/functions.php
  newspack-sacha/functions.php
  newspack-scott/functions.php
  newspack-theme/inc/color-patterns.php
  newspack-theme/inc/jetpack.php
  newspack-theme/inc/typography.php
  newspack-theme/sass/blocks/_blocks.scss
  newspack-theme/sass/navigation/_menu-main-navigation.scss
  newspack-theme/sass/site/header/_site-header.scss
  newspack-theme/sass/site/primary/_posts-and-pages.scss
  newspack-theme/sass/style-editor-base.scss
  newspack-theme/template-parts/post/large-featured-image.php
Labels: [Status] Approved
