Repository Automattic/newspack-theme, pull requests merged in 2020-03, with the labels that each got.

#812 Release: first production release
  .circleci/config.yml
  commitlint.config.js
  composer.json
  newspack-joseph/sass/style.scss
  newspack-katharine/sass/style.scss
  newspack-nelson/sass/style.scss
  newspack-sacha/sass/style.scss
  newspack-scott/sass/style.scss
  newspack-theme/sass/style.scss
  package-lock.json
  package.json
  release.config.js
Labels: [Status] Approved

#811 Add custom style for the Mailchimp block
  newspack-theme/sass/blocks/_blocks.scss
  newspack-theme/sass/style-editor-base.scss
Labels: [Status] Approved

#825 1.0.1 Release
  newspack-theme/sass/blocks/_blocks.scss
  newspack-theme/sass/style-editor-base.scss
  package-lock.json
Labels: [Status] Approved

#817 Social Menu: Add Podigee icon
  newspack-theme/classes/class-newspack-svg-icons.php
Labels: Needs documentation, [Status] Approved

#814 fix: apply custom header color background to Newspack Nelson's footer
  newspack-nelson/inc/child-color-patterns.php
  newspack-theme/inc/color-patterns.php
Labels: [Status] Approved

#818 Pages: fix issue with featured images not displaying for one col templates
  newspack-theme/sass/site/primary/_posts-and-pages.scss
  newspack-theme/single-feature.php
  newspack-theme/single-wide.php
Labels: [Status] Approved

#758 Fix pre-commit hook
  composer.json
  composer.lock
Labels: [Status] Approved

#813 CI: fix release assets paths
  release.config.js
Labels: [Status] Approved

#831 Correct issues in where custom typography is applied
  newspack-theme/inc/typography.php
Labels: [Status] Approved

#832 Release 3/17/20
  composer.json
  composer.lock
  newspack-nelson/inc/child-color-patterns.php
  newspack-theme/classes/class-newspack-svg-icons.php
  newspack-theme/inc/color-patterns.php
  newspack-theme/inc/typography.php
  newspack-theme/sass/site/primary/_posts-and-pages.scss
  newspack-theme/single-feature.php
  newspack-theme/single-wide.php
  release.config.js
Labels: [Status] Approved

#827 fix: set max width for nested full and wide blocks
  newspack-theme/sass/blocks/_blocks.scss
Labels: [Status] Approved

#824 Correct position of comment icon indicating current author
  newspack-theme/classes/class-newspack-walker-comment.php
  newspack-theme/inc/color-patterns.php
  newspack-theme/sass/site/primary/_comments.scss
Labels: [Status] Approved

#837 Change way featured images are added to fix missing titles
  newspack-theme/single-feature.php
  newspack-theme/single-wide.php
Labels: [Status] Approved

#835 CI: remove redundant build step
  package.json
Labels: Smaller PR, [Status] Approved

#834 Remove style overrides from h2 in cover blocks
  newspack-theme/sass/blocks/_blocks.scss
Labels: Smaller PR, [Status] Approved

#833 Prevent id selector format error in pre-commit checks
  newspack-theme/sass/blocks/_blocks.scss
Labels: Smaller PR, [Status] Approved

#829 Homepage Posts: Remove top margin on accent-header with AMP
  newspack-theme/sass/blocks/_blocks.scss
Labels: Smaller PR, [Status] Approved

#828 Set size for above copyright widget titles
  newspack-theme/sass/site/footer/_site-footer.scss
Labels: Smaller PR, [Status] Approved

#839 Filters for Super Cool Ad Inserter Ads
  newspack-theme/functions.php
Labels: [Status] Approved

#842 Release 3/24/2020
  newspack-theme/classes/class-newspack-walker-comment.php
  newspack-theme/functions.php
  newspack-theme/inc/color-patterns.php
  newspack-theme/sass/blocks/_blocks.scss
  newspack-theme/sass/site/footer/_site-footer.scss
  newspack-theme/sass/site/primary/_comments.scss
  newspack-theme/single-feature.php
  newspack-theme/single-wide.php
  package-lock.json
  package.json
Labels: [Status] Approved

#846 Make sure social links block doesn't inherit link color
  newspack-theme/sass/blocks/_blocks.scss
Labels: Smaller PR, [Status] Approved

#851 Only apply RSS icon to /feed
  newspack-theme/classes/class-newspack-svg-icons.php
Labels: Smaller PR, [Status] Approved

#849 Add telephone icon to social menu
  newspack-theme/classes/class-newspack-svg-icons.php
Labels: Smaller PR, [Status] Approved

#761 Fix: Make Related Posts styles more consistent between formats
  newspack-katharine/sass/style-editor.scss
  newspack-katharine/sass/style.scss
  newspack-theme/inc/typography.php
  newspack-theme/sass/blocks/_blocks.scss
  newspack-theme/sass/site/primary/_posts-and-pages.scss
  newspack-theme/sass/style-editor-base.scss
Labels: [Status] Approved

#816 Add desktop slideout menu
  newspack-theme/functions.php
  newspack-theme/header.php
  newspack-theme/inc/color-patterns.php
  newspack-theme/inc/customizer.php
  newspack-theme/js/src/amp-fallback.js
  newspack-theme/js/src/customize-controls.js
  newspack-theme/sass/navigation/_menu-mobile-navigation.scss
  newspack-theme/sass/site/header/_site-header.scss
  newspack-theme/sass/site/secondary/_widgets.scss
  newspack-theme/template-parts/header/desktop-sidebar.php
  newspack-theme/template-parts/header/mobile-sidebar.php
Labels: Needs documentation, [Status] Approved

#859 Secondary Menu: Correct menu name when checking for it in header
  newspack-theme/header.php
Labels: [Status] Approved

#820 Adds option to collapse comments
  newspack-theme/comments.php
  newspack-theme/functions.php
  newspack-theme/inc/color-patterns.php
  newspack-theme/inc/customizer.php
  newspack-theme/js/src/amp-fallback.js
  newspack-theme/sass/navigation/_next-previous.scss
  newspack-theme/sass/site/primary/_comments.scss
  newspack-theme/sass/typography/_headings.scss
Labels: Needs documentation, [Status] Approved

#857 Fix editor color palettes and secondary color by adding full, 6-digits, hex codes
  newspack-joseph/inc/child-color-patterns.php
  newspack-katharine/inc/child-color-patterns.php
  newspack-nelson/inc/child-color-patterns.php
  newspack-sacha/inc/child-color-patterns.php
  newspack-scott/inc/child-color-patterns.php
  newspack-theme/functions.php
  newspack-theme/inc/color-patterns.php
  newspack-theme/inc/customizer.php
Labels: [Status] Approved

#858 Remove popup styles
  newspack-joseph/sass/style.scss
  newspack-katharine/sass/style.scss
  newspack-nelson/sass/style.scss
  newspack-sacha/sass/style.scss
  newspack-scott/sass/style.scss
Labels: [Status] Approved

#852 Releases: fix setting version in release files
  package-lock.json
  package.json
  release.config.js
Labels: Next release, [Status] Approved
