Repository Automattic/newspack-theme, pull requests merged in 2020-07, with the labels that each got.

#993 fix: make sure amp fallback script always loads latest version
  newspack-theme/functions.php
Labels: Smaller PR, [Status] Approved

#986 Group Block: remove space between group blocks with backgrounds
  newspack-theme/sass/blocks/_blocks.scss
Labels: Smaller PR, [Status] Approved

#948 Refactor: Remove style pack code
  newspack-joseph/functions.php
  newspack-joseph/inc/child-customizer.php
  newspack-katharine/functions.php
  newspack-katharine/inc/child-customizer.php
  newspack-nelson/functions.php
  newspack-nelson/inc/child-customizer.php
  newspack-sacha/functions.php
  newspack-sacha/inc/child-customizer.php
  newspack-scott/functions.php
  newspack-scott/inc/child-customizer.php
  newspack-scott/sass/style.scss
  newspack-theme/classes/class-newspack-style-packs-core.php
  newspack-theme/functions.php
  newspack-theme/inc/color-patterns.php
  newspack-theme/inc/style-packs.php
  newspack-theme/inc/typography.php
  newspack-theme/js/src/style-packs-customizer.js
  newspack-theme/sass/plugins/newspack-ads.scss
  newspack-theme/sass/style-editor-overrides.scss
  newspack-theme/sass/styles/style-1/style-1-editor.scss
  newspack-theme/sass/styles/style-1/style-1.scss
  newspack-theme/sass/styles/style-2/style-2-editor.scss
  newspack-theme/sass/styles/style-2/style-2.scss
  newspack-theme/sass/styles/style-3/style-3-editor.scss
  newspack-theme/sass/styles/style-3/style-3.scss
  newspack-theme/sass/styles/style-4/style-4-editor.scss
  newspack-theme/sass/styles/style-4/style-4.scss
  newspack-theme/sass/styles/style-5/style-5-editor.scss
  newspack-theme/sass/styles/style-5/style-5.scss
  newspack-theme/template-parts/post/author-bio.php
  scripts/compile-scss.js
Labels: [Status] Approved

#994 Refactor: remove missed stylepacks reference
  phpstan.neon.dist
Labels: Smaller PR, [Status] Approved

#972 Fix $content_width setting in theme
  newspack-theme/functions.php
Labels: [Status] Approved

#995 Release 07/07/2020
  newspack-joseph/functions.php
  newspack-joseph/inc/child-customizer.php
  newspack-katharine/functions.php
  newspack-katharine/inc/child-customizer.php
  newspack-nelson/functions.php
  newspack-nelson/inc/child-customizer.php
  newspack-sacha/functions.php
  newspack-sacha/inc/child-customizer.php
  newspack-scott/functions.php
  newspack-scott/inc/child-customizer.php
  newspack-scott/sass/style.scss
  newspack-theme/classes/class-newspack-style-packs-core.php
  newspack-theme/functions.php
  newspack-theme/inc/color-patterns.php
  newspack-theme/inc/style-packs.php
  newspack-theme/inc/typography.php
  newspack-theme/js/src/style-packs-customizer.js
  newspack-theme/sass/blocks/_blocks.scss
  newspack-theme/sass/plugins/newspack-ads.scss
  newspack-theme/sass/style-editor-overrides.scss
  newspack-theme/sass/styles/style-1/style-1-editor.scss
  newspack-theme/sass/styles/style-1/style-1.scss
  newspack-theme/sass/styles/style-2/style-2-editor.scss
  newspack-theme/sass/styles/style-2/style-2.scss
  newspack-theme/sass/styles/style-3/style-3-editor.scss
  newspack-theme/sass/styles/style-3/style-3.scss
  newspack-theme/sass/styles/style-4/style-4-editor.scss
  newspack-theme/sass/styles/style-4/style-4.scss
  newspack-theme/sass/styles/style-5/style-5-editor.scss
  newspack-theme/sass/styles/style-5/style-5.scss
  newspack-theme/template-parts/post/author-bio.php
  phpstan.neon.dist
  scripts/compile-scss.js
Labels: [Status] Approved

#989 Header: Add mobile CTA button
  newspack-joseph/sass/style.scss
  newspack-katharine/sass/style.scss
  newspack-nelson/sass/style.scss
  newspack-sacha/sass/style.scss
  newspack-scott/sass/style.scss
  newspack-theme/functions.php
  newspack-theme/header.php
  newspack-theme/inc/color-patterns.php
  newspack-theme/inc/customizer.php
  newspack-theme/inc/template-functions.php
  newspack-theme/inc/template-tags.php
  newspack-theme/sass/navigation/_menu-mobile-navigation.scss
  newspack-theme/sass/site/header/_site-header.scss
Labels: Needs documentation, [Status] Approved

#1000 Release 14/07/2020
  newspack-joseph/sass/style.scss
  newspack-katharine/sass/style.scss
  newspack-nelson/sass/style.scss
  newspack-sacha/sass/style.scss
  newspack-scott/sass/style.scss
  newspack-theme/functions.php
  newspack-theme/header.php
  newspack-theme/inc/color-patterns.php
  newspack-theme/inc/customizer.php
  newspack-theme/inc/template-functions.php
  newspack-theme/inc/template-tags.php
  newspack-theme/sass/navigation/_menu-mobile-navigation.scss
  newspack-theme/sass/site/header/_site-header.scss
Labels: [Status] Approved

#999 Trust Indicators support
  newspack-joseph/sass/style.scss
  newspack-nelson/sass/style.scss
  newspack-sacha/sass/style.scss
  newspack-scott/sass/style.scss
  newspack-theme/archive.php
  newspack-theme/functions.php
  newspack-theme/inc/template-tags.php
  newspack-theme/inc/trust-indicators.php
  newspack-theme/sass/plugins/trust-indicators.scss
  newspack-theme/sass/styles/style-default/style-default.scss
  newspack-theme/template-parts/header/entry-header.php
  scripts/compile-scss.js
Labels: [Status] Needs Review

#1004 Release Jul 28
  newspack-joseph/sass/style.scss
  newspack-nelson/sass/style.scss
  newspack-sacha/sass/style.scss
  newspack-scott/sass/style.scss
  newspack-theme/archive.php
  newspack-theme/functions.php
  newspack-theme/inc/template-tags.php
  newspack-theme/inc/trust-indicators.php
  newspack-theme/sass/plugins/trust-indicators.scss
  newspack-theme/sass/styles/style-default/style-default.scss
  newspack-theme/template-parts/header/entry-header.php
  scripts/compile-scss.js
Labels: [Status] Approved

#1002 fix: remove URLs from print styles
  newspack-theme/sass/print.scss
Labels: Smaller PR, [Status] Approved
