Repository Automattic/newspack-theme, pull requests merged in 2020-12, with the labels that each got.

#1135 Footer: Add option to change footer background color
  newspack-joseph/inc/child-color-patterns.php
  newspack-katharine/inc/child-color-patterns.php
  newspack-nelson/inc/child-color-patterns.php
  newspack-sacha/inc/child-color-patterns.php
  newspack-scott/inc/child-color-patterns.php
  newspack-theme/inc/color-patterns.php
  newspack-theme/inc/customizer.php
  newspack-theme/js/src/customize-controls.js
  newspack-theme/sass/site/footer/_site-footer.scss
Labels: Needs documentation, [Status] Approved

#1134 Header: Add seperate colour control for primary menu
  newspack-theme/inc/color-patterns.php
  newspack-theme/inc/customizer.php
  newspack-theme/js/src/customize-controls.js
Labels: Needs documentation, [Status] Approved

#1158 fix: correct video width preview in editor
  newspack-theme/sass/style-editor-base.scss
Labels: Smaller PR, [Status] Approved

#1154 Feature: Add option to display 'updated' date
  newspack-katharine/inc/child-typography.php
  newspack-theme/inc/customizer.php
  newspack-theme/inc/template-functions.php
  newspack-theme/inc/template-tags.php
  newspack-theme/js/src/customize-controls.js
  newspack-theme/sass/site/primary/_posts-and-pages.scss
Labels: Needs documentation, [Status] Approved

#1167 fix: correct issue with primary menu background control
  newspack-theme/js/src/customize-controls.js
Labels: [Status] Approved

#1166 Release – Dec. 2
  newspack-joseph/inc/child-color-patterns.php
  newspack-joseph/sass/style.scss
  newspack-katharine/inc/child-color-patterns.php
  newspack-katharine/inc/child-typography.php
  newspack-katharine/sass/style.scss
  newspack-nelson/inc/child-color-patterns.php
  newspack-nelson/sass/style.scss
  newspack-sacha/inc/child-color-patterns.php
  newspack-sacha/sass/style.scss
  newspack-scott/inc/child-color-patterns.php
  newspack-scott/sass/style.scss
  newspack-theme/inc/color-patterns.php
  newspack-theme/inc/customizer.php
  newspack-theme/inc/template-functions.php
  newspack-theme/inc/template-tags.php
  newspack-theme/js/src/customize-controls.js
  newspack-theme/sass/site/footer/_site-footer.scss
  newspack-theme/sass/site/primary/_posts-and-pages.scss
  newspack-theme/sass/style-editor-base.scss
  newspack-theme/sass/style.scss
  package-lock.json
  package.json
Labels: [Status] Approved

#1140 Chore: Update theme POT file and translation files
  newspack-theme/inc/newspack-sponsors.php
  newspack-theme/inc/template-tags.php
  newspack-theme/languages/de_DE.mo
  newspack-theme/languages/de_DE.po
  newspack-theme/languages/es_ES.mo
  newspack-theme/languages/es_ES.po
  newspack-theme/languages/newspack-de_DE-newspack-extend-featured-image-script.json
  newspack-theme/languages/newspack-de_DE-newspack-post-subtitle.json
  newspack-theme/languages/newspack-es_ES-newspack-extend-featured-image-script.json
  newspack-theme/languages/newspack-es_ES-newspack-post-subtitle.json
  newspack-theme/languages/newspack-pt_BR-newspack-extend-featured-image-script.json
  newspack-theme/languages/newspack-pt_BR-newspack-post-subtitle.json
  newspack-theme/languages/newspack-theme.pot
  newspack-theme/languages/pt_BR.mo
  newspack-theme/languages/pt_BR.po
  newspack-theme/template-parts/content/content-page.php
Labels: [Status] Approved

#1156 fix: center sponsor flag in Newspack Sacha
  newspack-sacha/sass/style.scss
Labels: [Status] Approved

#1157 feat: add option to show excerpts on archives
  newspack-theme/archive.php
  newspack-theme/inc/customizer.php
Labels: Needs documentation, [Status] Approved

#1161 Columns block: fix wide alignment width
  newspack-theme/sass/blocks/_blocks.scss
Labels: [Status] Approved

#1133 Simplify block selectors so styles to be applied outside of the content area
  newspack-joseph/inc/child-typography.php
  newspack-joseph/sass/style.scss
  newspack-katharine/inc/child-color-patterns.php
  newspack-katharine/inc/child-typography.php
  newspack-katharine/sass/style.scss
  newspack-nelson/inc/child-typography.php
  newspack-nelson/sass/style.scss
  newspack-sacha/inc/child-color-patterns.php
  newspack-sacha/inc/child-typography.php
  newspack-sacha/sass/style.scss
  newspack-scott/inc/child-color-patterns.php
  newspack-scott/sass/style.scss
  newspack-theme/inc/color-patterns.php
  newspack-theme/inc/typography.php
  newspack-theme/sass/blocks/_blocks.scss
  newspack-theme/sass/site/primary/_posts-and-pages.scss
  newspack-theme/sass/style-editor-base.scss
Labels: [Status] Approved

#1172 Release – Dec. 8
  newspack-joseph/inc/child-typography.php
  newspack-joseph/sass/style.scss
  newspack-katharine/inc/child-color-patterns.php
  newspack-katharine/inc/child-typography.php
  newspack-katharine/sass/style.scss
  newspack-nelson/inc/child-typography.php
  newspack-nelson/sass/style.scss
  newspack-sacha/inc/child-color-patterns.php
  newspack-sacha/inc/child-typography.php
  newspack-sacha/sass/style.scss
  newspack-scott/inc/child-color-patterns.php
  newspack-scott/sass/style.scss
  newspack-theme/archive.php
  newspack-theme/inc/color-patterns.php
  newspack-theme/inc/customizer.php
  newspack-theme/inc/newspack-sponsors.php
  newspack-theme/inc/template-tags.php
  newspack-theme/inc/typography.php
  newspack-theme/languages/de_DE.mo
  newspack-theme/languages/de_DE.po
  newspack-theme/languages/es_ES.mo
  newspack-theme/languages/es_ES.po
  newspack-theme/languages/newspack-de_DE-newspack-extend-featured-image-script.json
  newspack-theme/languages/newspack-de_DE-newspack-post-subtitle.json
  newspack-theme/languages/newspack-es_ES-newspack-extend-featured-image-script.json
  newspack-theme/languages/newspack-es_ES-newspack-post-subtitle.json
  newspack-theme/languages/newspack-pt_BR-newspack-extend-featured-image-script.json
  newspack-theme/languages/newspack-pt_BR-newspack-post-subtitle.json
  newspack-theme/languages/newspack-theme.pot
  newspack-theme/languages/pt_BR.mo
  newspack-theme/languages/pt_BR.po
  newspack-theme/sass/blocks/_blocks.scss
  newspack-theme/sass/site/primary/_posts-and-pages.scss
  newspack-theme/sass/style-editor-base.scss
  newspack-theme/template-parts/content/content-page.php
Labels: [Status] Approved, [Status] Needs Design Review

#1137 Featured Image: Add above placement to single posts
  newspack-scott/sass/style.scss
  newspack-theme/inc/customizer.php
  newspack-theme/inc/template-functions.php
  newspack-theme/inc/template-tags.php
  newspack-theme/js/src/extend-featured-image-editor.js
  newspack-theme/page.php
  newspack-theme/sass/navigation/_menu-highlight-navigation.scss
  newspack-theme/sass/site/primary/_posts-and-pages.scss
  newspack-theme/single-feature.php
  newspack-theme/single-wide.php
  newspack-theme/single.php
  newspack-theme/template-parts/post/large-featured-image.php
Labels: Needs documentation, [Status] Approved

#1176 feat: add Flipboard icon for the social links menu
  newspack-theme/classes/class-newspack-svg-icons.php
Labels: Needs documentation, Smaller PR, [Status] Approved

#1177 feat: add Apple News icon for the social links menu
  newspack-theme/classes/class-newspack-svg-icons.php
Labels: Needs documentation, Smaller PR, [Status] Approved

#1178 fix: override semi-transparent styles for separator block
  newspack-theme/sass/blocks/_blocks.scss
  newspack-theme/sass/style-editor-base.scss
Labels: Smaller PR, [Status] Approved

#1184 Release – Dec. 15
  newspack-scott/sass/style.scss
  newspack-theme/classes/class-newspack-svg-icons.php
  newspack-theme/inc/customizer.php
  newspack-theme/inc/template-functions.php
  newspack-theme/inc/template-tags.php
  newspack-theme/js/src/extend-featured-image-editor.js
  newspack-theme/page.php
  newspack-theme/sass/blocks/_blocks.scss
  newspack-theme/sass/navigation/_menu-highlight-navigation.scss
  newspack-theme/sass/site/primary/_posts-and-pages.scss
  newspack-theme/sass/style-editor-base.scss
  newspack-theme/single-feature.php
  newspack-theme/single-wide.php
  newspack-theme/single.php
  newspack-theme/template-parts/post/large-featured-image.php
Labels: [Status] Approved

#1186 feat: add support for Listings "hide author" option
  newspack-theme/inc/template-tags.php
Labels: [Status] Approved

#1188 Add fr_BE translations to the theme
  newspack-theme/languages/fr_BE.mo
  newspack-theme/languages/fr_BE.po
Labels: [Status] Approved

#1189 Add per-post toggle for updated date
  newspack-theme/functions.php
  newspack-theme/inc/template-functions.php
  newspack-theme/js/src/post-date-updated.js
Labels: Needs documentation, [Status] Approved
