Repository Automattic/newspack-theme, pull requests merged in 2020-11, with the labels that each got.

#1143 Release Nov 11
  newspack-theme/inc/template-functions.php
  newspack-theme/sass/media/_captions.scss
Labels: [Status] Approved

#1144 feat: optimize sponsors queries; fix phpcs lint rules
  newspack-theme/archive.php
  newspack-theme/inc/newspack-sponsors.php
  newspack-theme/template-parts/content/content-archive.php
  newspack-theme/template-parts/content/content-excerpt.php
  newspack-theme/template-parts/content/content-single.php
  newspack-theme/template-parts/header/entry-header.php
  phpcs.xml
Labels: [Status] Approved, [Type] Enhancement

#1123 Feature: Add featured image position options for pages
  newspack-theme/functions.php
  newspack-theme/inc/customizer.php
  newspack-theme/inc/template-functions.php
  newspack-theme/page.php
  newspack-theme/sass/site/primary/_posts-and-pages.scss
  newspack-theme/sass/site/secondary/_widgets.scss
  newspack-theme/template-parts/content/content-page.php
Labels: Needs documentation, [Status] Approved

#1150 Fix fatals if sponsors plugin is inactive
  newspack-theme/archive.php
  newspack-theme/template-parts/content/content-archive.php
  newspack-theme/template-parts/content/content-excerpt.php
  newspack-theme/template-parts/content/content-single.php
  newspack-theme/template-parts/header/entry-header.php
Labels: [Status] Approved

#1152 Release Nov 24
  newspack-theme/archive.php
  newspack-theme/functions.php
  newspack-theme/inc/customizer.php
  newspack-theme/inc/newspack-sponsors.php
  newspack-theme/inc/template-functions.php
  newspack-theme/page.php
  newspack-theme/sass/site/primary/_posts-and-pages.scss
  newspack-theme/sass/site/secondary/_widgets.scss
  newspack-theme/template-parts/content/content-archive.php
  newspack-theme/template-parts/content/content-excerpt.php
  newspack-theme/template-parts/content/content-page.php
  newspack-theme/template-parts/content/content-single.php
  newspack-theme/template-parts/header/entry-header.php
  phpcs.xml
Labels: [Status] Approved
