Repository Automattic/newspack-theme, pull requests merged in 2020-02, with the labels that each got.

#748 Fix AMP compatibility with Coral comments
  newspack-theme/front-page.php
  newspack-theme/image.php
  newspack-theme/inc/template-tags.php
  newspack-theme/page.php
  newspack-theme/single-feature.php
  newspack-theme/single-wide.php
  newspack-theme/single.php
Labels: [Status] Approved

#744 Add German translations to the theme
  newspack-theme/languages/de_DE.mo
  newspack-theme/languages/de_DE.po
  newspack-theme/languages/newspack-de_DE-newspack-extend-featured-image-script.json
  newspack-theme/languages/newspack-de_DE-newspack-post-subtitle.json
Labels: [Status] Approved

#745 Fix: Make sure correct colour is used for the category + Sacha theme
  newspack-sacha/inc/child-color-patterns.php
Labels: Smaller PR, [Status] Approved

#746 Katharine: Correct custom colour usage on accent headers in the editor
  newspack-katharine/inc/child-color-patterns.php
Labels: Smaller PR, [Status] Approved

#755 Bump versions for release
  newspack-joseph/sass/style.scss
  newspack-katharine/sass/style.scss
  newspack-nelson/sass/style.scss
  newspack-sacha/sass/style.scss
  newspack-scott/sass/style.scss
  newspack-theme/sass/style.scss
Labels: [Status] Needs Review

#756 Only output AMP toolbar attributes for the mobile menu when the menu space exists
  newspack-theme/inc/template-tags.php
Labels: [Status] Approved

#764 Override Photon Avatar Downsizing
  newspack-theme/functions.php
Labels: [Status] Approved

#767 Add classes for the category and tags to the primary `<section>`
  newspack-theme/inc/template-functions.php
  newspack-theme/single-feature.php
  newspack-theme/single-wide.php
  newspack-theme/single.php
Labels: [Status] Approved

#768 Chore: Bump version number
  newspack-joseph/sass/style.scss
  newspack-katharine/sass/style.scss
  newspack-nelson/sass/style.scss
  newspack-sacha/sass/style.scss
  newspack-scott/sass/style.scss
  newspack-theme/sass/style.scss
Labels: [Status] Approved

#796 Fix: Make sure CAP guest authors are also used in RSS feed
  newspack-theme/functions.php
Labels: [Status] Needs Review

#698 Remove escaping from custom colour and typography CSS
  newspack-sacha/functions.php
  newspack-sacha/inc/child-color-patterns.php
  newspack-sacha/inc/child-typography.php
  newspack-scott/inc/child-color-patterns.php
  newspack-scott/inc/child-typography.php
  newspack-theme/functions.php
  newspack-theme/inc/color-filters.php
  newspack-theme/inc/color-patterns.php
  newspack-theme/inc/template-functions.php
  newspack-theme/inc/typography.php
Labels: [Status] Approved

#771 Make sure highlight menu is using the correct colour for visited links
  newspack-theme/sass/navigation/_menu-highlight-navigation.scss
Labels: Smaller PR, [Status] Approved

#780 Fix: Active menu toggle button colour
  newspack-theme/sass/navigation/_menu-mobile-navigation.scss
Labels: Smaller PR, [Status] Approved

#783 Remove Style Pack files if using the default theme and default style packs
  newspack-theme/functions.php
Labels: Smaller PR, [Status] Approved

#797 Remove unneeded escaping from Katharine, Scott custom typography and colours code
  newspack-katharine/functions.php
  newspack-scott/functions.php
Labels: [Status] Approved

#770 Refactor: Simplify the mobile menu files
  newspack-theme/header.php
  newspack-theme/template-parts/header/mobile-sidebar-fallback.php
  newspack-theme/template-parts/header/mobile-sidebar.php
Labels: [Status] Approved

#775 Fix: Correct link colours for the carousel block
  newspack-theme/sass/blocks/_blocks.scss
  newspack-theme/sass/style-editor-base.scss
Labels: [Status] Approved

#792 Fix: Improve Latest Comments font styles
  newspack-theme/sass/blocks/_blocks.scss
  newspack-theme/sass/style-editor-base.scss
Labels: [Status] Approved

#789 fix: Correct font used by AMP lightbox overlays for the gallery block
  newspack-theme/inc/typography.php
  newspack-theme/sass/media/_captions.scss
Labels: Smaller PR, [Status] Approved

#793 Add separate custom colour control for the Header Background
  newspack-joseph/inc/child-color-patterns.php
  newspack-katharine/inc/child-color-patterns.php
  newspack-nelson/inc/child-color-patterns.php
  newspack-sacha/inc/child-color-patterns.php
  newspack-scott/inc/child-color-patterns.php
  newspack-theme/inc/color-patterns.php
  newspack-theme/inc/customizer.php
  newspack-theme/js/src/customize-controls.js
Labels: [Status] Approved

#801 Chore: Bump version number
  newspack-joseph/sass/style.scss
  newspack-katharine/sass/style.scss
  newspack-nelson/sass/style.scss
  newspack-sacha/sass/style.scss
  newspack-scott/sass/style.scss
  newspack-theme/sass/style.scss
Labels: [Status] Approved

#799 Fix: Add dashboard notification for the upcoming removal of the Style Packs
  newspack-theme/functions.php
Labels: [Status] Approved

#757 Configure: automatic releases, commit linting
  .circleci/config.yml
  commitlint.config.js
  composer.json
  package-lock.json
  package.json
  release.config.js
Labels: [Status] Approved

#809 Bump version for release
  newspack-joseph/sass/style.scss
  newspack-katharine/sass/style.scss
  newspack-nelson/sass/style.scss
  newspack-sacha/sass/style.scss
  newspack-scott/sass/style.scss
  newspack-theme/sass/style.scss
Labels: [Status] Approved
