Repository Automattic/newspack-theme, pull requests merged in 2020-10, with the labels that each got.

#1103 Release Oct. 7
  newspack-scott/sass/style.scss
Labels: [Status] Approved

#1104 Add option to turn off Yoast's primary category, so all categories display
  newspack-theme/inc/customizer.php
  newspack-theme/inc/template-tags.php
Labels: Needs documentation, [Status] Approved

#1109 Image Block: Target only smaller screen sizes for image block fix
  newspack-theme/sass/blocks/_blocks.scss
Labels: [Status] Approved

#1110 Newspack Katharine: Fix menu hover background in dropdowns
  newspack-katharine/inc/child-color-patterns.php
  newspack-katharine/sass/style.scss
Labels: [Status] Approved

#1111 fix: correct dropdown colors for Newspack Sacha
  newspack-sacha/inc/child-color-patterns.php
  newspack-sacha/sass/style.scss
Labels: [Status] Approved

#1112 fix: make sure accent header in the editor matches the front end
  newspack-joseph/inc/child-typography.php
  newspack-joseph/sass/style-editor.scss
  newspack-katharine/inc/child-color-patterns.php
  newspack-katharine/inc/child-typography.php
  newspack-katharine/sass/style-editor.scss
  newspack-nelson/inc/child-typography.php
  newspack-sacha/inc/child-color-patterns.php
  newspack-sacha/inc/child-typography.php
  newspack-scott/inc/child-color-patterns.php
  newspack-scott/inc/child-typography.php
  newspack-theme/inc/color-patterns.php
  newspack-theme/inc/typography.php
  newspack-theme/sass/styles/style-default/style-default-editor.scss
Labels: [Status] Approved

#1113 fix: prevent captions from getting cut off with image-beside setting
  newspack-theme/sass/media/_captions.scss
Labels: [Status] Approved

#1118 Oct. 20 – Release
  newspack-joseph/inc/child-typography.php
  newspack-joseph/sass/style-editor.scss
  newspack-katharine/inc/child-color-patterns.php
  newspack-katharine/inc/child-typography.php
  newspack-katharine/sass/style-editor.scss
  newspack-katharine/sass/style.scss
  newspack-nelson/inc/child-typography.php
  newspack-sacha/inc/child-color-patterns.php
  newspack-sacha/inc/child-typography.php
  newspack-sacha/sass/style.scss
  newspack-scott/inc/child-color-patterns.php
  newspack-scott/inc/child-typography.php
  newspack-theme/inc/color-patterns.php
  newspack-theme/inc/customizer.php
  newspack-theme/inc/template-tags.php
  newspack-theme/inc/typography.php
  newspack-theme/sass/blocks/_blocks.scss
  newspack-theme/sass/media/_captions.scss
  newspack-theme/sass/style-editor-base.scss
  newspack-theme/sass/styles/style-default/style-default-editor.scss
Labels: [Status] Approved, [Status] Needs Design Review

#1120 Make sure featured image placements aren't applied to CPTs
  newspack-theme/inc/template-functions.php
Labels: [Status] Approved

#1121 Avoid error with AMP fallback for the search
  newspack-theme/js/src/amp-fallback.js
Labels: [Status] Approved

#1126 Release Oct 27
  newspack-theme/inc/template-functions.php
  newspack-theme/js/src/amp-fallback.js
Labels: [Status] Approved

#1129 Captions: correct caption width issue
  newspack-theme/sass/media/_captions.scss
Labels: [Status] Approved
