Repository Automattic/newspack-theme, pull requests merged in 2020-01, with the labels that each got.

#657 Update README formatting
  README.md
Labels: [Status] Approved

#660 Style 1, 3: Remove styles that hide :before on headers
  sass/blocks/_blocks.scss
  sass/style-editor-base.scss
Labels: Smaller PR, [Status] Approved

#658 Style 2: Correct separator styles
  newspack-theme/sass/styles/style-2/style-2-editor.scss
  newspack-theme/sass/styles/style-2/style-2.scss
Labels: Smaller PR, [Status] Approved, [Status] Needs changes or feedback

#667 Update theme README file to address the structure update
  README.md
Labels: Smaller PR, [Status] Approved

#661 Make sure correct fonts are used for archive subheaders, menu toggle.
  newspack-theme/inc/typography.php
Labels: [Status] Approved

#662 Links: Fix issues with links not inheriting the correct colours
  newspack-theme/inc/color-patterns.php
  newspack-theme/sass/blocks/_blocks.scss
  newspack-theme/sass/elements/_elements.scss
  newspack-theme/sass/navigation/_links.scss
  newspack-theme/sass/style-editor-base.scss
Labels: [Status] Approved

#470 Pullquote block: Simplify style selectors
  newspack-theme/inc/color-patterns.php
  newspack-theme/inc/typography.php
  newspack-theme/sass/blocks/_blocks.scss
  newspack-theme/sass/styles/style-1/style-1-editor.scss
  newspack-theme/sass/styles/style-1/style-1.scss
  newspack-theme/sass/styles/style-2/style-2-editor.scss
  newspack-theme/sass/styles/style-2/style-2.scss
  newspack-theme/sass/styles/style-3/style-3-editor.scss
  newspack-theme/sass/styles/style-3/style-3.scss
  newspack-theme/sass/styles/style-4/style-4.scss
  newspack-theme/sass/styles/style-5/style-5-editor.scss
  newspack-theme/sass/styles/style-5/style-5.scss
Labels: [Status] Approved

#670 Fix typo in readme
  README.md
Labels: [Status] Approved

#671 Bump version number to 1.0.0-alpha.25
  newspack-theme/sass/style.scss
Labels: [Status] Approved

#676 Fix styling: footer credits for style 1
  newspack-theme/sass/styles/style-1/style-1.scss
Labels: [Status] Approved

#677 Styling links: remove underline on hover
  newspack-theme/sass/site/primary/_posts-and-pages.scss
Labels: [Status] Approved

#672 Update function that checks if style pack is assigned
  newspack-theme/functions.php
  newspack-theme/inc/color-patterns.php
Labels: [Status] Approved

#659 Default style: Minor spacing adjustment to accent headers
  newspack-theme/sass/styles/style-default/style-default-editor.scss
  newspack-theme/sass/styles/style-default/style-default.scss
Labels: Smaller PR, [Status] Approved

#673 Move `newspack_color_with_contrast()` function
  newspack-theme/inc/color-patterns.php
  newspack-theme/inc/template-functions.php
Labels: Smaller PR, [Status] Approved

#656 Update node-sass and calypso-build to support node v.12
  package-lock.json
  package.json
Labels: [Status] Approved

#678 Style: make button block inherit custom font
  newspack-theme/inc/typography.php
Labels: [Status] Approved

#684 Organic Profile Block: Overwrite some of the default styles to make the block more generic to Newspack
  newspack-theme/sass/blocks/_blocks.scss
  newspack-theme/sass/style-editor-base.scss
Labels: [Status] Approved, [Status] Needs Discussion

#679 Beside image style: Make sure colours are inherited correctly
  newspack-theme/inc/color-patterns.php
  newspack-theme/sass/site/primary/_posts-and-pages.scss
  newspack-theme/sass/styles/style-3/style-3.scss
  newspack-theme/sass/styles/style-5/style-5.scss
Labels: [Status] Approved

#686 Update editor classes to match what's currently in Gutenberg
  newspack-theme/inc/color-patterns.php
  newspack-theme/inc/typography.php
Labels: [Status] Approved

#680 Add a child theme to replace Style 4
  newspack-sacha/functions.php
  newspack-sacha/inc/child-color-patterns.php
  newspack-sacha/inc/child-customizer.php
  newspack-sacha/inc/child-typography.php
  newspack-sacha/sass/style-editor.scss
  newspack-sacha/sass/style.scss
  newspack-sacha/sass/variables-style/_fonts.scss
  newspack-sacha/sass/variables-style/_variables-style.scss
  newspack-sacha/screenshot.png
  newspack-sacha/template-parts/posts/author-bio.php
  newspack-theme/sass/styles/style-4/style-4-editor.scss
  newspack-theme/sass/styles/style-4/style-4.scss
  package.json
  scripts/compile-scss.js
Labels: [Status] Approved

#691 Bump version number
  newspack-sacha/sass/style.scss
  newspack-theme/sass/style.scss
Labels: [Status] Approved

#692 Default Style: Make 'Tertiary menu' styles more consistent across header settings
  newspack-theme/inc/color-patterns.php
  newspack-theme/sass/styles/style-default/style-default.scss
Labels: [Status] Needs Review

#690 Newspack Sacha: Correct code comments
  newspack-sacha/inc/child-color-patterns.php
  newspack-sacha/inc/child-customizer.php
  newspack-sacha/template-parts/posts/author-bio.php
Labels: Smaller PR, [Status] Approved

#693 Newspack Sacha: Correct child theme text domain
  newspack-sacha/sass/style.scss
Labels: Smaller PR, [Status] Approved

#681 Improve spacing on accent headers, compared to article blocks.
  newspack-theme/sass/blocks/_blocks.scss
  newspack-theme/sass/styles/style-1/style-1.scss
  newspack-theme/sass/styles/style-2/style-2.scss
  newspack-theme/sass/styles/style-3/style-3.scss
  newspack-theme/sass/styles/style-5/style-5.scss
  newspack-theme/sass/styles/style-default/style-default.scss
Labels: [Status] Approved, [Status] Needs Discussion

#682 Improve styles of Latest Comments block
  newspack-theme/inc/typography.php
  newspack-theme/sass/blocks/_blocks.scss
  newspack-theme/sass/style-editor-base.scss
Labels: [Status] Approved

#689 Group Block: Sit right under header on home page
  newspack-theme/sass/blocks/_blocks.scss
  newspack-theme/sass/layout/_layout.scss
  newspack-theme/sass/styles/style-2/style-2.scss
Labels: Smaller PR, [Status] Approved

#695 Linting and formatting - JS code
  .eslintrc.js
  .gitignore
  .prettierignore
  composer.json
  composer.lock
  newspack-theme/js/originals/skip-link-focus-fix.js
  newspack-theme/js/src/amp-fallback.js
  newspack-theme/js/src/customize-controls.js
  newspack-theme/js/src/customize-preview.js
  newspack-theme/js/src/extend-featured-image-editor.js
  newspack-theme/js/src/logo-customize-controls.js
  newspack-theme/js/src/logo-customize-preview.js
  newspack-theme/js/src/post-subtitle/SubtitleEditor.js
  newspack-theme/js/src/post-subtitle/index.js
  newspack-theme/js/src/post-subtitle/utils.js
  newspack-theme/js/src/style-packs-customizer.js
  package-lock.json
  package.json
Labels: [Status] Approved

#702 Fix: Add wp_body_open right after the opening body tag.
  newspack-theme/header.php
Labels: Smaller PR, [Status] Approved

#694 Add child theme to replace Style 1
  newspack-scott/functions.php
  newspack-scott/inc/child-color-patterns.php
  newspack-scott/inc/child-customizer.php
  newspack-scott/inc/child-typography.php
  newspack-scott/sass/style-editor.scss
  newspack-scott/sass/style.scss
  newspack-scott/sass/variables-style/_fonts.scss
  newspack-scott/sass/variables-style/_variables-style.scss
  newspack-scott/screenshot.png
  newspack-theme/sass/styles/style-1/style-1-editor.scss
  newspack-theme/sass/styles/style-1/style-1.scss
  newspack-theme/sass/styles/style-1/variables-style/_colors.scss
  package.json
  scripts/compile-scss.js
Labels: [Status] Approved

#703 Fix: handle post subtitle in Code editor mode
  newspack-theme/js/src/post-subtitle/index.js
  newspack-theme/js/src/post-subtitle/utils.js
Labels: [Status] Approved

#699 Copy Theme Settings When Switching
  newspack-theme/functions.php
Labels: [Status] Approved

#696 Default Style: Improve tertiary nav padding
  newspack-theme/sass/styles/style-default/style-default.scss
Labels: Smaller PR, [Status] Approved

#704 Add child theme to replace style 2
  newspack-nelson/functions.php
  newspack-nelson/inc/child-color-patterns.php
  newspack-nelson/inc/child-customizer.php
  newspack-nelson/inc/child-typography.php
  newspack-nelson/sass/style-editor.scss
  newspack-nelson/sass/style.scss
  newspack-nelson/sass/variables-style/_fonts.scss
  newspack-nelson/sass/variables-style/_variables-style.scss
  newspack-nelson/screenshot.png
  newspack-theme/sass/styles/style-2/style-2-editor.scss
  newspack-theme/sass/styles/style-2/style-2.scss
  package.json
  scripts/compile-scss.js
Labels: [Status] Approved

#708 Fix: Remove style pack required files if using a child theme
  newspack-theme/functions.php
Labels: Smaller PR, [Status] Approved

#707 Fix: Correct missing italicized version of font in Newspack Scott
  newspack-scott/functions.php
Labels: Smaller PR, [Status] Approved

#685 Make sure column block border styles are being applied correctly
  newspack-theme/sass/style-editor-base.scss
  newspack-theme/sass/styles/style-3/style-3-editor.scss
  newspack-theme/sass/styles/style-5/style-5-editor.scss
  newspack-theme/sass/styles/style-5/style-5.scss
Labels: [Status] Approved

#713 Bump version number
  newspack-nelson/sass/style.scss
  newspack-sacha/sass/style.scss
  newspack-scott/sass/style.scss
  newspack-theme/sass/style.scss
Labels: Smaller PR, [Status] Approved

#710 Add child theme to replace style 3
  newspack-katharine/functions.php
  newspack-katharine/inc/child-color-patterns.php
  newspack-katharine/inc/child-customizer.php
  newspack-katharine/inc/child-typography.php
  newspack-katharine/sass/style-editor.scss
  newspack-katharine/sass/style.scss
  newspack-katharine/sass/variables-style/_fonts.scss
  newspack-katharine/sass/variables-style/_variables-style.scss
  newspack-katharine/screenshot.png
  newspack-theme/sass/styles/style-3/style-3-editor.scss
  newspack-theme/sass/styles/style-3/style-3.scss
  package.json
  scripts/compile-scss.js
Labels: [Status] Approved

#714 Refactor: Add child theme to replace Style 5
  newspack-joseph/functions.php
  newspack-joseph/inc/child-color-patterns.php
  newspack-joseph/inc/child-customizer.php
  newspack-joseph/inc/child-typography.php
  newspack-joseph/sass/style-editor.scss
  newspack-joseph/sass/style.scss
  newspack-joseph/sass/variables-style/_colors.scss
  newspack-joseph/sass/variables-style/_fonts.scss
  newspack-joseph/sass/variables-style/_variables-style.scss
  newspack-joseph/screenshot.png
  newspack-theme/sass/styles/style-5/style-5-editor.scss
  newspack-theme/sass/styles/style-5/style-5.scss
  package.json
  scripts/compile-scss.js
Labels: [Status] Approved

#717 Bump version number
  newspack-joseph/sass/style.scss
  newspack-katharine/sass/style.scss
  newspack-nelson/sass/style.scss
  newspack-sacha/sass/style.scss
  newspack-scott/sass/style.scss
  newspack-theme/sass/style.scss
Labels: Smaller PR, [Status] Approved

#706 Fix: Hide author, publish date on pages in search results
  newspack-theme/sass/site/primary/_archives.scss
  newspack-theme/template-parts/content/content-excerpt.php
Labels: Smaller PR, [Status] Approved

#719 Fix: Run screenshots through image optimizer, to reduce size.
  newspack-katharine/screenshot.png
  newspack-sacha/screenshot.png
  newspack-scott/screenshot.png
  newspack-theme/screenshot.png
Labels: [Status] Approved

#718 Fix: Update screenshots for Newspack Nelson, Joseph, to correct logo
  newspack-joseph/screenshot.png
  newspack-nelson/screenshot.png
Labels: [Status] Approved

#731 Fix: Correct issue in Katharine's colour code that was throwing errors
  newspack-katharine/inc/child-color-patterns.php
Labels: Smaller PR, [Status] Approved

#736 Bump version numbers
  newspack-joseph/sass/style.scss
  newspack-katharine/sass/style.scss
  newspack-nelson/sass/style.scss
  newspack-sacha/sass/style.scss
  newspack-scott/sass/style.scss
  newspack-theme/sass/style.scss
Labels: [Status] Approved

#738 Fix: Update footer logo code, to fix non-cropping issue
  newspack-theme/inc/customizer.php
Labels: Smaller PR, [Status] Approved

#732 Fix: Remove duplicate border on posts with Sacha theme
  newspack-sacha/sass/style.scss
Labels: Smaller PR, [Status] Approved, [Theme] Sacha

#742 Update screenshots to match demo sites
  newspack-joseph/screenshot.png
  newspack-katharine/screenshot.png
  newspack-nelson/screenshot.png
  newspack-sacha/screenshot.png
  newspack-scott/screenshot.png
  newspack-theme/screenshot.png
Labels: [Status] Approved

#737 Make sure site title and site description are always aligned to the baseline
  newspack-theme/sass/site/header/_site-header.scss
  newspack-theme/template-parts/header/site-branding.php
Labels: [Status] Approved

#743 Fix: Correct JavaScript translation file path for new parent/child theme setup
  newspack-theme/functions.php
Labels: Smaller PR, [Status] Approved
