Repository Automattic/newspack-theme, pull requests merged in 2020-06, with the labels that each got.

#957 fix: WooCommerce shop description markup
  newspack-theme/inc/woocommerce.php
Labels: [Pri] High, [Status] Approved, [Type] Bug

#958 Release June 3/2020
  .github/workflows/main.yml
  newspack-joseph/sass/style-editor.scss
  newspack-joseph/sass/style.scss
  newspack-katharine/sass/style-editor.scss
  newspack-katharine/sass/style.scss
  newspack-nelson/sass/style-editor.scss
  newspack-nelson/sass/style.scss
  newspack-sacha/functions.php
  newspack-sacha/sass/child-style-editor-overrides.scss
  newspack-sacha/sass/style.scss
  newspack-sacha/template-parts/post/author-bio.php
  newspack-scott/sass/style-editor.scss
  newspack-scott/sass/style.scss
  newspack-theme/archive.php
  newspack-theme/classes/class-newspack-svg-icons.php
  newspack-theme/functions.php
  newspack-theme/inc/customizer.php
  newspack-theme/inc/logo-resizer.php
  newspack-theme/inc/template-functions.php
  newspack-theme/inc/template-tags.php
  newspack-theme/inc/typography.php
  newspack-theme/inc/woocommerce.php
  newspack-theme/js/src/amp-fallback.js
  newspack-theme/sass/blocks/_blocks.scss
  newspack-theme/sass/site/header/_site-header.scss
  newspack-theme/sass/site/primary/_posts-and-pages.scss
  newspack-theme/sass/style-editor-base.scss
  newspack-theme/sass/styles/style-default/style-default.scss
  newspack-theme/sass/typography/_headings.scss
  newspack-theme/template-parts/post/author-bio.php
  newspack-theme/template-parts/post/large-featured-image.php
  scripts/compile-scss.js
Labels: [Status] Approved

#945 Add hook above archive posts
  newspack-theme/archive.php
Labels: [Status] Approved

#955 Author Bio: Display social icons from Yoast
  newspack-sacha/sass/style.scss
  newspack-sacha/template-parts/post/author-bio.php
  newspack-theme/archive.php
  newspack-theme/classes/class-newspack-svg-icons.php
  newspack-theme/inc/customizer.php
  newspack-theme/inc/template-tags.php
  newspack-theme/js/src/customize-controls.js
  newspack-theme/sass/site/primary/_posts-and-pages.scss
  newspack-theme/template-parts/post/author-bio.php
Labels: [Status] Approved

#959 Correct path to WooCommerce fonts in theme
  newspack-theme/sass/plugins/woocommerce.scss
Labels: [Status] Approved

#962 Subpage Header: Hide below header ad in certain cases
  newspack-theme/sass/plugins/newspack-ads.scss
Labels: [Status] Approved

#963 Subpage Header: Make sure subpage menu toggle is not there when empty
  newspack-theme/header.php
Labels: [Status] Approved

#969 Release 09/06/2020
  newspack-sacha/sass/style.scss
  newspack-sacha/template-parts/post/author-bio.php
  newspack-theme/archive.php
  newspack-theme/classes/class-newspack-svg-icons.php
  newspack-theme/header.php
  newspack-theme/inc/customizer.php
  newspack-theme/inc/template-tags.php
  newspack-theme/js/src/customize-controls.js
  newspack-theme/sass/plugins/newspack-ads.scss
  newspack-theme/sass/plugins/woocommerce.scss
  newspack-theme/sass/site/primary/_posts-and-pages.scss
  newspack-theme/template-parts/post/author-bio.php
Labels: [Status] Approved

#974 Fallback to author if coauthors fails
  newspack-sacha/template-parts/post/author-bio.php
  newspack-theme/inc/template-tags.php
  newspack-theme/template-parts/post/author-bio.php
Labels: [Status] Approved, [Type] Bug

#978 Allow other post types to register featured image settings support
  newspack-theme/functions.php
  newspack-theme/js/src/extend-featured-image-editor.js
Labels: [Priority] High, [Status] Approved

#981 Update footer message
  newspack-theme/footer.php
Labels: [Status] Approved

#982 Release 23/06/2020
  newspack-sacha/template-parts/post/author-bio.php
  newspack-theme/footer.php
  newspack-theme/functions.php
  newspack-theme/inc/template-tags.php
  newspack-theme/js/src/extend-featured-image-editor.js
  newspack-theme/template-parts/post/author-bio.php
Labels: [Status] Approved

#988 feat: default post template selection
  newspack-theme/functions.php
  newspack-theme/inc/customizer.php
Labels: Needs documentation, [Status] Approved

#987 Comments: improve appearance of comment log in messages
  newspack-theme/inc/color-patterns.php
  newspack-theme/inc/typography.php
  newspack-theme/sass/site/primary/_comments.scss
  newspack-theme/sass/typography/_headings.scss
Labels: [Status] Approved

#985 Menus: Close slide out menus when clicking overlays (non-AMP fallback)
  newspack-theme/js/src/amp-fallback.js
  newspack-theme/sass/navigation/_menu-mobile-navigation.scss
Labels: [Status] Approved

#990 Release - June 30, 2020
  newspack-theme/functions.php
  newspack-theme/inc/color-patterns.php
  newspack-theme/inc/customizer.php
  newspack-theme/inc/typography.php
  newspack-theme/js/src/amp-fallback.js
  newspack-theme/sass/navigation/_menu-mobile-navigation.scss
  newspack-theme/sass/site/primary/_comments.scss
  newspack-theme/sass/typography/_headings.scss
Labels: [Status] Approved
