Repository Automattic/newspack-theme, pull requests merged in 2020-09, with the labels that each got.

#1037 Adds/desktop slideout control
  newspack-theme/header.php
  newspack-theme/inc/customizer.php
  newspack-theme/js/src/customize-controls.js
  newspack-theme/sass/navigation/_menu-mobile-navigation.scss
  newspack-theme/template-parts/header/desktop-sidebar.php
Labels: [Status] Approved

#1051 Release Sep 01
  newspack-theme/header.php
  newspack-theme/inc/customizer.php
  newspack-theme/js/src/customize-controls.js
  newspack-theme/sass/navigation/_menu-mobile-navigation.scss
  newspack-theme/template-parts/header/desktop-sidebar.php
Labels: [Status] Approved

#1045 fix: make sure sponsor flag is not cut off for Newspack Katharine
  newspack-katharine/sass/style-editor.scss
  newspack-katharine/sass/style.scss
Labels: [Status] Approved

#1046 Sponsored Content: make sure sponsored content styles survive tree shaking
  newspack-theme/inc/newspack-sponsors.php
  newspack-theme/inc/typography.php
  newspack-theme/sass/plugins/newspack-sponsors.scss
  newspack-theme/sass/site/primary/_posts-and-pages.scss
  newspack-theme/sass/typography/_headings.scss
Labels: [Status] Approved

#1049 Improve logo size behavior with mobile CTA
  newspack-theme/sass/mixins/_utilities.scss
  newspack-theme/sass/site/header/_site-header.scss
Labels: [Status] Approved

#1052 Header: prevent gap between mobile CTA and menu toggle
  newspack-theme/header.php
Labels: Smaller PR, [Status] Approved

#1053 fix: harmonise how the author link is printed regardless of truncation
  newspack-theme/template-parts/post/author-bio.php
Labels: [Status] Approved

#1058 Image Block: prevent gaps above captions in mobile Safari
  newspack-theme/sass/blocks/_blocks.scss
Labels: [Status] Approved

#1059 Add 'time ago' date option to theme
  newspack-theme/footer.php
  newspack-theme/inc/customizer.php
  newspack-theme/inc/template-functions.php
  newspack-theme/js/src/customize-controls.js
  newspack-theme/sidebar.php
Labels: [Status] Approved

#1062 Release Sep 08
  newspack-katharine/sass/style-editor.scss
  newspack-katharine/sass/style.scss
  newspack-theme/footer.php
  newspack-theme/header.php
  newspack-theme/inc/customizer.php
  newspack-theme/inc/newspack-sponsors.php
  newspack-theme/inc/template-functions.php
  newspack-theme/inc/typography.php
  newspack-theme/js/src/customize-controls.js
  newspack-theme/sass/blocks/_blocks.scss
  newspack-theme/sass/mixins/_utilities.scss
  newspack-theme/sass/plugins/newspack-sponsors.scss
  newspack-theme/sass/site/header/_site-header.scss
  newspack-theme/sass/site/primary/_posts-and-pages.scss
  newspack-theme/sass/typography/_headings.scss
  newspack-theme/sidebar.php
  newspack-theme/template-parts/post/author-bio.php
  package-lock.json
Labels: [Status] Approved

#1028 Create releases on external repos on release
  .circleci/config.yml
  package-lock.json
  package.json
  release.config.js
  scripts/create-child-releases.js
Labels: [Status] Approved

#1060 Add simplified gradient set
  newspack-theme/functions.php
  newspack-theme/inc/color-patterns.php
  newspack-theme/inc/template-functions.php
  newspack-theme/sass/blocks/_blocks.scss
  newspack-theme/sass/style-editor-base.scss
Labels: Needs documentation, [Status] Approved

#1071 Fix PHP errors from the "time ago" functionality
  newspack-theme/footer.php
  newspack-theme/inc/template-functions.php
  newspack-theme/sidebar.php
Labels: [Status] Approved

#1068 Update method for getting current time
  newspack-theme/inc/template-functions.php
Labels: [Status] Approved

#1072 Alpha release Sep 10
  .circleci/config.yml
  newspack-theme/footer.php
  newspack-theme/functions.php
  newspack-theme/inc/color-patterns.php
  newspack-theme/inc/template-functions.php
  newspack-theme/sass/blocks/_blocks.scss
  newspack-theme/sass/style-editor-base.scss
  newspack-theme/sidebar.php
  package-lock.json
  package.json
  release.config.js
  scripts/create-child-releases.js
Labels: [Status] Needs Review

#1073 Release Sep 10
  .circleci/config.yml
  newspack-theme/footer.php
  newspack-theme/functions.php
  newspack-theme/inc/color-patterns.php
  newspack-theme/inc/template-functions.php
  newspack-theme/sass/blocks/_blocks.scss
  newspack-theme/sass/style-editor-base.scss
  newspack-theme/sidebar.php
  package-lock.json
  package.json
  release.config.js
  scripts/create-child-releases.js
Labels: [Status] Approved

#1077 fix: show credit if credit is set and caption is not
  newspack-theme/inc/template-tags.php
Labels: [Status] Approved

#1074 Add support for the Aside post format
  newspack-theme/functions.php
  newspack-theme/sass/blocks/_blocks.scss
  newspack-theme/sass/site/primary/_archives.scss
  newspack-theme/sass/site/primary/_posts-and-pages.scss
  newspack-theme/sass/style-editor-base.scss
  newspack-theme/single.php
Labels: Needs documentation, [Status] Approved

#1070 Fix: improve contrast in light grey text
  newspack-theme/sass/variables-site/_colors.scss
Labels: Smaller PR, [Status] Approved

#1079 Release Sep 15
  newspack-theme/functions.php
  newspack-theme/inc/template-tags.php
  newspack-theme/sass/blocks/_blocks.scss
  newspack-theme/sass/site/primary/_archives.scss
  newspack-theme/sass/site/primary/_posts-and-pages.scss
  newspack-theme/sass/style-editor-base.scss
  newspack-theme/sass/variables-site/_colors.scss
  newspack-theme/single.php
Labels: [Status] Approved

#1080 fix: relative time filter should use the correct $post object
  newspack-theme/footer.php
  newspack-theme/inc/template-functions.php
  newspack-theme/sidebar.php
Labels: [Status] Approved

#1082 Update Facebook's SVG icon
  newspack-theme/classes/class-newspack-svg-icons.php
Labels: [Status] Approved

#1044 fix: update sharing title styles to be more specific
  newspack-theme/sass/site/primary/_posts-and-pages.scss
Labels: Smaller PR, [Status] Needs Review

#1086 Release Sep 22
  newspack-theme/classes/class-newspack-svg-icons.php
  newspack-theme/footer.php
  newspack-theme/inc/template-functions.php
  newspack-theme/sass/site/primary/_posts-and-pages.scss
  newspack-theme/sidebar.php
Labels: [Status] Approved

#1092 Tagline: Make sure it's picking up custom fonts
  newspack-theme/inc/typography.php
Labels: Smaller PR, [Status] Approved

#1088 Sponsored Content: Remove $ symbol
  newspack-theme/inc/newspack-sponsors.php
  newspack-theme/sass/plugins/newspack-sponsors.scss
Labels: [Status] Approved

#1090 fix: switch menu dropdowns to use primary color to improve contrast
  newspack-theme/inc/color-patterns.php
  newspack-theme/sass/navigation/_menu-dropdown.scss
Labels: [Status] Approved

#1096 Release Sep 29
  newspack-theme/inc/color-patterns.php
  newspack-theme/inc/newspack-sponsors.php
  newspack-theme/inc/typography.php
  newspack-theme/sass/navigation/_menu-dropdown.scss
  newspack-theme/sass/plugins/newspack-sponsors.scss
Labels: [Status] Approved

#1091 Newspack Scott: Make sure footer widgets pick up correct custom font
  newspack-scott/sass/style.scss
Labels: [Status] Approved
