Repository Automattic/newspack-theme, pull requests merged in 2021-09, with the labels that each got.

#1491 fix: ensure header_color is defined in child themes
  newspack-joseph/inc/child-color-patterns.php
  newspack-katharine/inc/child-color-patterns.php
  newspack-nelson/inc/child-color-patterns.php
  newspack-sacha/inc/child-color-patterns.php
  newspack-scott/inc/child-color-patterns.php
  newspack-theme/inc/color-patterns.php
Labels: [Status] Approved

#1497 feat: option to pick page default template
  newspack-theme/functions.php
  newspack-theme/inc/customizer.php
Labels: [Status] Approved

#1498 fix: turn off AMP lightbox by default for theme elements
  newspack-theme/header.php
Labels: [Status] Approved

#1504 Release Sep 08
  newspack-joseph/inc/child-color-patterns.php
  newspack-katharine/inc/child-color-patterns.php
  newspack-nelson/inc/child-color-patterns.php
  newspack-sacha/inc/child-color-patterns.php
  newspack-scott/inc/child-color-patterns.php
  newspack-theme/functions.php
  newspack-theme/header.php
  newspack-theme/inc/color-patterns.php
  newspack-theme/inc/customizer.php
Labels: [Status] Approved

#1503 feat: add option to change archive title format
  newspack-sacha/sass/style.scss
  newspack-theme/archive.php
  newspack-theme/functions.php
  newspack-theme/inc/customizer.php
  newspack-theme/inc/template-tags.php
  newspack-theme/sass/site/primary/_archives.scss
Labels: [Status] Approved

#1507 feat(archive template): add after_archive_post action
  newspack-theme/archive.php
Labels: [Status] Approved

#1506 Update header colour logic
  newspack-joseph/inc/child-color-patterns.php
  newspack-katharine/inc/child-color-patterns.php
  newspack-nelson/inc/child-color-patterns.php
  newspack-sacha/inc/child-color-patterns.php
  newspack-scott/inc/child-color-patterns.php
  newspack-theme/inc/color-patterns.php
Labels: [Status] Approved

#1518 Release Sep 14
  newspack-joseph/inc/child-color-patterns.php
  newspack-katharine/inc/child-color-patterns.php
  newspack-nelson/inc/child-color-patterns.php
  newspack-sacha/inc/child-color-patterns.php
  newspack-sacha/sass/style.scss
  newspack-scott/inc/child-color-patterns.php
  newspack-theme/archive.php
  newspack-theme/functions.php
  newspack-theme/inc/color-patterns.php
  newspack-theme/inc/customizer.php
  newspack-theme/inc/template-tags.php
  newspack-theme/sass/site/primary/_archives.scss
Labels: [Status] Approved

#1511 feat: add tiktok, telegram icons
  newspack-theme/classes/class-newspack-svg-icons.php
Labels: [Status] Approved, Smaller PR

#1513 Fix centred image block caption on smaller screens
  newspack-theme/sass/blocks/_blocks.scss
Labels: [Status] Approved, Smaller PR

#1514 feat: allow links in the article subtitle field
  newspack-theme/template-parts/header/entry-header.php
Labels: [Status] Approved, Smaller PR

#1516 fix: update SVG sanitization to include more HTML elements
  newspack-theme/functions.php
Labels: [Status] Approved, Smaller PR

#1517 fix: add responsive sizes for large, huge font sizes
  newspack-theme/sass/blocks/_blocks.scss
Labels: [Status] Approved, Smaller PR

#1520 Chore: update translation files
  newspack-theme/languages/de_DE.mo
  newspack-theme/languages/de_DE.po
  newspack-theme/languages/es_ES.mo
  newspack-theme/languages/es_ES.po
  newspack-theme/languages/fr_BE.mo
  newspack-theme/languages/fr_BE.po
  newspack-theme/languages/newspack-de_DE-newspack-extend-featured-image-script.json
  newspack-theme/languages/newspack-de_DE-newspack-post-meta-toggles-script.json
  newspack-theme/languages/newspack-de_DE-newspack-post-subtitle.json
  newspack-theme/languages/newspack-es_ES-newspack-extend-featured-image-script.json
  newspack-theme/languages/newspack-es_ES-newspack-post-meta-toggles-script.json
  newspack-theme/languages/newspack-es_ES-newspack-post-subtitle.json
  newspack-theme/languages/newspack-fr_BE-newspack-extend-featured-image-script.json
  newspack-theme/languages/newspack-fr_BE-newspack-post-subtitle.json
  newspack-theme/languages/newspack-pt_BR-newspack-post-meta-toggles-script.json
  newspack-theme/languages/newspack-pt_BR-newspack-post-subtitle.json
  newspack-theme/languages/newspack-pt_PT-newspack-extend-featured-image-script.json
  newspack-theme/languages/newspack-pt_PT-newspack-post-meta-toggles-script.json
  newspack-theme/languages/newspack-pt_PT-newspack-post-subtitle.json
  newspack-theme/languages/newspack-theme.pot
  newspack-theme/languages/pt_BR.mo
  newspack-theme/languages/pt_BR.po
  newspack-theme/languages/pt_PT.mo
  newspack-theme/languages/pt_PT.po
Labels: [Status] Approved

#1524 Release Sep 21
  newspack-theme/classes/class-newspack-svg-icons.php
  newspack-theme/functions.php
  newspack-theme/languages/de_DE.mo
  newspack-theme/languages/de_DE.po
  newspack-theme/languages/es_ES.mo
  newspack-theme/languages/es_ES.po
  newspack-theme/languages/fr_BE.mo
  newspack-theme/languages/fr_BE.po
  newspack-theme/languages/newspack-de_DE-newspack-extend-featured-image-script.json
  newspack-theme/languages/newspack-de_DE-newspack-post-meta-toggles-script.json
  newspack-theme/languages/newspack-de_DE-newspack-post-subtitle.json
  newspack-theme/languages/newspack-es_ES-newspack-extend-featured-image-script.json
  newspack-theme/languages/newspack-es_ES-newspack-post-meta-toggles-script.json
  newspack-theme/languages/newspack-es_ES-newspack-post-subtitle.json
  newspack-theme/languages/newspack-fr_BE-newspack-extend-featured-image-script.json
  newspack-theme/languages/newspack-fr_BE-newspack-post-subtitle.json
  newspack-theme/languages/newspack-pt_BR-newspack-post-meta-toggles-script.json
  newspack-theme/languages/newspack-pt_BR-newspack-post-subtitle.json
  newspack-theme/languages/newspack-pt_PT-newspack-extend-featured-image-script.json
  newspack-theme/languages/newspack-pt_PT-newspack-post-meta-toggles-script.json
  newspack-theme/languages/newspack-pt_PT-newspack-post-subtitle.json
  newspack-theme/languages/newspack-theme.pot
  newspack-theme/languages/pt_BR.mo
  newspack-theme/languages/pt_BR.po
  newspack-theme/languages/pt_PT.mo
  newspack-theme/languages/pt_PT.po
  newspack-theme/sass/blocks/_blocks.scss
  newspack-theme/template-parts/header/entry-header.php
Labels: [Status] Approved

#1254 Feat: Add sticky header
  newspack-joseph/sass/style.scss
  newspack-nelson/sass/style.scss
  newspack-sacha/sass/style.scss
  newspack-theme/functions.php
  newspack-theme/header.php
  newspack-theme/inc/customizer.php
  newspack-theme/inc/logo-resizer.php
  newspack-theme/inc/template-functions.php
  newspack-theme/js/src/amp-fallback.js
  newspack-theme/sass/layout/_layout.scss
  newspack-theme/sass/navigation/_menu-mobile-navigation.scss
  newspack-theme/sass/plugins/newspack-ads.scss
  newspack-theme/sass/site/header/_site-header.scss
  newspack-theme/template-parts/content/content-page.php
  newspack-theme/template-parts/content/content-single.php
  newspack-theme/template-parts/post/large-featured-image.php
Labels: [Status] Approved, Larger PR

#1529 Release Sep 28
  newspack-joseph/sass/style.scss
  newspack-nelson/sass/style.scss
  newspack-sacha/sass/style.scss
  newspack-theme/functions.php
  newspack-theme/header.php
  newspack-theme/inc/customizer.php
  newspack-theme/inc/logo-resizer.php
  newspack-theme/inc/template-functions.php
  newspack-theme/js/src/amp-fallback.js
  newspack-theme/sass/layout/_layout.scss
  newspack-theme/sass/navigation/_menu-mobile-navigation.scss
  newspack-theme/sass/plugins/newspack-ads.scss
  newspack-theme/sass/site/header/_site-header.scss
  newspack-theme/template-parts/content/content-page.php
  newspack-theme/template-parts/content/content-single.php
  newspack-theme/template-parts/post/large-featured-image.php
Labels: [Status] Approved
