Repository Automattic/newspack-theme, pull requests merged in 2021-08, with the labels that each got.

#1451 fix: correct related events header font
  newspack-theme/inc/typography.php
  newspack-theme/sass/plugins/the-events-calendar.scss
Labels: Smaller PR, The Events Calendar, [Status] Approved, [Type] Bug

#1452 Events Calendar: correct spacing in the event calendar photo shortcode
  newspack-theme/sass/plugins/the-events-calendar.scss
Labels: The Events Calendar, [Status] Approved, [Type] Bug

#1453 fix: update event calendar shortcode custom fonts
  newspack-theme/inc/typography.php
  newspack-theme/sass/plugins/the-events-calendar.scss
Labels: The Events Calendar, [Status] Approved, [Type] Bug

#1454 Events Calendar: correct spacing in event calendar map shortcode
  newspack-theme/sass/plugins/the-events-calendar.scss
Labels: The Events Calendar, [Status] Approved, [Type] Bug

#1456 Release Aug 03
  newspack-joseph/tribe-events/tribe-events.scss
  newspack-katharine/tribe-events/tribe-events.scss
  newspack-nelson/inc/child-color-patterns.php
  newspack-nelson/tribe-events/tribe-events.scss
  newspack-sacha/tribe-events/tribe-events.scss
  newspack-scott/tribe-events/tribe-events.scss
  newspack-theme/inc/color-patterns.php
  newspack-theme/inc/icon-functions.php
  newspack-theme/inc/typography.php
  newspack-theme/sass/navigation/_menu-mobile-navigation.scss
  newspack-theme/sass/plugins/the-events-calendar.scss
Labels: [Status] Approved

#1459 Default theme: fix tertiary menu appearance in slide-out sidebar
  newspack-theme/inc/color-patterns.php
  newspack-theme/sass/styles/style-default/style-default.scss
Labels: [Status] Approved

#1458 WooCommerce: Add `wc_format_content()` to shop page output
  newspack-theme/inc/woocommerce.php
Labels: [Status] Approved

#1460 fix: add space between above content widget and featured image
  newspack-theme/sass/site/primary/_posts-and-pages.scss
Labels: [Status] Approved

#1461 Embeds: remove float on screens smaller than desktop
  newspack-theme/sass/blocks/_blocks.scss
  newspack-theme/sass/mixins/_utilities.scss
Labels: [Status] Approved

#1462 Remove extra escaping from author bios
  newspack-sacha/template-parts/post/author-bio.php
  newspack-theme/template-parts/post/author-bio.php
Labels: [Status] Approved, Smaller PR

#1463 Add styles for the "zip" type input field
  newspack-theme/sass/forms/_fields.scss
Labels: [Status] Approved, Smaller PR

#1464 fix: correct spacing in Events Calendar month shortcode
  newspack-theme/sass/plugins/the-events-calendar.scss
Labels: [Type] Bug, [Status] Approved, The Events Calendar

#1465 Events Calendar: correct spacing on events calendar day shortcode
  newspack-theme/sass/plugins/the-events-calendar.scss
Labels: [Type] Bug, [Status] Approved, The Events Calendar

#1467 Events Calendar: correct spacing on events calendar shortcode week view
  newspack-theme/sass/plugins/the-events-calendar.scss
Labels: [Type] Bug, [Status] Approved, The Events Calendar

#1474 Release Aug 10
  newspack-sacha/template-parts/post/author-bio.php
  newspack-theme/inc/color-patterns.php
  newspack-theme/inc/woocommerce.php
  newspack-theme/sass/blocks/_blocks.scss
  newspack-theme/sass/forms/_fields.scss
  newspack-theme/sass/mixins/_utilities.scss
  newspack-theme/sass/plugins/the-events-calendar.scss
  newspack-theme/sass/site/primary/_posts-and-pages.scss
  newspack-theme/sass/site/secondary/_widgets.scss
  newspack-theme/sass/styles/style-default/style-default.scss
  newspack-theme/template-parts/post/author-bio.php
Labels: [Status] Needs Review

#1472 Newspack Sacha: Remove border when author & date are hidden
  newspack-sacha/sass/style.scss
  newspack-theme/sass/plugins/newspack-listings.scss
  newspack-theme/sass/style-base.scss
Labels: [Status] Approved

#1471 Hide "Cancel Reply" link when AMP is enabled
  newspack-theme/inc/template-tags.php
  newspack-theme/sass/site/primary/_comments.scss
Labels: [Status] Approved

#1477 fix: reduce padding on headings with backgrounds
  newspack-theme/sass/blocks/_blocks.scss
  newspack-theme/sass/style-editor-base.scss
Labels: [Status] Approved

#1475 Add 'above' and 'below' widget areas to the theme
  newspack-nelson/functions.php
  newspack-theme/functions.php
  newspack-theme/header.php
  newspack-theme/sass/site/secondary/_widgets.scss
Labels: [Status] Approved

#1478 fix: style categories widget block to match legacy widget
  newspack-theme/sass/blocks/_blocks.scss
Labels: [Status] Approved, Smaller PR

#1479 Make sure comments block doesn't wrongly inherit avatar sizes
  newspack-theme/sass/site/primary/_posts-and-pages.scss
Labels: [Status] Approved, Smaller PR

#1480 Make sure preformatted block doesn't get too small
  newspack-theme/sass/blocks/_blocks.scss
Labels: [Status] Approved, Smaller PR

#1482 Newspack Nelson: remove overlap when featured image is above
  newspack-nelson/sass/style.scss
Labels: [Status] Approved, Smaller PR

#1485 Release Aug 17
  newspack-nelson/functions.php
  newspack-nelson/sass/style.scss
  newspack-sacha/sass/style.scss
  newspack-theme/functions.php
  newspack-theme/header.php
  newspack-theme/inc/template-tags.php
  newspack-theme/sass/blocks/_blocks.scss
  newspack-theme/sass/plugins/newspack-listings.scss
  newspack-theme/sass/site/primary/_comments.scss
  newspack-theme/sass/site/primary/_posts-and-pages.scss
  newspack-theme/sass/site/secondary/_widgets.scss
  newspack-theme/sass/style-base.scss
  newspack-theme/sass/style-editor-base.scss
  package-lock.json
Labels: [Status] Approved

#1487 WooCommerce: Bump template version number
  newspack-theme/woocommerce/order/order-details-customer.php
Labels: [Status] Approved, Smaller PR

#1489 Add a custom login screen based on theme's settings
  newspack-theme/functions.php
  newspack-theme/inc/login-screen.php
Labels: [Status] Approved

#1488 Feat: add widget area above the footer
  newspack-joseph/sass/style.scss
  newspack-scott/sass/style.scss
  newspack-theme/footer.php
  newspack-theme/functions.php
  newspack-theme/inc/template-functions.php
  newspack-theme/sass/site/footer/_site-footer.scss
  newspack-theme/sass/site/secondary/_widgets.scss
  newspack-theme/sass/styles/style-default/style-default.scss
Labels: [Status] Approved

#1494 Feat: add support for Typenetwork.com fonts
  newspack-theme/inc/customizer.php
Labels: [Status] Approved, Smaller PR
