Repository Automattic/newspack-theme, pull requests merged in 2021-03, with the labels that each got.

#1271 WooCommerce: improvements to product page
  newspack-theme/inc/color-patterns.php
  newspack-theme/inc/typography.php
  newspack-theme/js/src/amp-fallback.js
  newspack-theme/sass/forms/_amp.scss
  newspack-theme/sass/forms/_forms.scss
  newspack-theme/sass/plugins/woocommerce.scss
  newspack-theme/sass/typography/_headings.scss
Labels: [Status] Approved

#1274 WooCommerce: improve cart appearance
  newspack-theme/sass/plugins/woocommerce.scss
Labels: [Status] Approved

#1280 Add Display and Monospace to the font fallback stack
  newspack-theme/inc/typography.php
Labels: [Status] Approved

#1278 fix: improve appearance of shop page
  newspack-theme/inc/typography.php
  newspack-theme/inc/woocommerce.php
  newspack-theme/sass/plugins/woocommerce.scss
  newspack-theme/sass/typography/_headings.scss
Labels: [Status] Approved

#1284 Release Mar 02
  newspack-theme/inc/color-patterns.php
  newspack-theme/inc/typography.php
  newspack-theme/inc/woocommerce.php
  newspack-theme/js/src/amp-fallback.js
  newspack-theme/sass/forms/_amp.scss
  newspack-theme/sass/forms/_forms.scss
  newspack-theme/sass/plugins/woocommerce.scss
  newspack-theme/sass/typography/_headings.scss
Labels: [Status] Approved

#1288 fix: add presentation role to buttons in the menu dropdowns
  newspack-theme/inc/template-functions.php
Labels: Smaller PR, [Status] Approved

#1291 feat: add category class to single post body
  newspack-theme/inc/template-functions.php
Labels: [Status] Approved

#1296 Release Mar 09
  newspack-theme/inc/template-functions.php
Labels: [Status] Approved

#1298 fix: update custom font selectors in the editor styles
  newspack-joseph/inc/child-typography.php
  newspack-joseph/sass/style-editor.scss
  newspack-joseph/sass/style.scss
  newspack-nelson/inc/child-typography.php
  newspack-sacha/inc/child-typography.php
  newspack-sacha/sass/style-editor.scss
  newspack-scott/inc/child-typography.php
  newspack-theme/inc/color-patterns.php
  newspack-theme/inc/typography.php
  newspack-theme/sass/style-editor-base.scss
Labels: [Status] Approved

#1299 fix: correct style selectors for inline text colours
  newspack-theme/inc/color-patterns.php
Labels: [Status] Approved

#1301 fix: remove spacing from first block in campaign
  newspack-theme/sass/blocks/_blocks.scss
Labels: Smaller PR, [Status] Approved

#1305 Release Mar 16
  newspack-joseph/inc/child-typography.php
  newspack-joseph/sass/style-editor.scss
  newspack-joseph/sass/style.scss
  newspack-nelson/inc/child-typography.php
  newspack-sacha/inc/child-typography.php
  newspack-sacha/sass/style-editor.scss
  newspack-scott/inc/child-typography.php
  newspack-theme/inc/color-patterns.php
  newspack-theme/inc/typography.php
  newspack-theme/sass/blocks/_blocks.scss
  newspack-theme/sass/style-editor-base.scss
  package-lock.json
Labels: [Status] Approved

#1302 feat: add option to set footer logo size
  newspack-theme/functions.php
  newspack-theme/inc/customizer.php
  newspack-theme/inc/template-functions.php
  newspack-theme/js/src/logo-customize-preview.js
  newspack-theme/sass/site/footer/_site-footer.scss
Labels: [Status] Approved

#1275 WooCommerce: Improve checkout page appearance and simplify
  newspack-theme/inc/color-patterns.php
  newspack-theme/inc/woocommerce.php
  newspack-theme/sass/plugins/woocommerce.scss
  newspack-theme/woocommerce/checkout/form-checkout.php
Labels: [Status] Approved

#1307 Add web stories embed support in theme
  newspack-theme/functions.php
  newspack-theme/inc/web-stories.php
Labels: [Status] Needs Review

#1311 Release Mar 23
  newspack-theme/functions.php
  newspack-theme/inc/color-patterns.php
  newspack-theme/inc/customizer.php
  newspack-theme/inc/template-functions.php
  newspack-theme/inc/web-stories.php
  newspack-theme/inc/woocommerce.php
  newspack-theme/js/src/logo-customize-preview.js
  newspack-theme/sass/plugins/woocommerce.scss
  newspack-theme/sass/site/footer/_site-footer.scss
  newspack-theme/woocommerce/checkout/form-checkout.php
Labels: [Status] Approved

#1314 fix: remove filtering of WooCommerce checkout fields
  newspack-theme/inc/woocommerce.php
Labels: [Priority] High, [Status] Approved, [Type] Bug

#1315 Hotfix release Mar 24
  newspack-theme/inc/woocommerce.php
Labels: [Status] Approved

#1313 feat: add support for custom excerpts on pages
  newspack-theme/functions.php
Labels: [Status] Approved, [Status] Needs Design Review

#1308 feat: add post template support for Newspack Listings post types
  newspack-theme/single-feature.php
  newspack-theme/single-wide.php
  newspack-theme/template-parts/post/author-bio.php
Labels: [Status] Approved, [Type] Enhancement
