Repository Automattic/newspack-theme, pull requests merged in 2021-11, with the labels that each got.

#1566 fix: make sure mobile CTA is always clickable
  newspack-theme/sass/navigation/_menu-mobile-navigation.scss
Labels: [Status] Approved, Smaller PR

#1569 Release Nov 02
  newspack-katharine/sass/variables-style/_fonts.scss
  newspack-nelson/sass/variables-style/_fonts.scss
  newspack-sacha/sass/variables-style/_fonts.scss
  newspack-scott/sass/variables-style/_fonts.scss
  newspack-theme/functions.php
  newspack-theme/inc/customizer.php
  newspack-theme/inc/template-functions.php
  newspack-theme/inc/typography.php
  newspack-theme/inc/woocommerce.php
  newspack-theme/js/src/post-summary/SummaryEditor.js
  newspack-theme/js/src/post-summary/SummaryTitleEditor.js
  newspack-theme/js/src/post-summary/index.js
  newspack-theme/js/src/post-summary/utils.js
  newspack-theme/sass/navigation/_menu-mobile-navigation.scss
  newspack-theme/sass/site/primary/_posts-and-pages.scss
Labels: [Status] Approved

#1563 Prevent centred logo from getting cut off with Sticky Header
  newspack-theme/inc/logo-resizer.php
  newspack-theme/sass/site/header/_site-header.scss
Labels: [Status] Approved

#1571 fix: make sure the featured image description is not output
  newspack-theme/inc/template-tags.php
Labels: [Status] Approved, Smaller PR

#1573 Release Nov 09
  newspack-theme/inc/logo-resizer.php
  newspack-theme/inc/template-tags.php
  newspack-theme/sass/site/header/_site-header.scss
Labels: [Status] Approved

#1575 fix: sticky ad on amp plus
  newspack-theme/js/src/amp-fallback.js
  newspack-theme/js/src/amp-plus.js
  newspack-theme/sass/plugins/newspack-ads.scss
Labels: [Status] Approved, Next release

#1582 feat: add social icon for Patreon
  newspack-theme/classes/class-newspack-svg-icons.php
Labels: [Status] Approved

#1583 fix: add wptexturize to the article subtitle
  newspack-theme/template-parts/header/entry-header.php
Labels: [Status] Approved, Smaller PR

#1584 Add description to the default templates, featured image settings
  newspack-theme/inc/customizer.php
Labels: [Status] Approved

#1585 fix: make the imprint open in a new tab
  newspack-theme/footer.php
Labels: [Status] Approved

#1579 Update es_ES.po
  newspack-theme/languages/es_ES.po
Labels: [Status] Needs Changes or Feeback

#1589 Release Nov 18
  CHANGELOG.md
  newspack-joseph/sass/style.scss
  newspack-katharine/sass/style.scss
  newspack-nelson/sass/style.scss
  newspack-sacha/sass/style.scss
  newspack-scott/sass/style.scss
  newspack-theme/js/src/amp-fallback.js
  newspack-theme/js/src/amp-plus.js
  newspack-theme/sass/plugins/newspack-ads.scss
  newspack-theme/sass/style.scss
  package-lock.json
  package.json
Labels: [Status] Approved

#1578 fix: improve logo sizing behavior with sticky header
  newspack-theme/inc/logo-resizer.php
Labels: [Status] Approved

#1588 fix: update Spanish .mo file for updated translations
  newspack-theme/languages/es_ES.mo
  newspack-theme/languages/es_ES.po
Labels: [Status] Approved

#1593 fix: if no logo, show site title with simplified header
  newspack-theme/sass/site/header/_site-header.scss
Labels: [Status] Approved

#1599 Release Nov 30
  CHANGELOG.md
  newspack-joseph/sass/style.scss
  newspack-katharine/sass/style.scss
  newspack-nelson/sass/style.scss
  newspack-sacha/sass/style.scss
  newspack-scott/sass/style.scss
  newspack-theme/classes/class-newspack-svg-icons.php
  newspack-theme/footer.php
  newspack-theme/inc/customizer.php
  newspack-theme/languages/es_ES.po
  newspack-theme/sass/style.scss
  newspack-theme/template-parts/header/entry-header.php
  package-lock.json
  package.json
Labels: [Status] Approved
