Repository Automattic/newspack-theme, pull requests merged in 2021-01, with the labels that each got.

#1191 feat: add styles for the block 'read more' links
  newspack-theme/inc/color-patterns.php
  newspack-theme/sass/blocks/_blocks.scss
  newspack-theme/sass/site/primary/_posts-and-pages.scss
  newspack-theme/sass/style-editor-base.scss
Labels: [Status] Approved

#1194 Pullquote Block: remove hyphenation styles from pullquote blocks
  newspack-theme/sass/typography/_headings.scss
Labels: [Status] Approved

#1195 Pullquote Block: fix font size with solid backgrounds
  newspack-katharine/sass/style.scss
  newspack-nelson/sass/style.scss
  newspack-sacha/sass/style.scss
  newspack-scott/sass/style.scss
  newspack-theme/sass/blocks/_blocks.scss
Labels: [Status] Approved

#1196 Pullquote Block: Correct preview in editor
  newspack-joseph/sass/style-editor.scss
  newspack-katharine/sass/style-editor.scss
  newspack-nelson/sass/style-editor.scss
  newspack-sacha/sass/style-editor.scss
  newspack-scott/inc/child-color-patterns.php
  newspack-scott/inc/child-typography.php
  newspack-scott/sass/style-editor.scss
  newspack-theme/sass/style-editor-base.scss
Labels: [Status] Approved

#1197 Print styles: Make sure header elements, campaigns are hidden
  newspack-theme/sass/print.scss
Labels: [Pri] Low, [Status] Approved

#1204 Release Jan 12
  newspack-joseph/sass/style-editor.scss
  newspack-katharine/sass/style-editor.scss
  newspack-katharine/sass/style.scss
  newspack-nelson/sass/style-editor.scss
  newspack-nelson/sass/style.scss
  newspack-sacha/sass/style-editor.scss
  newspack-sacha/sass/style.scss
  newspack-scott/inc/child-color-patterns.php
  newspack-scott/inc/child-typography.php
  newspack-scott/sass/style-editor.scss
  newspack-scott/sass/style.scss
  newspack-theme/functions.php
  newspack-theme/inc/color-patterns.php
  newspack-theme/inc/template-functions.php
  newspack-theme/inc/template-tags.php
  newspack-theme/js/src/post-date-updated.js
  newspack-theme/languages/fr_BE.mo
  newspack-theme/languages/fr_BE.po
  newspack-theme/sass/blocks/_blocks.scss
  newspack-theme/sass/print.scss
  newspack-theme/sass/site/primary/_posts-and-pages.scss
  newspack-theme/sass/style-editor-base.scss
  newspack-theme/sass/typography/_headings.scss
  package-lock.json
Labels: [Status] Approved

#1205 Comments: Add optional space for a comment policy
  newspack-theme/inc/customizer.php
  newspack-theme/inc/template-tags.php
  newspack-theme/sass/site/primary/_comments.scss
Labels: Needs documentation, [Status] Approved

#1208 feat: add a sticky ad slot to the Advertising wizard
  newspack-theme/js/src/amp-fallback.js
  newspack-theme/sass/plugins/newspack-ads.scss
Labels: [Status] Approved

#1190 feat: add fr-BR JSON files for the editor
  newspack-theme/languages/newspack-fr_BE-newspack-extend-featured-image-script.json
  newspack-theme/languages/newspack-fr_BE-newspack-post-subtitle.json
Labels: [Status] Approved

#1206 Single Articles: Add previous/next links
  newspack-katharine/sass/style.scss
  newspack-nelson/sass/style.scss
  newspack-theme/inc/customizer.php
  newspack-theme/inc/template-tags.php
  newspack-theme/inc/typography.php
  newspack-theme/sass/site/primary/_posts-and-pages.scss
  newspack-theme/sass/typography/_headings.scss
  newspack-theme/single-feature.php
  newspack-theme/single-wide.php
  newspack-theme/single.php
Labels: Needs documentation, [Status] Approved

#1193 Pullquote Block: Make sure italics are working
  newspack-joseph/sass/style-editor.scss
  newspack-joseph/sass/style.scss
  newspack-katharine/sass/style-editor.scss
  newspack-katharine/sass/style.scss
  newspack-nelson/sass/style-editor.scss
  newspack-nelson/sass/style.scss
Labels: [Status] Approved

#1217 Release Jan 19
  newspack-joseph/sass/style-editor.scss
  newspack-joseph/sass/style.scss
  newspack-katharine/sass/style-editor.scss
  newspack-katharine/sass/style.scss
  newspack-nelson/sass/style-editor.scss
  newspack-nelson/sass/style.scss
  newspack-theme/inc/customizer.php
  newspack-theme/inc/template-tags.php
  newspack-theme/inc/typography.php
  newspack-theme/js/src/amp-fallback.js
  newspack-theme/languages/newspack-fr_BE-newspack-extend-featured-image-script.json
  newspack-theme/languages/newspack-fr_BE-newspack-post-subtitle.json
  newspack-theme/sass/plugins/newspack-ads.scss
  newspack-theme/sass/site/primary/_comments.scss
  newspack-theme/sass/site/primary/_posts-and-pages.scss
  newspack-theme/sass/typography/_headings.scss
  newspack-theme/single-feature.php
  newspack-theme/single-wide.php
  newspack-theme/single.php
Labels: [Status] Approved

#1200 Add option to hide page title
  newspack-nelson/sass/style.scss
  newspack-theme/functions.php
  newspack-theme/inc/template-functions.php
  newspack-theme/inc/template-tags.php
  newspack-theme/js/src/post-date-updated.js
  newspack-theme/js/src/post-meta-toggles.js
  newspack-theme/sass/site/primary/_posts-and-pages.scss
  newspack-theme/template-parts/header/entry-header.php
Labels: Needs documentation, [Status] Approved

#1222 Archives: Add option to change archive layout
  newspack-theme/archive.php
  newspack-theme/functions.php
  newspack-theme/inc/customizer.php
  newspack-theme/inc/template-functions.php
  newspack-theme/inc/template-tags.php
  newspack-theme/sass/layout/_layout.scss
  newspack-theme/template-parts/content/content-archive.php
  newspack-theme/template-parts/content/content-excerpt.php
Labels: Needs documentation, [Status] Approved

#1223 Archives: add option to change first archive layout
  newspack-theme/archive.php
  newspack-theme/inc/customizer.php
  newspack-theme/inc/template-functions.php
  newspack-theme/sass/site/primary/_archives.scss
  newspack-theme/sass/typography/_headings.scss
Labels: Needs documentation, [Status] Approved

#1211 Button Block: Fix issue where primary background colour not applied
  newspack-theme/inc/color-patterns.php
Labels: Smaller PR, [Status] Approved

#1224 Archives: make hidden categories on archives more flexible
  newspack-joseph/sass/style.scss
  newspack-katharine/sass/style.scss
  newspack-sacha/sass/style.scss
  newspack-scott/sass/style.scss
  newspack-theme/sass/plugins/newspack-sponsors.scss
  newspack-theme/sass/site/primary/_archives.scss
  newspack-theme/sass/styles/style-default/style-default.scss
  newspack-theme/template-parts/content/content-archive.php
  newspack-theme/template-parts/content/content-excerpt.php
Labels: [Status] Approved

#1226 Release Jan 28
  newspack-joseph/sass/style.scss
  newspack-katharine/sass/style.scss
  newspack-nelson/sass/style.scss
  newspack-sacha/sass/style.scss
  newspack-scott/sass/style.scss
  newspack-theme/archive.php
  newspack-theme/functions.php
  newspack-theme/inc/color-patterns.php
  newspack-theme/inc/customizer.php
  newspack-theme/inc/template-functions.php
  newspack-theme/inc/template-tags.php
  newspack-theme/js/src/post-date-updated.js
  newspack-theme/js/src/post-meta-toggles.js
  newspack-theme/sass/layout/_layout.scss
  newspack-theme/sass/plugins/newspack-sponsors.scss
  newspack-theme/sass/site/primary/_archives.scss
  newspack-theme/sass/site/primary/_posts-and-pages.scss
  newspack-theme/sass/styles/style-default/style-default.scss
  newspack-theme/sass/typography/_headings.scss
  newspack-theme/template-parts/content/content-archive.php
  newspack-theme/template-parts/content/content-excerpt.php
  newspack-theme/template-parts/header/entry-header.php
Labels: [Status] Approved

#1227 fix: add check for meta and post types before loading toggles
  newspack-theme/js/src/post-meta-toggles.js
Labels: [Status] Approved

#1229 Release Jan 29
  newspack-theme/js/src/post-meta-toggles.js
Labels: [Status] Approved
