Repository Automattic/newspack-theme, pull requests merged in 2021-07, with the labels that each got.

#1401 Block Widgets: Correct font previews
  newspack-theme/inc/typography.php
Labels: [Status] Approved

#1398 Donate Block: improve donate block appearance for WP 5.8
  newspack-theme/inc/color-patterns.php
  newspack-theme/sass/blocks/_blocks.scss
Labels: [Status] Approved

#1382 fix: figcaption rendering bug in Safari
  newspack-theme/sass/blocks/_blocks.scss
  newspack-theme/sass/media/_captions.scss
Labels: [Status] Approved, [Type] Bug

#1402 fix: ads media queries
  newspack-theme/functions.php
Labels: [Status] Approved

#1405 Release Jul 06
  newspack-theme/functions.php
  newspack-theme/inc/color-patterns.php
  newspack-theme/inc/typography.php
  newspack-theme/js/src/amp-fallback.js
  newspack-theme/sass/blocks/_blocks.scss
  newspack-theme/sass/media/_captions.scss
Labels: [Status] Approved

#1368 feat: enable jetpack share buttons on pages, too
  newspack-theme/functions.php
  newspack-theme/js/src/post-meta-toggles.js
  newspack-theme/sass/style-editor-overrides.scss
  newspack-theme/template-parts/header/entry-header.php
Labels: [Status] Approved, [Type] Feature request

#1410 Add option to change the footer layout
  newspack-theme/inc/customizer.php
  newspack-theme/inc/template-functions.php
  newspack-theme/sass/site/footer/_site-footer.scss
Labels: [Status] Approved

#1407 Homepage Posts Block: Style adjustments for widget block areas
  newspack-joseph/sass/style.scss
  newspack-katharine/inc/child-color-patterns.php
  newspack-katharine/sass/style.scss
  newspack-nelson/sass/style.scss
  newspack-sacha/sass/style.scss
  newspack-sacha/template-parts/post/author-bio.php
  newspack-scott/inc/child-color-patterns.php
  newspack-scott/sass/style.scss
  newspack-theme/inc/color-patterns.php
  newspack-theme/sass/blocks/_blocks.scss
  newspack-theme/sass/navigation/_menu-mobile-navigation.scss
  newspack-theme/sass/site/footer/_site-footer.scss
  newspack-theme/sass/site/secondary/_widgets.scss
  newspack-theme/template-parts/post/author-bio.php
Labels: Larger PR, [Status] Approved, [Status] Needs Changes or Feeback

#1413 Release Jul 13
  newspack-joseph/sass/style.scss
  newspack-katharine/inc/child-color-patterns.php
  newspack-katharine/sass/style.scss
  newspack-nelson/sass/style.scss
  newspack-sacha/sass/style.scss
  newspack-sacha/template-parts/post/author-bio.php
  newspack-scott/inc/child-color-patterns.php
  newspack-scott/sass/style.scss
  newspack-theme/functions.php
  newspack-theme/inc/color-patterns.php
  newspack-theme/inc/customizer.php
  newspack-theme/inc/template-functions.php
  newspack-theme/js/src/post-meta-toggles.js
  newspack-theme/sass/blocks/_blocks.scss
  newspack-theme/sass/navigation/_menu-mobile-navigation.scss
  newspack-theme/sass/site/footer/_site-footer.scss
  newspack-theme/sass/site/secondary/_widgets.scss
  newspack-theme/sass/style-editor-overrides.scss
  newspack-theme/template-parts/header/entry-header.php
  newspack-theme/template-parts/post/author-bio.php
Labels: [Status] Approved

#1414 Query Block: Update styles to match theme, pick up custom fonts
  newspack-theme/inc/typography.php
  newspack-theme/sass/navigation/_next-previous.scss
  newspack-theme/sass/style-editor-base.scss
  newspack-theme/sass/typography/_headings.scss
Labels: [Status] Approved

#1415 Widgets: Remove link from Slide-out Sidebar description
  newspack-theme/functions.php
Labels: Smaller PR, [Status] Approved

#1416 Add support for custom spacing
  newspack-theme/functions.php
Labels: Smaller PR, [Status] Approved

#1411 Post Carousel: Adjust styles when used in certain widget areas
  newspack-theme/sass/blocks/_blocks.scss
  newspack-theme/sass/navigation/_menu-mobile-navigation.scss
  newspack-theme/sass/site/secondary/_widgets.scss
Labels: [Status] Approved

#1421 Release Jul 19
  newspack-theme/functions.php
  newspack-theme/inc/typography.php
  newspack-theme/sass/blocks/_blocks.scss
  newspack-theme/sass/navigation/_menu-mobile-navigation.scss
  newspack-theme/sass/navigation/_next-previous.scss
  newspack-theme/sass/site/secondary/_widgets.scss
  newspack-theme/sass/style-editor-base.scss
  newspack-theme/sass/typography/_headings.scss
Labels: [Status] Approved

#1422 Author Profile Block: reduce font sizing slightly in slide-out sidebars
  newspack-theme/sass/blocks/_blocks.scss
  newspack-theme/sass/navigation/_menu-mobile-navigation.scss
Labels: [Status] Approved

#1423 fix: add simple styles for the login block
  newspack-theme/inc/typography.php
  newspack-theme/sass/blocks/_blocks.scss
  newspack-theme/sass/style-editor-base.scss
  newspack-theme/sass/typography/_headings.scss
Labels: [Status] Approved

#1425 Search block: improve appearance
  newspack-theme/inc/color-patterns.php
  newspack-theme/inc/typography.php
  newspack-theme/sass/blocks/_blocks.scss
  newspack-theme/sass/forms/_buttons.scss
  newspack-theme/sass/style-editor-base.scss
Labels: [Status] Approved

#1424 fix: replace widget spacing for standard content spacing for blocks
  newspack-theme/sass/navigation/_menu-mobile-navigation.scss
  newspack-theme/sass/site/secondary/_widgets.scss
Labels: [Status] Approved

#1427 fix: make sure event archives don't pick up regular archive styles
  newspack-theme/inc/template-functions.php
Labels: [Status] Approved

#1426 Button block: fix outline style padding and colour
  newspack-theme/inc/color-patterns.php
  newspack-theme/sass/blocks/_blocks.scss
Labels: [Status] Approved

#1435 Get Custom Fonts loading with the Events Calendar new views
  newspack-joseph/tribe-events/tribe-events.scss
  newspack-katharine/tribe-events/tribe-events.scss
  newspack-nelson/tribe-events/tribe-events.scss
  newspack-sacha/tribe-events/tribe-events.scss
  newspack-scott/tribe-events/tribe-events.scss
  newspack-theme/inc/typography.php
  newspack-theme/sass/plugins/the-events-calendar.scss
  newspack-theme/tribe-events/tribe-events.scss
  scripts/compile-scss.js
Labels: [Status] Approved

#1440 Re-add default header styles in editor
  newspack-theme/sass/style-editor-base.scss
Labels: Smaller PR, [Status] Approved

#1441 Events Calendar: Make sure archive styles aren't breaking photo view
  newspack-theme/sass/plugins/the-events-calendar.scss
Labels: [Status] Approved

#1442 Add Events template to theme, and single event sidebar option
  newspack-theme/functions.php
  newspack-theme/inc/the-events-calendar.php
  newspack-theme/sass/plugins/the-events-calendar.scss
  newspack-theme/tribe/events/v2/default-template.php
Labels: [Status] Needs Review

#1446 Release Jul 27
  newspack-joseph/tribe-events/tribe-events.scss
  newspack-katharine/tribe-events/tribe-events.scss
  newspack-nelson/tribe-events/tribe-events.scss
  newspack-sacha/tribe-events/tribe-events.scss
  newspack-scott/tribe-events/tribe-events.scss
  newspack-theme/functions.php
  newspack-theme/inc/color-patterns.php
  newspack-theme/inc/template-functions.php
  newspack-theme/inc/the-events-calendar.php
  newspack-theme/inc/typography.php
  newspack-theme/sass/blocks/_blocks.scss
  newspack-theme/sass/forms/_buttons.scss
  newspack-theme/sass/navigation/_menu-mobile-navigation.scss
  newspack-theme/sass/plugins/the-events-calendar.scss
  newspack-theme/sass/site/secondary/_widgets.scss
  newspack-theme/sass/style-editor-base.scss
  newspack-theme/sass/typography/_headings.scss
  newspack-theme/tribe-events/tribe-events.scss
  newspack-theme/tribe/events/v2/default-template.php
  scripts/compile-scss.js
Labels: [Status] Approved

#1443 Make sure mobile CTA doesn't pick up Events Calendar: Community Events styles
  newspack-joseph/tribe-events/tribe-events.scss
  newspack-katharine/tribe-events/tribe-events.scss
  newspack-nelson/tribe-events/tribe-events.scss
  newspack-sacha/tribe-events/tribe-events.scss
  newspack-scott/tribe-events/tribe-events.scss
  newspack-theme/inc/color-patterns.php
  newspack-theme/inc/typography.php
  newspack-theme/sass/navigation/_menu-mobile-navigation.scss
  newspack-theme/sass/plugins/the-events-calendar.scss
Labels: [Status] Approved

#1444 Newspack Nelson: Add overlap styles for the Events Calendar
  newspack-nelson/inc/child-color-patterns.php
  newspack-nelson/tribe-events/tribe-events.scss
Labels: [Status] Approved

#1396 feat: customizing svg icon for social media with a hook
  newspack-theme/inc/icon-functions.php
Labels: [Status] Needs Changes or Feeback

#1449 fix: override event link styles on related posts
  newspack-theme/sass/plugins/the-events-calendar.scss
Labels: Smaller PR, [Status] Approved
