Repository Automattic/newspack-theme, pull requests merged in 2021-06, with the labels that each got.

#1359 feat: support Newspack Listings hide publish date option
  newspack-theme/inc/template-tags.php
Labels: [Status] Approved, [Type] Enhancement

#1365 chore: update build-related packages
  composer.json
  composer.lock
  package-lock.json
  package.json
Labels: [Status] Approved, [Type] Enhancement

#1367 fix: es_ES translation for "time ago" string
  newspack-theme/languages/es_ES.mo
  newspack-theme/languages/es_ES.po
Labels: [Status] Approved

#1366 fix: style of sponsor logo in footer blurb if no link
  newspack-theme/inc/newspack-sponsors.php
Labels: [Status] Approved, [Type] Bug

#1358 Fix: Web Stories default customizer options display
  newspack-theme/functions.php
Labels: [Status] Approved

#1377 Release Jun 22
  composer.json
  composer.lock
  newspack-theme/functions.php
  newspack-theme/inc/newspack-sponsors.php
  newspack-theme/languages/es_ES.mo
  newspack-theme/languages/es_ES.po
  package-lock.json
  package.json
Labels: [Status] Approved

#1378 Make sure mobile menu displays when it only contains widgets
  newspack-theme/inc/template-tags.php
Labels: [Status] Approved

#1385 Newspack Sacha: correct alignment for sponsor bio in Newspack Sacha
  newspack-sacha/sass/style.scss
Labels: Smaller PR, [Status] Approved

#1384 Newspack Sacha: make accent header styles more specific in Newspack Sacha
  newspack-sacha/sass/style.scss
Labels: Smaller PR, [Status] Approved

#1388 Release Jun 29
  newspack-sacha/sass/style.scss
  newspack-theme/inc/template-tags.php
Labels: [Status] Approved

#1390 WordPress 5.8: Prevent white screen and errors on Widget Screen
  newspack-theme/functions.php
  newspack-theme/js/src/amp-fallback.js
Labels: [Status] Approved
