Repository Automattic/newspack-theme, pull requests merged in 2022-11, with the labels that each got.

#1966 fix: usage of filter for post author footer bio name
  newspack-sacha/template-parts/post/author-bio.php
  newspack-theme/inc/trust-indicators.php
  newspack-theme/template-parts/post/author-bio.php
Labels: [Status] Needs Review

#1985 chore: update Newspack website URL in the themes' style.css headers
  newspack-joseph/sass/theme-description.scss
  newspack-katharine/sass/theme-description.scss
  newspack-nelson/sass/theme-description.scss
  newspack-sacha/sass/theme-description.scss
  newspack-scott/sass/theme-description.scss
  newspack-theme/sass/theme-description.scss
Labels: [Status] Approved

#1983 Update primary domain
  newspack-theme/footer.php
  newspack-theme/languages/de_DE.po
  newspack-theme/languages/es_ES.po
  newspack-theme/languages/fr_BE.po
  newspack-theme/languages/newspack-theme.pot
  newspack-theme/languages/pl_PL.po
  newspack-theme/languages/pt_BR.po
  newspack-theme/languages/pt_PT.po
Labels: [Status] Approved, Design

#1988 fix: woocommerce CSS loading condition
  newspack-theme/inc/woocommerce.php
Labels: [Status] Approved, Performance
