Repository Automattic/newspack-theme, pull requests merged in 2022-09, with the labels that each got.

#1922 feat: ensure footer stays at the bottom of the screen
  newspack-theme/sass/layout/_layout.scss
Labels: [Status] Approved, [Status] Needs Design Review

#1927 Release Sep 14
  CHANGELOG.md
  composer.lock
  newspack-joseph/sass/theme-description.scss
  newspack-katharine/sass/theme-description.scss
  newspack-nelson/sass/theme-description.scss
  newspack-sacha/sass/theme-description.scss
  newspack-scott/sass/theme-description.scss
  newspack-theme/sass/blocks/_patterns.scss
  newspack-theme/sass/print.scss
  newspack-theme/sass/theme-description.scss
  package-lock.json
  package.json
Labels: [Status] Approved

#1924 Footer: add option to toggle off branding
  newspack-theme/footer.php
  newspack-theme/inc/customizer.php
  newspack-theme/sass/site/footer/_site-footer.scss
  newspack-theme/template-parts/footer/footer-branding.php
Labels: [Status] Approved, Needs documentation

#1926 fix: organic-profile-block editor handling
  newspack-theme/sass/style-editor-base.scss
Labels: [Status] Approved

#1935 Print styles: fix issue with ad background colours, and improve styles hiding ads
  newspack-theme/sass/print.scss
Labels: [Status] Approved

#1934 test: Upgrade to php 8
  composer.json
  composer.lock
Labels: [Status] Approved
