Repository Automattic/newspack-theme, pull requests merged in 2022-05, with the labels that each got.

#1777 fix: correct author alignment when date is hidden
  newspack-sacha/sass/style.scss
  newspack-theme/sass/site/primary/_posts-and-pages.scss
Labels: [Status] Approved, Smaller PR

#1791 Release May 02
  CHANGELOG.md
  composer.lock
  newspack-joseph/sass/style.scss
  newspack-katharine/sass/style.scss
  newspack-nelson/sass/style.scss
  newspack-sacha/sass/style.scss
  newspack-scott/sass/style.scss
  newspack-theme/inc/jetpack.php
  newspack-theme/sass/blocks/_blocks.scss
  newspack-theme/sass/blocks/_patterns.scss
  newspack-theme/sass/media/_captions.scss
  newspack-theme/sass/style-editor-base.scss
  newspack-theme/sass/style-editor-overrides.scss
  newspack-theme/sass/style.scss
  newspack-theme/sass/styles/style-default/style-default.scss
  package-lock.json
  package.json
Labels: [Status] Approved

#1792 fix(sponsors): ensure sponsor bios appear above Related Posts module
  newspack-theme/inc/newspack-sponsors.php
  newspack-theme/template-parts/content/content-single.php
Labels: [Type] Enhancement, [Status] Approved

#1798 Separator Block: update colour styles in the editor for WordPress 6.0
  newspack-theme/sass/style-editor-base.scss
Labels: [Status] Approved

#1786 fix: update single post footer print styles
  newspack-theme/sass/print.scss
Labels: [Status] Approved, Smaller PR

#1804 Release May 17
  CHANGELOG.md
  newspack-joseph/sass/style.scss
  newspack-katharine/sass/style.scss
  newspack-nelson/sass/style.scss
  newspack-sacha/sass/style.scss
  newspack-scott/sass/style.scss
  newspack-theme/inc/newspack-sponsors.php
  newspack-theme/sass/blocks/_blocks.scss
  newspack-theme/sass/site/primary/_posts-and-pages.scss
  newspack-theme/sass/style-editor-base.scss
  newspack-theme/sass/style.scss
  newspack-theme/template-parts/content/content-single.php
  package-lock.json
  package.json
Labels: [Status] Approved

#1801 Columns Block: remove custom column block styles
  newspack-theme/sass/blocks/_blocks.scss
  newspack-theme/sass/blocks/_patterns.scss
  newspack-theme/sass/style-editor-base.scss
Labels: [Status] Approved

#1817 fix: columns block: update styles for WP 6.0
  newspack-theme/sass/blocks/_blocks.scss
  newspack-theme/sass/blocks/_patterns.scss
  newspack-theme/sass/style-editor-base.scss
Labels: [Status] Approved

#1806 Trust Indicators: Add the author title to the author bio as well
  newspack-joseph/sass/style.scss
  newspack-sacha/template-parts/post/author-bio.php
  newspack-theme/inc/trust-indicators.php
  newspack-theme/sass/site/primary/_posts-and-pages.scss
  newspack-theme/template-parts/post/author-bio.php
Labels: [Status] Approved

#1816 fix: make third level headings a unique size on mobile
  newspack-theme/sass/style-editor-base.scss
  newspack-theme/sass/typography/_headings.scss
Labels: [Status] Approved

#1818 Add custom style to subscribe pattern 10
  newspack-theme/sass/blocks/_patterns.scss
  newspack-theme/sass/mixins/_mixins-master.scss
  newspack-theme/sass/style-editor-base.scss
Labels: [Status] Approved

#1822 Release May 30
  CHANGELOG.md
  newspack-joseph/sass/style.scss
  newspack-katharine/sass/style.scss
  newspack-nelson/sass/style.scss
  newspack-sacha/sass/style.scss
  newspack-scott/sass/style.scss
  newspack-theme/header.php
  newspack-theme/sass/print.scss
  newspack-theme/sass/style.scss
  package-lock.json
  package.json
Labels: [Status] Approved

#1810 Remove support for the Aside post format support
  newspack-theme/functions.php
  newspack-theme/sass/blocks/_blocks.scss
  newspack-theme/sass/site/primary/_archives.scss
  newspack-theme/sass/site/primary/_posts-and-pages.scss
  newspack-theme/sass/style-editor-base.scss
Labels: [Status] Approved
