Repository Automattic/newspack-theme, pull requests merged in 2022-02, with the labels that each got.

#1695 Add more specific styles for the MailChimp button
  newspack-theme/inc/typography.php
  newspack-theme/sass/blocks/_blocks.scss
Labels: [Status] Approved

#1696 Make sure full-width group block contents can't touch edges
  newspack-theme/sass/blocks/_blocks.scss
  newspack-theme/sass/style-editor-overrides.scss
Labels: [Status] Approved

#1699 feat: full-width scaip ad
  newspack-theme/inc/color-patterns.php
  newspack-theme/sass/blocks/_blocks.scss
Labels: [Status] Approved, [Status] Needs Design Review

#1705 Release Feb 08
  .circleci/config.yml
  .eslintrc.js
  .stylelintrc
  CHANGELOG.md
  babel.config.js
  composer.json
  newspack-joseph/sass/style.scss
  newspack-katharine/sass/style.scss
  newspack-nelson/sass/style.scss
  newspack-sacha/sass/style.scss
  newspack-scott/sass/style.scss
  newspack-theme/inc/template-tags.php
  newspack-theme/js/src/amp-fallback-newspack-sponsors.js
  newspack-theme/js/src/amp-fallback.js
  newspack-theme/js/src/customize-controls.js
  newspack-theme/js/src/customize-preview.js
  newspack-theme/js/src/logo-customize-controls.js
  newspack-theme/js/src/logo-customize-preview.js
  newspack-theme/js/src/post-subtitle/utils.js
  newspack-theme/sass/plugins/woocommerce.scss
  newspack-theme/sass/style.scss
  package-lock.json
  package.json
  webpack.config.js
Labels: [Status] Approved

#1712 fix: make sure featured image credits show up for all image placements
  newspack-theme/inc/template-tags.php
  newspack-theme/template-parts/post/large-featured-image.php
Labels: [Status] Approved

#1678 fix: extend/duplicate .widget-title and .accent-header styles (#1470)
  newspack-joseph/inc/child-color-patterns.php
  newspack-joseph/inc/child-typography.php
  newspack-joseph/sass/style.scss
  newspack-katharine/inc/child-color-patterns.php
  newspack-katharine/inc/child-typography.php
  newspack-katharine/sass/style.scss
  newspack-nelson/inc/child-color-patterns.php
  newspack-nelson/inc/child-typography.php
  newspack-nelson/sass/style.scss
  newspack-sacha/inc/child-color-patterns.php
  newspack-sacha/inc/child-typography.php
  newspack-sacha/sass/style.scss
  newspack-scott/inc/child-color-patterns.php
  newspack-scott/inc/child-typography.php
  newspack-scott/sass/style.scss
  newspack-theme/inc/color-patterns.php
  newspack-theme/inc/typography.php
  newspack-theme/sass/navigation/_menu-mobile-navigation.scss
  newspack-theme/sass/site/footer/_site-footer.scss
  newspack-theme/sass/site/secondary/_widgets.scss
  newspack-theme/sass/styles/style-default/style-default.scss
  newspack-theme/sass/typography/_headings.scss
Labels: [Status] Needs Changes or Feeback

#1715 Release Feb 22
  .nvmrc
  CHANGELOG.md
  composer.lock
  newspack-joseph/sass/style.scss
  newspack-katharine/sass/style.scss
  newspack-nelson/sass/style.scss
  newspack-sacha/sass/style.scss
  newspack-scott/sass/style.scss
  newspack-theme/inc/color-patterns.php
  newspack-theme/inc/logo-resizer.php
  newspack-theme/inc/typography.php
  newspack-theme/sass/blocks/_blocks.scss
  newspack-theme/sass/plugins/the-events-calendar.scss
  newspack-theme/sass/site/footer/_site-footer.scss
  newspack-theme/sass/site/header/_site-header.scss
  newspack-theme/sass/site/secondary/_widgets.scss
  newspack-theme/sass/style-editor-overrides.scss
  newspack-theme/sass/style.scss
  newspack-theme/sass/styles/style-default/style-default.scss
  package-lock.json
  package.json
Labels: [Status] Needs Review

#1717 fix: remove ads custom media queries
  newspack-theme/functions.php
Labels: [Status] Approved
