Repository Automattic/newspack-theme, pull requests merged in 2022-03, with the labels that each got.

#1726 Release Mar 08
  CHANGELOG.md
  newspack-joseph/inc/child-color-patterns.php
  newspack-joseph/inc/child-typography.php
  newspack-joseph/sass/style.scss
  newspack-katharine/inc/child-color-patterns.php
  newspack-katharine/inc/child-typography.php
  newspack-katharine/sass/style.scss
  newspack-nelson/inc/child-color-patterns.php
  newspack-nelson/inc/child-typography.php
  newspack-nelson/sass/style.scss
  newspack-sacha/inc/child-color-patterns.php
  newspack-sacha/inc/child-typography.php
  newspack-sacha/sass/style.scss
  newspack-scott/inc/child-color-patterns.php
  newspack-scott/inc/child-typography.php
  newspack-scott/sass/style.scss
  newspack-theme/inc/color-patterns.php
  newspack-theme/inc/template-tags.php
  newspack-theme/inc/typography.php
  newspack-theme/sass/blocks/_blocks.scss
  newspack-theme/sass/navigation/_menu-mobile-navigation.scss
  newspack-theme/sass/site/footer/_site-footer.scss
  newspack-theme/sass/site/secondary/_widgets.scss
  newspack-theme/sass/style.scss
  newspack-theme/sass/styles/style-default/style-default.scss
  newspack-theme/sass/typography/_headings.scss
  newspack-theme/template-parts/post/large-featured-image.php
  package-lock.json
  package.json
Labels: [Status] Approved

#1730 feat(newsletters): custom newsletter styles
  newspack-theme/functions.php
  newspack-theme/inc/newspack-newsletters.php
  newspack-theme/sass/plugins/newspack-newsletters-editor.scss
  scripts/compile-scss.js
Labels: [Status] Approved

#1737 Release Mar 22
  CHANGELOG.md
  newspack-joseph/sass/style.scss
  newspack-katharine/sass/style.scss
  newspack-nelson/sass/style.scss
  newspack-sacha/sass/style.scss
  newspack-scott/sass/style.scss
  newspack-theme/functions.php
  newspack-theme/sass/blocks/_blocks.scss
  newspack-theme/sass/style.scss
  package-lock.json
  package.json
Labels: [Status] Approved

#1738 Add `--wp--style--block-gap` default for the button block
  newspack-theme/sass/blocks/_blocks.scss
  newspack-theme/sass/style-editor-base.scss
Labels: [Status] Needs Review

#1742 Update ad spacing and move ad background styles
  newspack-theme/inc/color-patterns.php
  newspack-theme/inc/template-functions.php
  newspack-theme/sass/plugins/newspack-ads.scss
Labels: [Status] Approved

#1744 fix: remove bottom space from last block in cover block
  newspack-theme/sass/blocks/_blocks.scss
Labels: [Status] Approved, Smaller PR

#1747 Fix alignment of square logos when paired with the mobile CTA
  newspack-theme/sass/site/header/_site-header.scss
Labels: [Status] Approved, Smaller PR

#1746 fix: update approach to remove space with above footer ad
  newspack-theme/inc/template-functions.php
  newspack-theme/sass/plugins/newspack-ads.scss
Labels: [Status] Approved
