Repository Automattic/newspack-theme, pull requests merged in 2022-01, with the labels that each got.

#1628 chore(deps): implement dependabot auto-merge
  .github/workflows/auto-merge.yml
Labels: [Status] Approved, dependencies

#1647 chore: update post-release job to pull changelog and semver changes
  .circleci/config.yml
  CHANGELOG.md
Labels: [Status] Approved

#1659 Update post title styles for WP 5.9
  newspack-theme/inc/typography.php
  newspack-theme/sass/style-editor-base.scss
  newspack-theme/sass/style-editor-overrides.scss
Labels: [Status] Approved, wp 5.9

#1660 Update article subtitle preview selector
  newspack-theme/js/src/post-subtitle/utils.js
Labels: [Status] Approved, wp 5.9

#1650 chore: add CODEOWNERS file
  .github/CODEOWNERS
Labels: [Status] Approved

#1663 Update Pullquote block styles for WordPress 5.9
  newspack-joseph/sass/style-editor.scss
  newspack-joseph/sass/style.scss
  newspack-katharine/sass/style-editor.scss
  newspack-katharine/sass/style.scss
  newspack-nelson/sass/style-editor.scss
  newspack-nelson/sass/style.scss
  newspack-sacha/sass/style-editor.scss
  newspack-sacha/sass/style.scss
  newspack-scott/inc/child-color-patterns.php
  newspack-scott/sass/style-editor.scss
  newspack-scott/sass/style.scss
  newspack-theme/inc/color-patterns.php
  newspack-theme/sass/blocks/_blocks.scss
  newspack-theme/sass/style-editor-base.scss
Labels: [Status] Approved, wp 5.9

#1661 Update figcaption styles for WordPress 5.9
  newspack-theme/sass/style-editor-base.scss
Labels: [Status] Approved, wp 5.9

#1664 Correct Sacha post title styles for WordPress 5.9
  newspack-sacha/sass/child-style-editor-overrides.scss
  newspack-sacha/sass/style-editor.scss
Labels: [Status] Approved, wp 5.9

#1670 Update Column Block styles for WordPress 5.9.
  newspack-theme/sass/blocks/_blocks.scss
Labels: [Status] Approved, wp 5.9

#1674 Release Jan 18
  .circleci/config.yml
  .github/CODEOWNERS
  .github/workflows/auto-merge.yml
  CHANGELOG.md
  composer.json
  composer.lock
  newspack-joseph/sass/style-editor.scss
  newspack-joseph/sass/style.scss
  newspack-katharine/sass/style-editor.scss
  newspack-katharine/sass/style.scss
  newspack-nelson/sass/style-editor.scss
  newspack-nelson/sass/style.scss
  newspack-sacha/sass/child-style-editor-overrides.scss
  newspack-sacha/sass/style-editor.scss
  newspack-sacha/sass/style.scss
  newspack-scott/inc/child-color-patterns.php
  newspack-scott/sass/style-editor.scss
  newspack-scott/sass/style.scss
  newspack-theme/inc/color-patterns.php
  newspack-theme/inc/typography.php
  newspack-theme/js/src/post-subtitle/utils.js
  newspack-theme/sass/blocks/_blocks.scss
  newspack-theme/sass/style-editor-base.scss
  newspack-theme/sass/style-editor-overrides.scss
  newspack-theme/sass/style.scss
  package-lock.json
  package.json
Labels: [Status] Approved

#1675 Post-release 1/19/2022
  CHANGELOG.md
  newspack-joseph/sass/style.scss
  newspack-katharine/sass/style.scss
  newspack-nelson/sass/style.scss
  newspack-sacha/sass/style.scss
  newspack-scott/sass/style.scss
  newspack-theme/sass/style.scss
  package-lock.json
  package.json
Labels: [Status] Approved

#1629 Fix compatibility check for The Events Calendar to prevent critical/fatal errors
  newspack-theme/functions.php
Labels: [Status] Needs Review

#1677 chore: use newspack-scripts
  .circleci/config.yml
  .eslintrc.js
  .stylelintrc
  babel.config.js
  composer.json
  newspack-theme/js/src/amp-fallback-newspack-sponsors.js
  newspack-theme/js/src/amp-fallback.js
  newspack-theme/js/src/customize-controls.js
  newspack-theme/js/src/customize-preview.js
  newspack-theme/js/src/logo-customize-controls.js
  newspack-theme/js/src/logo-customize-preview.js
  newspack-theme/js/src/post-subtitle/utils.js
  newspack-theme/sass/plugins/woocommerce.scss
  package-lock.json
  package.json
  webpack.config.js
Labels: [Status] Approved

#1688 Release Jan 25
  CHANGELOG.md
  newspack-joseph/sass/style.scss
  newspack-katharine/sass/style.scss
  newspack-nelson/sass/style.scss
  newspack-sacha/sass/style.scss
  newspack-scott/sass/style.scss
  newspack-theme/functions.php
  newspack-theme/sass/style.scss
  package-lock.json
  package.json
Labels: [Status] Approved

#1689 Fix: prevent odd wrapping with multiple categories
  newspack-theme/inc/template-tags.php
Labels: [Status] Approved

#1691 fix: update styles for the Event Calendar download links
  newspack-theme/sass/plugins/the-events-calendar.scss
Labels: [Status] Approved

#1692 Improve mobile footer link tap target size
  newspack-theme/sass/site/footer/_site-footer.scss
  newspack-theme/sass/site/secondary/_widgets.scss
Labels: [Status] Approved

#1636 Fix remaining sticky header logo distortion
  newspack-theme/inc/logo-resizer.php
  newspack-theme/sass/site/header/_site-header.scss
Labels: [Status] Approved

#1698 chore: specify node version
  .nvmrc
Labels: [Status] Approved

#1693 Fix tag contrast issues in the Newspack theme
  newspack-theme/inc/color-patterns.php
  newspack-theme/sass/styles/style-default/style-default.scss
Labels: [Status] Approved
