Repository Automattic/newspack-theme, pull requests merged in 2023-07, with the labels that each got.

#2153 Release Jul 03
  CHANGELOG.md
  newspack-joseph/sass/theme-description.scss
  newspack-katharine/sass/theme-description.scss
  newspack-nelson/sass/theme-description.scss
  newspack-sacha/sass/theme-description.scss
  newspack-scott/sass/theme-description.scss
  newspack-theme/functions.php
  newspack-theme/inc/customizer.php
  newspack-theme/inc/newspack-multibranded-site-plugin.php
  newspack-theme/sass/site/primary/_posts-and-pages.scss
  newspack-theme/sass/site/secondary/_widgets.scss
  newspack-theme/sass/theme-description.scss
  package-lock.json
  package.json
Labels: [Status] Approved

#2150 fix(woocommerce): account page grid on member area
  newspack-theme/sass/plugins/woocommerce.scss
Labels: [Status] Approved

#2157 fix: add clamp to higher spacing values
  newspack-theme/sass/variables-site/_structure.scss
Labels: [Status] Approved

#2156 fix: Correct author bio truncation logic
  newspack-sacha/template-parts/post/author-bio.php
  newspack-theme/template-parts/post/author-bio.php
Labels: [Status] Approved

#2159 Make menu display functions pluggable
  newspack-theme/inc/template-tags.php
Labels: [Status] Needs Review

#2161 Release Jul 17
  CHANGELOG.md
  newspack-joseph/sass/theme-description.scss
  newspack-katharine/sass/theme-description.scss
  newspack-nelson/sass/theme-description.scss
  newspack-sacha/sass/theme-description.scss
  newspack-sacha/template-parts/post/author-bio.php
  newspack-scott/sass/theme-description.scss
  newspack-theme/sass/plugins/woocommerce.scss
  newspack-theme/sass/theme-description.scss
  newspack-theme/sass/variables-site/_structure.scss
  newspack-theme/template-parts/post/author-bio.php
  package-lock.json
  package.json
Labels: [Status] Approved

#2158 feat: add Threads logo to the social links menu
  newspack-theme/classes/class-newspack-svg-icons.php
Labels: [Status] Approved

#2162 feat: add downloads details to checkout
  newspack-theme/sass/plugins/woocommerce.scss
  newspack-theme/woocommerce/checkout/thankyou.php
Labels: [Status] Approved

#2165 feat: add styles for the details block
  newspack-theme/sass/blocks/_blocks.scss
  newspack-theme/sass/style-editor-base.scss
Labels: [Status] Approved, wp 6.3

#2166 feat: add styles for the footnote block
  newspack-theme/sass/blocks/_blocks.scss
Labels: [Status] Approved, wp 6.3

#2167 fix: improve new search setting appearance for WP 6.3
  newspack-theme/sass/blocks/_blocks.scss
  newspack-theme/sass/style-editor-base.scss
Labels: [Status] Approved, wp 6.3

#2168 fix: add padding to the file block when it has a background
  newspack-theme/sass/blocks/_blocks.scss
  newspack-theme/sass/style-editor-base.scss
Labels: [Status] Approved, wp 6.3
