Repository Automattic/newspack-theme, pull requests merged in 2023-11, with the labels that each got.

#2191 feat(woocommerce): remove woocommerce templates and dequeueing
  newspack-theme/inc/customizer.php
  newspack-theme/inc/woocommerce.php
  newspack-theme/woocommerce/checkout/form-checkout.php
  newspack-theme/woocommerce/checkout/thankyou.php
Labels: [Status] Needs Changes or Feeback, [Status] Approved

#2193 fix: reinstate WC CSS modifications
  newspack-theme/inc/woocommerce.php
Labels: [Status] Approved

#2196 feat: add WhatsApp icon
  newspack-theme/classes/class-newspack-svg-icons.php
Labels: [Status] Approved

#2195 fix: add a scroll-margin to anchors for sticky header
  newspack-theme/sass/blocks/_blocks.scss
Labels: [Status] Approved

#2200 Add script & style to HTML5 array
  newspack-theme/functions.php
Labels: [Status] Approved

#2194 feat: add single post option to display custom excerpt in lieu of subtitle
  newspack-theme/inc/customizer.php
  newspack-theme/template-parts/header/entry-header.php
Labels: [Status] Approved

#2201 fix: clears woo template cache
  newspack-theme/functions.php
  newspack-theme/woocommerce/templates.php
Labels: [Status] Approved

#2203 fix: avoid fatals on TEC updates
  newspack-theme/inc/the-events-calendar.php
Labels: [Status] Approved

#2204 Release Nov 13
  CHANGELOG.md
  newspack-joseph/sass/theme-description.scss
  newspack-katharine/sass/theme-description.scss
  newspack-nelson/sass/theme-description.scss
  newspack-sacha/sass/theme-description.scss
  newspack-scott/sass/theme-description.scss
  newspack-theme/functions.php
  newspack-theme/inc/customizer.php
  newspack-theme/inc/woocommerce.php
  newspack-theme/sass/theme-description.scss
  newspack-theme/woocommerce/checkout/form-checkout.php
  newspack-theme/woocommerce/checkout/thankyou.php
  newspack-theme/woocommerce/templates.php
  package-lock.json
  package.json
Labels: [Status] Approved

#2208 Release Nov 27
  CHANGELOG.md
  newspack-joseph/sass/theme-description.scss
  newspack-katharine/sass/theme-description.scss
  newspack-nelson/sass/theme-description.scss
  newspack-sacha/sass/theme-description.scss
  newspack-scott/sass/theme-description.scss
  newspack-theme/classes/class-newspack-svg-icons.php
  newspack-theme/inc/customizer.php
  newspack-theme/sass/blocks/_blocks.scss
  newspack-theme/sass/theme-description.scss
  newspack-theme/template-parts/header/entry-header.php
  package-lock.json
  package.json
Labels: [Status] Needs Review
