Repository Automattic/newspack-theme, pull requests merged in 2023-02, with the labels that each got.

#2032 fix: tweak styles for slideshow block's pagination
  newspack-theme/inc/typography.php
  newspack-theme/sass/media/_captions.scss
  newspack-theme/sass/style-editor-base.scss
  newspack-theme/sass/style-editor-overrides.scss
Labels: [Status] Approved

#2024 feat: remove inline CSS minification (in favor of newspack-plugin)
  newspack-theme/functions.php
Labels: [Status] Approved, Performance

#2025 Update menu ARIA labels, add missing button text
  newspack-theme/functions.php
  newspack-theme/inc/template-functions.php
  newspack-theme/inc/template-tags.php
  newspack-theme/js/src/amp-fallback.js
  newspack-theme/js/src/menu-accessibility.js
Labels: [Status] Approved

#2046 Jetpack Top Posts: improve styles and make image larger
  newspack-theme/inc/jetpack.php
  newspack-theme/inc/typography.php
  newspack-theme/sass/site/secondary/_widgets.scss
Labels: [Status] Approved

#2041 fix: Sacha author bio link
  newspack-sacha/template-parts/post/author-bio.php
Labels: [Type] Bug, [Status] Approved, [Theme] Sacha

#2047 fix: correct wide block width
  newspack-theme/sass/blocks/_blocks.scss
Labels: [Status] Approved

#2048 Release Feb 28
  CHANGELOG.md
  composer.lock
  newspack-joseph/sass/theme-description.scss
  newspack-katharine/sass/theme-description.scss
  newspack-nelson/sass/theme-description.scss
  newspack-sacha/sass/theme-description.scss
  newspack-scott/sass/theme-description.scss
  newspack-theme/functions.php
  newspack-theme/inc/template-functions.php
  newspack-theme/inc/template-tags.php
  newspack-theme/inc/typography.php
  newspack-theme/js/src/amp-fallback.js
  newspack-theme/js/src/menu-accessibility.js
  newspack-theme/sass/media/_captions.scss
  newspack-theme/sass/style-editor-base.scss
  newspack-theme/sass/style-editor-overrides.scss
  newspack-theme/sass/theme-description.scss
  package-lock.json
  package.json
Labels: [Status] Approved
