Repository Automattic/newspack-theme, pull requests merged in 2023-01, with the labels that each got.

#2010 fix: confirm query is explicitly for a page
  newspack-theme/inc/template-functions.php
Labels: [Status] Needs Review

#2012 fix: skip flex rule for newspack ad
  newspack-theme/sass/layout/_layout.scss
Labels: [Status] Approved

#2016 Release Jan 09
  CHANGELOG.md
  newspack-joseph/sass/theme-description.scss
  newspack-katharine/sass/theme-description.scss
  newspack-nelson/sass/theme-description.scss
  newspack-sacha/sass/theme-description.scss
  newspack-scott/sass/theme-description.scss
  newspack-theme/classes/class-newspack-svg-icons.php
  newspack-theme/sass/theme-description.scss
  package-lock.json
  package.json
Labels: [Status] Approved

#2017 feat: add Mastodon icon to the social links menu
  newspack-theme/classes/class-newspack-svg-icons.php
Labels: [Status] Approved

#2018 Alpha release Jan 13
  newspack-sacha/template-parts/post/author-bio.php
  newspack-theme/archive.php
  newspack-theme/classes/class-newspack-svg-icons.php
  newspack-theme/inc/template-functions.php
  newspack-theme/inc/template-tags.php
  newspack-theme/sass/layout/_layout.scss
  newspack-theme/template-parts/post/author-bio.php
  package-lock.json
  package.json
Labels: [Status] Needs Review

#2020 Feat: add 'flipped' option to display updated date per post
  newspack-theme/functions.php
  newspack-theme/inc/template-functions.php
  newspack-theme/js/src/post-meta-toggles.js
Labels: [Status] Approved

#2022 Set fetch priority on featured image
  newspack-theme/inc/template-tags.php
Labels: [Status] Approved, Performance

#2023 feat: add before and after page content hooks
  newspack-theme/template-parts/content/content-page.php
Labels: [Status] Approved, Performance

#2029 Release Jan 24
  CHANGELOG.md
  newspack-joseph/sass/theme-description.scss
  newspack-katharine/sass/theme-description.scss
  newspack-nelson/sass/theme-description.scss
  newspack-sacha/sass/theme-description.scss
  newspack-sacha/template-parts/post/author-bio.php
  newspack-scott/sass/theme-description.scss
  newspack-theme/archive.php
  newspack-theme/classes/class-newspack-svg-icons.php
  newspack-theme/inc/template-functions.php
  newspack-theme/inc/template-tags.php
  newspack-theme/sass/layout/_layout.scss
  newspack-theme/sass/theme-description.scss
  newspack-theme/template-parts/post/author-bio.php
  package-lock.json
  package.json
Labels: [Status] Approved
