Repository Automattic/newspack-theme, pull requests merged in 2024-07, with the labels that each got.

#2333 Release Jul 01
  CHANGELOG.md
  newspack-joseph/sass/theme-description.scss
  newspack-katharine/sass/theme-description.scss
  newspack-nelson/sass/theme-description.scss
  newspack-sacha/sass/theme-description.scss
  newspack-scott/sass/theme-description.scss
  newspack-theme/sass/theme-description.scss
  package-lock.json
  package.json
  webpack.config.js
Labels: [Status] Needs Review

#2341 fix: correct subtitle order for WP 6.6
  newspack-theme/js/src/post-subtitle/index.js
  newspack-theme/js/src/post-subtitle/utils.js
  newspack-theme/sass/style-editor-overrides.scss
Labels: [Status] Approved, wp 6.6

#2342 fix: remove margin from grid block
  newspack-theme/sass/blocks/_blocks.scss
Labels: [Status] Approved, wp 6.6

#2315 feat: add newspack-block-theme backwards compatibility
  newspack-theme/sass/blocks/_blocks.scss
  newspack-theme/sass/elements/_lists.scss
  newspack-theme/sass/style-editor-base.scss
Labels: [Status] Approved

#2347 Release Jul 15
  CHANGELOG.md
  composer.lock
  newspack-joseph/sass/theme-description.scss
  newspack-katharine/sass/theme-description.scss
  newspack-nelson/sass/theme-description.scss
  newspack-sacha/sass/theme-description.scss
  newspack-scott/sass/theme-description.scss
  newspack-theme/sass/plugins/newspack-publisher-media-kit.scss
  newspack-theme/sass/style-base.scss
  newspack-theme/sass/theme-description.scss
  package-lock.json
  package.json
Labels: [Status] Approved

#2350 fix(ras-acc): remove redundant checkout styles
  newspack-theme/sass/plugins/woocommerce.scss
Labels: [Status] Approved, ras-acc testing

#2355 Release Jul 29
  CHANGELOG.md
  composer.lock
  newspack-joseph/sass/theme-description.scss
  newspack-katharine/sass/theme-description.scss
  newspack-nelson/sass/theme-description.scss
  newspack-sacha/sass/theme-description.scss
  newspack-scott/sass/theme-description.scss
  newspack-theme/sass/blocks/_blocks.scss
  newspack-theme/sass/elements/_lists.scss
  newspack-theme/sass/style-editor-base.scss
  newspack-theme/sass/theme-description.scss
  package-lock.json
  package.json
Labels: [Status] Approved
